import Stafford38.ChallengeDefinitions

/-!
# Mathlib-only statement of the torsion-cyclicity corollary

This file gives the exact proposition in the shared `RingQuot` Weyl
presentation. Its proof is transported from the substantive Stafford formal
development by `tests/TorsionCyclicityConsumer.lean`.
-/

namespace Stafford38CorollaryChallenge

universe u v

abbrev PhaseVar (n : ℕ) := Stafford38Challenge.PhaseVar n

abbrev relation {k : Type u} [Field k] {n : ℕ}
    (omega : Matrix (PhaseVar n) (PhaseVar n) k)
    (a b : FreeAlgebra k (PhaseVar n)) : Prop :=
  Stafford38Challenge.relation (k := k) (n := n) omega a b

abbrev WeylAlg (k : Type u) [Field k] (n : ℕ) :=
  Stafford38Challenge.WeylAlg k n

abbrev IsRightTorsion {A : Type u} {M : Type v} [Ring A]
    [AddCommGroup M] [Module Aᵐᵒᵖ M] : Prop :=
  Stafford38.TorsionCyclicity.IsRightTorsion (A := A) (M := M)

/-- Every finitely generated torsion right module over a characteristic-zero
Weyl algebra is generated by one element. -/
def torsionCyclicStatement : Prop :=
  ∀ (k : Type u) [Field k] [CharZero k] (n : ℕ)
    (M : Type v) [AddCommGroup M]
    [Module (WeylAlg k n)ᵐᵒᵖ M]
    [Module.Finite (WeylAlg k n)ᵐᵒᵖ M],
    IsRightTorsion (A := WeylAlg k n) (M := M) →
      ∃ z : M, Submodule.span (WeylAlg k n)ᵐᵒᵖ ({z} : Set M) = ⊤

end Stafford38CorollaryChallenge
