import Mathlib.Algebra.RingQuot
import Mathlib.Algebra.FreeAlgebra
import Mathlib.LinearAlgebra.SymplecticGroup
import Mathlib.Order.Lattice.Nat

/-!
# Stafford's exact fixed-source strengthening

This file is the Mathlib-only challenge statement.  The Weyl algebra is the
free associative algebra on the phase variables modulo the Weyl commutator
relations.  The Bernstein filtration below is the span of the images of the
ordered PBW words of bounded total word degree, and `bernsteinDegree` is its
least membership level.  Thus the exponent in the statement is attached to
the presented element itself; it is not an extra degree or a supplied normal
form datum.
-/

namespace Stafford38FixedSourceChallenge

universe u

/-- The coordinate variables followed by the momentum variables. -/
abbrev PhaseVar (n : ℕ) := Fin n ⊕ Fin n

/-- The Weyl commutator relation on the free algebra. -/
def relation {k : Type u} [Field k] {n : ℕ}
    (omega : Matrix (PhaseVar n) (PhaseVar n) k)
    (a b : FreeAlgebra k (PhaseVar n)) : Prop :=
  ∃ i j,
    a = FreeAlgebra.ι k i * FreeAlgebra.ι k j -
      FreeAlgebra.ι k j * FreeAlgebra.ι k i ∧
    b = algebraMap k (FreeAlgebra k (PhaseVar n)) (omega i j)

/-- The presented Weyl algebra. -/
abbrev WeylAlg (k : Type u) [Field k] (n : ℕ) :=
  RingQuot (relation (k := k) (n := n) (Matrix.J (Fin n) k))

/-- A named generator in the presented quotient. -/
def generator (k : Type u) [Field k] (n : ℕ) (i : PhaseVar n) : WeylAlg k n :=
  RingQuot.mkAlgHom k (relation (k := k) (n := n) (Matrix.J (Fin n) k))
    (FreeAlgebra.ι k i)

/-- The old phase variables embedded into the next rank. -/
def oldIndex {n : ℕ} : PhaseVar n → PhaseVar (n + 1)
  | .inl i => .inl i.succ
  | .inr i => .inr i.succ

/-- Insert an old free-algebra word into the next-rank free algebra. -/
def freeOldMap (k : Type u) [Field k] (n : ℕ) :
    FreeAlgebra k (PhaseVar n) →ₐ[k] FreeAlgebra k (PhaseVar (n + 1)) :=
  FreeAlgebra.lift k (fun i => FreeAlgebra.ι k (oldIndex i))

/-- Ordered PBW words: old pairs first, then the newest coordinate and
momentum.  This is a free-algebra definition, so the filtration below is
independent of any project-specific normal-form construction. -/
def freeOrderedMonomial (k : Type u) [Field k] :
    (n : ℕ) → (Fin n → ℕ) → (Fin n → ℕ) → FreeAlgebra k (PhaseVar n)
  | 0, _, _ => 1
  | n + 1, a, p =>
      freeOldMap k n
          (freeOrderedMonomial k n (fun i => a i.succ) (fun i => p i.succ)) *
        FreeAlgebra.ι k (.inl (0 : Fin (n + 1))) ^ a 0 *
        FreeAlgebra.ι k (.inr (0 : Fin (n + 1))) ^ p 0

/-- The corresponding ordered word in the Weyl quotient. -/
def orderedMonomial (k : Type u) [Field k] (n : ℕ)
    (a p : Fin n → ℕ) : WeylAlg k n :=
  RingQuot.mkAlgHom k (relation (k := k) (n := n) (Matrix.J (Fin n) k))
    (freeOrderedMonomial k n a p)

/-- Total Bernstein weight of a phase exponent split into coordinates and
momenta. -/
def phaseDegree {n : ℕ} (a p : Fin n → ℕ) : ℕ :=
  (∑ i, a i) + ∑ i, p i

/-- The intrinsic Bernstein truncation generated by bounded ordered PBW
words. -/
def bernsteinPiece (k : Type u) [Field k] (n N : ℕ) :
    Submodule k (WeylAlg k n) :=
  Submodule.span k
    {z | ∃ a p : Fin n → ℕ,
      phaseDegree a p ≤ N ∧ z = orderedMonomial k n a p}

/-- Actual Bernstein degree: the least truncation containing the element.
The later transport proves that the defining set is nonempty and identifies
this infimum with the checked PBW normal-form degree. -/
noncomputable def bernsteinDegree (k : Type u) [Field k] {n : ℕ}
    (d : WeylAlg k n) : ℕ :=
  sInf {N : ℕ | d ∈ bernsteinPiece k n N}

/-- A linear combination of the named Weyl generators. -/
def linearCombination (k : Type u) [Field k] {n : ℕ}
    (M : Matrix (PhaseVar n) (PhaseVar n) k)
    (z : PhaseVar n → WeylAlg k n) (i : PhaseVar n) : WeylAlg k n :=
  ∑ j, algebraMap k (WeylAlg k n) (M i j) * z j

/-- The standard symplectic form in the phase-variable indexing. -/
abbrev standardForm (k : Type u) [Field k] (n : ℕ) :
    Matrix (PhaseVar n) (PhaseVar n) k := Matrix.J (Fin n) k

/-- A source coordinate obtained from an invertible symplectic linear change
of the Weyl generators. -/
def IsLinearWeylCoordinate (k : Type u) [Field k] (n : ℕ)
    (ell : WeylAlg k (n + 1)) : Prop :=
  ∃ (M N : Matrix (PhaseVar (n + 1)) (PhaseVar (n + 1)) k)
      (_hM : M * standardForm k (n + 1) * Matrix.transpose M =
        standardForm k (n + 1))
      (_hN : N * standardForm k (n + 1) * Matrix.transpose N =
        standardForm k (n + 1))
      (_hMN : M * N = 1) (_hNM : N * M = 1),
      ell = linearCombination k N (generator k (n + 1))
        (.inl (0 : Fin (n + 1)))

/-- The exact fixed-source statement, with the actual Bernstein degree of the
input operator as the source exponent. -/
def UniversalFixedSourceStatement : Prop :=
  ∀ (k : Type u) [Field k] [CharZero k] (n : ℕ)
    (d : WeylAlg k (n + 1)), d ≠ 0 →
      ∃ ell R S : WeylAlg k (n + 1),
        IsLinearWeylCoordinate k n ell ∧
          (1 : WeylAlg k (n + 1)) =
            d * R + ell ^ bernsteinDegree k d * d * S

/-- The compared theorem.  `FixedSourceSolution.lean` supplies the proof. -/
theorem universalFixedSourceStatement : UniversalFixedSourceStatement := by
  sorry

end Stafford38FixedSourceChallenge
