name = "stafford38Formal"
version = "1.2.3"
defaultTargets = ["Stafford38", "Solution", "FixedSourceSolution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "c55e6e786f49471c72fbddbec5415808896aec1e"

[[require]]
name = "algebraicAnalysis"
git = "https://github.com/itpplasma/algebraic-analysis.git"
rev = "bbbbf3fc358ca8100b158cec4cf47f336ab70163"

[[lean_lib]]
name = "Stafford38"

[[lean_lib]]
name = "proofs"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "FixedSourceChallenge"

[[lean_lib]]
name = "FixedSourceSolution"

[[lean_lib]]
name = "AlternativeSolution"

[[lean_lib]]
name = "AlternativeFixedSourceSolution"

[[lean_lib]]
name = "CorollaryChallenge"

[[lean_lib]]
name = "PaperPairChallenge"
