name = "stafford38Formal"
version = "1.2.3"
defaultTargets = ["Stafford38", "Solution", "FixedSourceSolution"]

[[require]]
name = "mathlib"
path = "../mathlib4"

[[require]]
name = "algebraicAnalysis"
path = "../algebraicAnalysis"

[[lean_lib]]
name = "Stafford38"

[[lean_lib]]
name = "proofs"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "FixedSourceChallenge"

[[lean_lib]]
name = "FixedSourceSolution"

[[lean_lib]]
name = "CorollaryChallenge"

[[lean_lib]]
name = "PaperPairChallenge"
