module
public import Stafford38.Weyl.EulerProductIdentities
public import Stafford38.FoundationClosure
public import Stafford38.TorsionCyclicity
public import Stafford38.NoncharacteristicHyperplane
public import Stafford38.NoncharacteristicHypersurface
public import Stafford38.LocalizedDifferentialCorollaries
public import Stafford38.LocalizationCorollaries
public import Stafford38.LeftHandedCorollary
public import Stafford38.EvolutionaryCorollary
public import Stafford38.Geometry.GeneralAsymptoticConormal
public import Stafford38.Geometry.GeneralCoisotropicSets
public import Stafford38.Geometry.GeneralCoisotropicCanonicalAdapter
public import Stafford38.Geometry.GeneralComponentConormalContainment
public import Stafford38.Geometry.GeneralTangentLimitCriterion
public import Stafford38.Geometry.GeneralTangentLatticePresentation
public import Stafford38.Geometry.GeneralCoisotropicSetsTest
public import Stafford38.Geometry.GeneralTangentLimitCriterionTest

@[expose] public section

/-! Stafford theorem, advertised corollaries, and independent geometry consumers. -/
