import Stafford38.MathlibCompat.MvPolynomialCoeff
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.MvPowerSeries.Equiv
import Stafford38.Geometry.AdicCompletionRingEquiv

set_option autoImplicit false

namespace Stafford38.Geometry.AffinePointCompletion

noncomputable section

open MvPolynomial

variable {k σ : Type*} [Field k] [Fintype σ]

/-- Translation sending the polynomial variable `X i` to `X i - p i`. -/
def translate (p : σ → k) : MvPolynomial σ k ≃ₐ[k] MvPolynomial σ k := by
  let f : MvPolynomial σ k →ₐ[k] MvPolynomial σ k :=
    MvPolynomial.aeval (fun i => X i - C (p i))
  let g : MvPolynomial σ k →ₐ[k] MvPolynomial σ k :=
    MvPolynomial.aeval (fun i => X i + C (p i))
  apply AlgEquiv.ofAlgHom f g
  · apply MvPolynomial.algHom_ext
    intro i
    simp [f, g]
  · apply MvPolynomial.algHom_ext
    intro i
    simp [f, g]

/-- The kernel of evaluation at the origin is the ideal generated by the variables. -/
theorem idealOfVars_eq_ker_eval_zero :
    MvPolynomial.idealOfVars σ k =
      RingHom.ker (MvPolynomial.aeval (fun _ : σ => (0 : k))) := by
  ext p
  change p ∈ Ideal.span (Set.range (X : σ → MvPolynomial σ k)) ↔ _
  rw [← Set.image_univ]
  rw [MvPolynomial.mem_ideal_span_X_image]
  simp only [Set.mem_univ, true_and, RingHom.mem_ker]
  have heval : MvPolynomial.aeval (fun _ : σ => (0 : k)) p =
      MvPolynomial.constantCoeff p := by
    simp
  rw [heval]
  constructor
  · intro h
    by_contra hconst
    have hzero : (0 : σ →₀ ℕ) ∈ p.support := MvPolynomial.mem_support_iff.mpr hconst
    obtain ⟨i, hi⟩ := h 0 hzero
    exact hi (by simp)
  · intro h
    have hconst : MvPolynomial.coeff 0 p = 0 := by
      simpa [MvPolynomial.constantCoeff_eq] using h
    intro m hm
    have hm0 : m ≠ 0 := by
      intro hz
      subst hz
      exact (MvPolynomial.mem_support_iff.mp hm) hconst
    have hcoords : ∃ i, m i ≠ 0 := by
      by_contra hnone
      apply hm0
      apply Finsupp.ext
      intro i
      by_contra hne
      exact hnone ⟨i, hne⟩
    exact hcoords

/-- The maximal evaluation ideal of the affine point `p`. -/
def pointIdeal (p : σ → k) : Ideal (MvPolynomial σ k) :=
  RingHom.ker (MvPolynomial.aeval p)

/-- Translation carries the origin ideal onto the evaluation ideal at `p`. -/
theorem pointIdeal_eq_map_translate (p : σ → k) :
    pointIdeal p = (MvPolynomial.idealOfVars σ k).map
      (translate p).toRingEquiv.toRingHom := by
  let e := (translate p).toRingEquiv.toRingHom
  have heval : (MvPolynomial.aeval p).comp (translate p).toAlgHom =
      MvPolynomial.aeval (fun _ : σ => (0 : k)) := by
    apply MvPolynomial.algHom_ext
    intro i
    simp [translate]
  have hcomap : Ideal.comap e (pointIdeal p) = MvPolynomial.idealOfVars σ k := by
    ext f
    change ((MvPolynomial.aeval p).comp (translate p).toAlgHom) f = 0 ↔
      f ∈ MvPolynomial.idealOfVars σ k
    rw [heval]
    rw [idealOfVars_eq_ker_eval_zero]
    rfl
  have hsurj : Function.Surjective e := (translate p).toRingEquiv.surjective
  have hmap := Ideal.map_comap_of_surjective e hsurj (pointIdeal p)
  rw [hcomap] at hmap
  exact hmap.symm

/-- The completed affine polynomial ring at a rational point is the multivariate
power-series ring, as a ring. This is the affine-chart model; it does not assert
that an arbitrary smooth local ring has this completion. -/
def powerSeriesCompletionAtPoint (p : σ → k) :
    MvPowerSeries σ k ≃+* AdicCompletion (pointIdeal p) (MvPolynomial σ k) := by
  let I := MvPolynomial.idealOfVars σ k
  let J := pointIdeal p
  have hJ : J = I.map (translate p).toRingEquiv.toRingHom := by
    simpa [I, J] using pointIdeal_eq_map_translate p
  exact (MvPowerSeries.toAdicCompletionAlgEquiv σ k).toRingEquiv.trans
    (AdicCompletionRingEquiv.ofRingEquiv (translate p).toRingEquiv I J hJ)

end
end Stafford38.Geometry.AffinePointCompletion
