import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Stafford38.Characteristic.BaseZeroSection
import Stafford38.Geometry.PointwiseConormalContainment

/-!
# Affine conormals are finite spans of equation differentials

For an ideal of equations in affine space and a rational point, define the
embedded Zariski tangent space as the common kernel of the evaluated
differentials.  Its annihilator is exactly the span of those differentials.
Because the ambient affine space is finite-dimensional, every conormal
covector is therefore an explicit finite linear combination of equation
differentials.

The final theorem feeds that finite representation into the pointwise
Hamiltonian-translation theorem.  No smoothness assumption is needed for this
linear-algebraic bridge.  What is not proved here is the scheme-geometric
identification of this equation-defined tangent space with the tangent fibre
of a smooth locus, or the passage from pointwise fibres to the closure of the
smooth conormal bundle.
-/

namespace Stafford38.Geometry.AffineConormalSpan

open Stafford38.Characteristic
open Stafford38.Characteristic.BaseRelativePoisson
open Stafford38.Characteristic.BaseZeroSection
open Stafford38.Characteristic.ReducedSupportIdeal
open Stafford38.Characteristic.ZeroSectionContainment
open Stafford38.Geometry.CoisotropicTranslation
open Stafford38.Geometry.PointwiseConormalContainment
open Stafford38.EulerSurjectivity
open Stafford38.WeylIteratedEquivalence

noncomputable section

variable {k : Type*} [Field k] {n : ℕ}

abbrev AffineTangentVector (k : Type*) (n : ℕ) := Fin n → k

/-- The differential of `f` at `y`, viewed as a linear functional on the
ambient affine tangent space. -/
def differentialCovector (y : Fin n → k) (f : MvPolynomial (Fin n) k) :
    Module.Dual k (AffineTangentVector k n) where
  toFun v := ∑ i, differentialAt y f i * v i
  map_add' u v := by simp [mul_add, Finset.sum_add_distrib]
  map_smul' a v := by simp [mul_assoc, mul_left_comm, mul_comm, Finset.mul_sum]

@[simp]
theorem differentialCovector_apply (y : Fin n → k)
    (f : MvPolynomial (Fin n) k) (v : AffineTangentVector k n) :
    differentialCovector y f v = ∑ i, differentialAt y f i * v i :=
  rfl

/-- Covectors generated by the differentials of all equations in `I`. -/
def equationCovectorSpan (y : Fin n → k)
    (I : Ideal (MvPolynomial (Fin n) k)) :
    Submodule k (Module.Dual k (AffineTangentVector k n)) :=
  Submodule.span k (Set.range fun f : I ↦ differentialCovector y f.1)

/-- The embedded Zariski tangent space cut out by the first-order parts of all
equations in `I`. -/
def zariskiTangentSpace (y : Fin n → k)
    (I : Ideal (MvPolynomial (Fin n) k)) :
    Submodule k (AffineTangentVector k n) :=
  (equationCovectorSpan y I).dualCoannihilator

/-- The embedded conormal space, defined as the annihilator of the embedded
Zariski tangent space. -/
def affineConormalSpace (y : Fin n → k)
    (I : Ideal (MvPolynomial (Fin n) k)) :
    Submodule k (Module.Dual k (AffineTangentVector k n)) :=
  (zariskiTangentSpace y I).dualAnnihilator

/-- The embedded conormal is exactly the span of evaluated differentials of
the equation ideal.  This is finite-dimensional double-annihilator duality. -/
theorem affineConormalSpace_eq_equationCovectorSpan
    (y : Fin n → k) (I : Ideal (MvPolynomial (Fin n) k)) :
    affineConormalSpace y I = equationCovectorSpan y I := by
  classical
  exact Subspace.dualCoannihilator_dualAnnihilator_eq

/-- Every embedded conormal covector has an explicit finite-support expansion
in differentials of equations. -/
theorem mem_affineConormalSpace_iff_exists_finsupp
    (y : Fin n → k) (I : Ideal (MvPolynomial (Fin n) k))
    (phi : Module.Dual k (AffineTangentVector k n)) :
    phi ∈ affineConormalSpace y I ↔
      ∃ c : I →₀ k,
        Finsupp.linearCombination k (fun f : I ↦ differentialCovector y f.1) c = phi := by
  classical
  rw [affineConormalSpace_eq_equationCovectorSpan]
  exact Finsupp.mem_span_range_iff_exists_finsupp

/-- The coordinate covector associated with a fibre coordinate `xi`. -/
def coordinateCovector (xi : Fin n → k) :
    Module.Dual k (AffineTangentVector k n) where
  toFun v := ∑ i, xi i * v i
  map_add' u v := by simp [mul_add, Finset.sum_add_distrib]
  map_smul' a v := by simp [mul_assoc, mul_left_comm, mul_comm, Finset.mul_sum]

@[simp]
theorem coordinateCovector_apply (xi v : Fin n → k) :
    coordinateCovector xi v = ∑ i, xi i * v i :=
  rfl

/-- Equality of coordinate covectors recovers equality of their coordinates. -/
theorem coordinateCovector_injective :
    Function.Injective (coordinateCovector (k := k) (n := n)) := by
  intro xi eta h
  funext i
  have hi := LinearMap.congr_fun h (Pi.single i 1)
  simpa [coordinateCovector, Pi.single_apply] using hi

/-- A conormal coordinate covector admits a finite-support expansion in
gradients of equations. -/
theorem coordinate_mem_affineConormalSpace_exists_finsupp
    (y xi : Fin n → k) (I : Ideal (MvPolynomial (Fin n) k)) :
    coordinateCovector xi ∈ affineConormalSpace y I →
      ∃ c : I →₀ k, ∀ i,
        xi i = ∑ f ∈ c.support, c f * differentialAt y f.1 i := by
  classical
  intro hxi
  obtain ⟨c, hc⟩ :=
    (mem_affineConormalSpace_iff_exists_finsupp y I (coordinateCovector xi)).mp hxi
  refine ⟨c, fun i ↦ ?_⟩
  have hi := LinearMap.congr_fun hc (Pi.single i 1)
  simpa [Finsupp.linearCombination_apply, differentialCovector, coordinateCovector,
    Pi.single_apply, Finsupp.sum, mul_comm, mul_left_comm, mul_assoc] using hi.symm

/-- The genuine conormal consumer: under the existing base-relative Poisson
hypothesis, every coordinate covector in the equation-defined affine
conormal space gives a common zero in the corresponding support fibre. -/
theorem affineConormal_coordinatePoint_isCommonZero
    [CharZero k]
    (J : Ideal (SymbolRing k n)) (hJ : IsBaseRelativePoisson J)
    (y : Fin n → k)
    (hzero : ∀ g ∈ J, MvPolynomial.eval (zeroSectionPoint y) g = 0)
    (I : Ideal (MvPolynomial (Fin n) k))
    (hlift : ∀ f : I, baseLift f.1 ∈ J)
    (xi : Fin n → k)
    (hxi : coordinateCovector xi ∈ affineConormalSpace y I) :
    ∀ g ∈ J, MvPolynomial.eval (Sum.elim y xi) g = 0 := by
  classical
  obtain ⟨c, hc⟩ :=
    coordinate_mem_affineConormalSpace_exists_finsupp y xi I hxi
  let ι := {f : I // f ∈ c.support}
  let equations : ι → MvPolynomial (Fin n) k := fun f ↦ f.1.1
  let coefficients : ι → k := fun f ↦ c f.1
  have hpoint : differentialCombinationPoint y coefficients equations = Sum.elim y xi := by
    funext q
    rcases q with i | i
    · rfl
    · simp only [differentialCombinationPoint, coefficients, equations, Sum.elim_inr]
      rw [hc i]
      exact (Finset.sum_subtype c.support (by simp)
        (fun f ↦ c f * differentialAt y f.1 i)).symm
  rw [← hpoint]
  exact differentialCombinationPoint_isCommonZero J hJ y hzero equations
    (fun f ↦ hlift f.1) coefficients

/-- Concrete characteristic-support form.  If `(y, eta)` lies in the reduced
order support and the required base-relative Gabber fragment holds, then the
entire equation-defined conormal space of the contracted base ideal over `y`
lies in the same reduced support fibre. -/
theorem reducedOrderSupport_affineConormal_coordinatePoint_isCommonZero
    [CharZero k]
    (W : RightIdeal (PresentedWeyl k n))
    (hJ : IsBaseRelativePoisson (reducedOrderSupportIdeal k W))
    (y eta : Fin n → k)
    (hpoint : ∀ g ∈ reducedOrderSupportIdeal k W,
      MvPolynomial.eval (Sum.elim y eta) g = 0)
    (xi : Fin n → k)
    (hxi : coordinateCovector xi ∈
      affineConormalSpace y (reducedOrderBaseIdeal k W)) :
    ∀ g ∈ reducedOrderSupportIdeal k W,
      MvPolynomial.eval (Sum.elim y xi) g = 0 := by
  apply affineConormal_coordinatePoint_isCommonZero
    (reducedOrderSupportIdeal k W) hJ y
    (zeroSection_mem_of_mem_reducedOrderSupport_zeroSet k W y eta hpoint)
    (reducedOrderBaseIdeal k W)
  · intro f
    exact (mem_reducedOrderBaseIdeal_iff k W f.1).mp f.2
  · exact hxi

/-- Stronger contracted-base form: every equation-defined conormal covector
over a common zero of the contracted base ideal lies in the reduced support
fibre. No auxiliary point of that fibre is required. -/
theorem reducedOrderBaseZero_affineConormal_coordinatePoint_isCommonZero
    [CharZero k]
    (W : RightIdeal (PresentedWeyl k n))
    (hJ : IsBaseRelativePoisson (reducedOrderSupportIdeal k W))
    (y : Fin n → k)
    (hy : ∀ f ∈ reducedOrderBaseIdeal k W,
      MvPolynomial.eval y f = 0)
    (xi : Fin n → k)
    (hxi : coordinateCovector xi ∈
      affineConormalSpace y (reducedOrderBaseIdeal k W)) :
    ∀ g ∈ reducedOrderSupportIdeal k W,
      MvPolynomial.eval (Sum.elim y xi) g = 0 := by
  apply affineConormal_coordinatePoint_isCommonZero
    (reducedOrderSupportIdeal k W) hJ y
    (zeroSection_mem_of_mem_reducedOrderBaseZeroSet k W y hy)
    (reducedOrderBaseIdeal k W)
  · intro f
    exact (mem_reducedOrderBaseIdeal_iff k W f.1).mp f.2
  · exact hxi

#print axioms affineConormalSpace_eq_equationCovectorSpan
#print axioms mem_affineConormalSpace_iff_exists_finsupp
#print axioms coordinate_mem_affineConormalSpace_exists_finsupp
#print axioms affineConormal_coordinatePoint_isCommonZero
#print axioms reducedOrderSupport_affineConormal_coordinatePoint_isCommonZero
#print axioms reducedOrderBaseZero_affineConormal_coordinatePoint_isCommonZero

end

end Stafford38.Geometry.AffineConormalSpan
