import Stafford38.Geometry.AsymptoticChartArcAdapter

/-!
# Annihilation by the completed chart arc

`CompletedProjectiveBoundaryChart` stores affine-ideal containment after
dehomogenizing in coordinate zero, while its normalized power-series chart
coordinate is the unrelated index `chart`.  This file makes the necessary
coordinate repair explicit.

The minimal strengthened certificate below retains the existing completed
chart and asks for the same kind of ideal containment after dehomogenizing in
its actual normalized chart, with precisely the coordinate ordering used by
`completedChartAffineArc`.  Projective equation vanishing then proves arc
annihilation; annihilation itself is not a field of the certificate.
-/

namespace Stafford38.Geometry.ChartArcAnnihilation

open Stafford38.Geometry.AsymptoticChartArcAdapter
open Stafford38.Geometry.CanonicalAsymptoticLaurentProducer
open Stafford38.Geometry.FormalDivisorLaurentConormal
open Stafford38.Geometry.ProjectiveBoundaryFrameRank
open Stafford38.Geometry.ScalarExtensionPoints

noncomputable section

universe u

variable {K : Type u} [Field K]

/-- Insert affine coordinates into an arbitrary projective chart, using the
same complement ordering as `completedChartAffineArc`. -/
def projectiveChartPoint {m : ℕ} (chart : Fin (m + 1))
    (y : Fin m → K) : Fin (m + 1) → K :=
  fun a ↦ if h : a = chart then 1
    else y ((chartAffineCoordinateEquiv chart).symm ⟨a, h⟩)

/-- Substitute the chart coordinate by one and the remaining projective
coordinates by the correspondingly ordered affine variables. -/
def projectiveDehomogenizeAt {m : ℕ} (chart : Fin (m + 1)) :
    MvPolynomial (Fin (m + 1)) K →ₐ[K] MvPolynomial (Fin m) K :=
  MvPolynomial.aeval fun a ↦ if h : a = chart then 1
    else MvPolynomial.X ((chartAffineCoordinateEquiv chart).symm ⟨a, h⟩)

/-- Evaluation after arbitrary-chart dehomogenization is evaluation at the
inserted projective chart point. -/
theorem eval_projectiveDehomogenizeAt {m : ℕ} (chart : Fin (m + 1))
    (p : MvPolynomial (Fin (m + 1)) K) (y : Fin m → K) :
    MvPolynomial.eval y (projectiveDehomogenizeAt chart p) =
      MvPolynomial.eval (projectiveChartPoint chart y) p := by
  rw [show projectiveDehomogenizeAt chart p =
      MvPolynomial.bind₁
        (fun a ↦ if h : a = chart then 1
          else MvPolynomial.X
            ((chartAffineCoordinateEquiv chart).symm ⟨a, h⟩)) p by rfl]
  rw [MvPolynomial.hom_bind₁]
  change MvPolynomial.eval₂ _ _ p = MvPolynomial.eval₂ _ _ p
  have hcoeff : (MvPolynomial.eval y).comp MvPolynomial.C = RingHom.id K := by
    ext a
    simp
  rw [hcoeff]
  apply MvPolynomial.eval₂_congr
  intro a
  by_cases h : a = chart
  · subst a
    simp [projectiveChartPoint]
  · simp [projectiveChartPoint, h]

/-- The affine ideal generated by dehomogenizing projective equations in the
specified chart. -/
def chartDehomogenizedEquationIdeal {m : ℕ} {ι : Type*}
    (chart : Fin (m + 1))
    (equations : ι → MvPolynomial (Fin (m + 1)) K) :
    Ideal (MvPolynomial (Fin m) K) :=
  Ideal.span (Set.range fun i ↦ projectiveDehomogenizeAt chart (equations i))

/-- Every polynomial in the chart-dehomogenized equation ideal vanishes at
an affine chart point whose inserted projective point kills the supplied
projective equations. -/
theorem eval_eq_zero_of_mem_chartDehomogenizedEquationIdeal
    {m : ℕ} {ι : Type*} (chart : Fin (m + 1))
    (equations : ι → MvPolynomial (Fin (m + 1)) K)
    (y : Fin m → K)
    (hvanish : ∀ i,
      MvPolynomial.eval (projectiveChartPoint chart y) (equations i) = 0)
    (f : MvPolynomial (Fin m) K)
    (hf : f ∈ chartDehomogenizedEquationIdeal chart equations) :
    MvPolynomial.eval y f = 0 := by
  have hle : chartDehomogenizedEquationIdeal chart equations ≤
      RingHom.ker (MvPolynomial.eval y) := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    change MvPolynomial.eval y
      (projectiveDehomogenizeAt chart (equations i)) = 0
    rw [eval_projectiveDehomogenizeAt]
    exact hvanish i
  exact hle hf

/-! ## Minimal completed-chart repair -/

/-- A completed projective chart together with affine-ideal containment in
the chart which is actually normalized to one.

This adds only a chart-relative algebraic containment, parallel to the
coordinate-zero containment already stored in `CompletedProjectiveBoundaryChart`.
It does not assume that the resulting arc annihilates the ideal. -/
structure ChartArcCompatibleBoundaryChart
    (k : Type u) [Field k] [CharZero k]
    (m : ℕ) (hm : 0 < m)
    (I : Ideal (MvPolynomial (Fin m) k)) where
  toCompleted : CompletedProjectiveBoundaryChart k m hm I
  chart_ideal_containment :
    I.map (scalarPolynomialMap
      (k := k) (K := LaurentSeries k) (Fin m)) ≤
      chartDehomogenizedEquationIdeal toCompleted.chart
        toCompleted.equations

/-- Inserting the completed affine chart arc recovers the original
projective Laurent column exactly. -/
theorem projectiveChartPoint_completedChartAffineArc
    {k : Type u} [Field k] [CharZero k]
    {m : ℕ} (hm : 0 < m)
    (I : Ideal (MvPolynomial (Fin m) k))
    (W : CompletedProjectiveBoundaryChart k m hm I) :
    projectiveChartPoint W.chart
        (fun i ↦ algebraMap (PowerSeries k) (LaurentSeries k)
          (completedChartAffineArc hm I W i)) =
      laurentColumn W.q := by
  funext a
  by_cases h : a = W.chart
  · subst a
    simp [projectiveChartPoint, laurentColumn, W.q_chart]
  · let i : Fin m :=
      (chartAffineCoordinateEquiv W.chart).symm ⟨a, h⟩
    have hi : chartAffineCoordinateEquiv W.chart i = ⟨a, h⟩ :=
      (chartAffineCoordinateEquiv W.chart).apply_symm_apply ⟨a, h⟩
    simp [projectiveChartPoint, h, completedChartAffineArc, laurentColumn,
      i, hi]

/-- The minimally repaired completed chart proves, rather than stores, that
its actual power-series affine chart arc annihilates the boundary ideal. -/
theorem completedChartAffineArc_annihilates
    {k : Type u} [Field k] [CharZero k]
    {m : ℕ} (hm : 0 < m)
    (I : Ideal (MvPolynomial (Fin m) k))
    (W : ChartArcCompatibleBoundaryChart k m hm I) :
    ∀ f ∈ I,
      MvPolynomial.eval₂ (algebraMap k (PowerSeries k))
        (completedChartAffineArc hm I W.toCompleted) f = 0 := by
  intro f hf
  let qLaurent : Fin m → LaurentSeries k := fun i ↦
    algebraMap (PowerSeries k) (LaurentSeries k)
      (completedChartAffineArc hm I W.toCompleted i)
  have hprojective : ∀ j,
      MvPolynomial.eval
        (projectiveChartPoint W.toCompleted.chart qLaurent)
        (W.toCompleted.equations j) = 0 := by
    intro j
    rw [projectiveChartPoint_completedChartAffineArc]
    exact W.toCompleted.equations_vanish j
  have hlaurent :
      MvPolynomial.eval₂ (algebraMap k (LaurentSeries k)) qLaurent f = 0 := by
    have hmem := W.chart_ideal_containment
      (Ideal.mem_map_of_mem
        (scalarPolynomialMap
          (k := k) (K := LaurentSeries k) (Fin m)) hf)
    have heval := eval_eq_zero_of_mem_chartDehomogenizedEquationIdeal
      W.toCompleted.chart W.toCompleted.equations qLaurent hprojective
      (scalarPolynomialMap
        (k := k) (K := LaurentSeries k) (Fin m) f) hmem
    simpa [eval_scalarPolynomialMap] using heval
  apply HahnSeries.ofPowerSeries_injective (Γ := ℤ)
  have hmap := MvPolynomial.eval₂_comp_left
    (algebraMap (PowerSeries k) (LaurentSeries k))
    (algebraMap k (PowerSeries k))
    (completedChartAffineArc hm I W.toCompleted) f
  have hcoeff :
      (algebraMap (PowerSeries k) (LaurentSeries k)).comp
          (algebraMap k (PowerSeries k)) =
        algebraMap k (LaurentSeries k) := by
    ext a
    simp [PowerSeries.algebraMap_eq, PowerSeries.coe_C,
      LaurentSeries.algebraMap_apply]
  rw [hcoeff] at hmap
  have hpoint :
      (algebraMap (PowerSeries k) (LaurentSeries k)) ∘
          completedChartAffineArc hm I W.toCompleted = qLaurent := by
    rfl
  rw [hpoint, hlaurent] at hmap
  simpa using hmap

#print axioms eval_projectiveDehomogenizeAt
#print axioms eval_eq_zero_of_mem_chartDehomogenizedEquationIdeal
#print axioms projectiveChartPoint_completedChartAffineArc
#print axioms completedChartAffineArc_annihilates

end

end Stafford38.Geometry.ChartArcAnnihilation
