import Stafford38.Geometry.AffineConormalClosure

/-!
# Comparing Jacobian and equation-defined affine conormals

An externally supplied smooth locus can be compared with the repository's
equation-defined conormal locus once its tangent space is identified with the
common kernel of a family of Jacobian rows.  This file isolates that exact
bridge.

The equations in the Jacobian family are required to belong to the ambient
ideal.  Under that hypothesis, their conormal space is contained in the
conormal space defined using all equations.  Consequently, if the supplied
tangent space agrees pointwise with the Jacobian kernel, its conormal locus
embeds into `equationConormalLocus`, and its field-valued algebraic closure
hull embeds into `equationConormalClosure`.

No smoothness criterion, scheme tangent-space construction, geometric-point
comparison, algebraic closedness, or base change is asserted here.  Those are
inputs to the comparison theorem, not consequences of it.
-/

namespace Stafford38.Geometry.JacobianConormalComparison

open Stafford38.Characteristic
open Stafford38.Characteristic.BaseRelativePoisson
open Stafford38.Characteristic.ReducedSupportIdeal
open Stafford38.Geometry.AffineConormalClosure
open Stafford38.Geometry.AffineConormalSpan
open Stafford38.EulerSurjectivity
open Stafford38.WeylIteratedEquivalence

noncomputable section

variable {k : Type*} [Field k] {n : ℕ}

/-- The span of the Jacobian rows of a chosen family of equations at `y`. -/
def jacobianCovectorSpan {ι : Type*} (y : Fin n → k)
    (equations : ι → MvPolynomial (Fin n) k) :
    Submodule k (Module.Dual k (AffineTangentVector k n)) :=
  Submodule.span k (Set.range fun i ↦ differentialCovector y (equations i))

/-- The tangent space cut out by the chosen Jacobian rows. -/
def jacobianTangentSpace {ι : Type*} (y : Fin n → k)
    (equations : ι → MvPolynomial (Fin n) k) :
    Submodule k (AffineTangentVector k n) :=
  (jacobianCovectorSpan y equations).dualCoannihilator

/-- The conormal space obtained as the annihilator of the Jacobian kernel. -/
def jacobianConormalSpace {ι : Type*} (y : Fin n → k)
    (equations : ι → MvPolynomial (Fin n) k) :
    Submodule k (Module.Dual k (AffineTangentVector k n)) :=
  (jacobianTangentSpace y equations).dualAnnihilator

/-- In finite-dimensional affine space, taking the annihilator of the
Jacobian kernel recovers the span of the Jacobian rows. -/
theorem jacobianConormalSpace_eq_jacobianCovectorSpan {ι : Type*}
    (y : Fin n → k) (equations : ι → MvPolynomial (Fin n) k) :
    jacobianConormalSpace y equations = jacobianCovectorSpan y equations := by
  classical
  exact Subspace.dualCoannihilator_dualAnnihilator_eq

/-- Jacobian rows coming from equations in `I` span a subspace of the
covectors generated by all equations in `I`. -/
theorem jacobianCovectorSpan_le_equationCovectorSpan {ι : Type*}
    (y : Fin n → k) (I : Ideal (MvPolynomial (Fin n) k))
    (equations : ι → MvPolynomial (Fin n) k)
    (hequations : ∀ i, equations i ∈ I) :
    jacobianCovectorSpan y equations ≤ equationCovectorSpan y I := by
  apply Submodule.span_le.mpr
  rintro _ ⟨i, rfl⟩
  apply Submodule.subset_span
  exact ⟨⟨equations i, hequations i⟩, rfl⟩

/-- The conormal computed from any chosen equations in `I` embeds in the
equation-defined affine conormal computed from the whole ideal. -/
theorem jacobianConormalSpace_le_affineConormalSpace {ι : Type*}
    (y : Fin n → k) (I : Ideal (MvPolynomial (Fin n) k))
    (equations : ι → MvPolynomial (Fin n) k)
    (hequations : ∀ i, equations i ∈ I) :
    jacobianConormalSpace y equations ≤ affineConormalSpace y I := by
  rw [jacobianConormalSpace_eq_jacobianCovectorSpan,
    affineConormalSpace_eq_equationCovectorSpan]
  exact jacobianCovectorSpan_le_equationCovectorSpan y I equations hequations

/-- The conormal locus of a supplied set of base points and supplied tangent
spaces.  For a smooth locally closed locus, callers instantiate `Y` with its
field-valued points and `T` with its scheme-theoretic tangent spaces. -/
def tangentConormalLocus
    (Y : Set (Fin n → k))
    (T : (Fin n → k) → Submodule k (AffineTangentVector k n)) :
    Set (PhaseVar n → k) :=
  {q | (fun i ↦ q (Sum.inl i)) ∈ Y ∧
    coordinateCovector (fun i ↦ q (Sum.inr i)) ∈
      (T (fun i ↦ q (Sum.inl i))).dualAnnihilator}

/-- Exact pointwise smooth-conormal comparison.

The caller supplies two geometric facts: points of `Y` satisfy `I`, and the
supplied tangent space on `Y` is the kernel of the displayed Jacobian rows.
The latter is the explicit Jacobian/tangent hypothesis normally furnished by
smoothness. -/
theorem tangentConormalLocus_subset_equationConormalLocus_of_eq_jacobian
    {ι : Type*}
    (I : Ideal (MvPolynomial (Fin n) k))
    (Y : Set (Fin n → k))
    (T : (Fin n → k) → Submodule k (AffineTangentVector k n))
    (equations : ι → MvPolynomial (Fin n) k)
    (hequations : ∀ i, equations i ∈ I)
    (hY : ∀ y ∈ Y, ∀ f ∈ I, MvPolynomial.eval y f = 0)
    (hT : ∀ y ∈ Y, T y = jacobianTangentSpace y equations) :
    tangentConormalLocus Y T ⊆ equationConormalLocus I := by
  intro q hq
  let y : Fin n → k := fun i ↦ q (Sum.inl i)
  let ξ : Fin n → k := fun i ↦ q (Sum.inr i)
  refine ⟨hY y hq.1, ?_⟩
  apply jacobianConormalSpace_le_affineConormalSpace y I equations hequations
  change coordinateCovector ξ ∈ jacobianConormalSpace y equations
  have hq' := hq.2
  change coordinateCovector ξ ∈ (T y).dualAnnihilator at hq'
  rw [hT y hq.1] at hq'
  exact hq'

/-- Closure-level form of the comparison: the field-valued algebraic closure
hull of the supplied tangent conormal locus lies in the equation-defined
conormal closure. -/
theorem tangentConormalClosure_subset_equationConormalClosure_of_eq_jacobian
    {ι : Type*}
    (I : Ideal (MvPolynomial (Fin n) k))
    (Y : Set (Fin n → k))
    (T : (Fin n → k) → Submodule k (AffineTangentVector k n))
    (equations : ι → MvPolynomial (Fin n) k)
    (hequations : ∀ i, equations i ∈ I)
    (hY : ∀ y ∈ Y, ∀ f ∈ I, MvPolynomial.eval y f = 0)
    (hT : ∀ y ∈ Y, T y = jacobianTangentSpace y equations) :
    MvPolynomial.zeroLocus k
        (MvPolynomial.vanishingIdeal k (tangentConormalLocus Y T)) ⊆
      equationConormalClosure I := by
  rw [equationConormalClosure]
  exact MvPolynomial.zeroLocus_anti_mono
    (MvPolynomial.vanishingIdeal_anti_mono
      (tangentConormalLocus_subset_equationConormalLocus_of_eq_jacobian
        I Y T equations hequations hY hT))

/-- Direct characteristic-support consumer.  Once the tangent data on `Y`
are identified with Jacobian kernels for equations in the contracted base
ideal, the closure of their conormal locus lies in reduced order support under
the existing base-relative Gabber fragment. -/
theorem tangentConormalClosure_subset_reducedOrderSupport_of_eq_jacobian
    [CharZero k]
    {ι : Type*}
    (W : RightIdeal (PresentedWeyl k n))
    (hJ : IsBaseRelativePoisson (reducedOrderSupportIdeal k W))
    (Y : Set (Fin n → k))
    (T : (Fin n → k) → Submodule k (AffineTangentVector k n))
    (equations : ι → MvPolynomial (Fin n) k)
    (hequations : ∀ i, equations i ∈ reducedOrderBaseIdeal k W)
    (hY : ∀ y ∈ Y, ∀ f ∈ reducedOrderBaseIdeal k W,
      MvPolynomial.eval y f = 0)
    (hT : ∀ y ∈ Y, T y = jacobianTangentSpace y equations) :
    MvPolynomial.zeroLocus k
        (MvPolynomial.vanishingIdeal k (tangentConormalLocus Y T)) ⊆
      MvPolynomial.zeroLocus k (reducedOrderSupportIdeal k W) := by
  exact (tangentConormalClosure_subset_equationConormalClosure_of_eq_jacobian
    (reducedOrderBaseIdeal k W) Y T equations hequations hY hT).trans
      (equationConormalClosure_subset_reducedOrderSupport W hJ)

#print axioms jacobianConormalSpace_eq_jacobianCovectorSpan
#print axioms jacobianCovectorSpan_le_equationCovectorSpan
#print axioms jacobianConormalSpace_le_affineConormalSpace
#print axioms tangentConormalLocus_subset_equationConormalLocus_of_eq_jacobian
#print axioms tangentConormalClosure_subset_equationConormalClosure_of_eq_jacobian
#print axioms tangentConormalClosure_subset_reducedOrderSupport_of_eq_jacobian

end

end Stafford38.Geometry.JacobianConormalComparison
