import Mathlib
import Stafford38.Geometry.DivisorTangentLattice
import Stafford38.Geometry.KaehlerSpanSeparableAdjoin

/-!
# Kähler visibility at a discrete valuation place

For a local ring whose maximal ideal is generated by `t`, the kernel of the
map from absolute Kähler differentials to residue-field differentials is the
sum of the line generated by `d t` and the maximal-ideal multiple of the
source module.  If the residue field is algebraic over the field generated by
the residues of a coordinate family, those coordinate differentials span the
remaining residue cotangent space.  Mapping this statement to the fraction
field gives the visibility condition used by `VisibleDivisorFrame`.
-/

namespace Stafford38.Geometry.KaehlerDVRVisibility

open IsLocalRing
open TensorProduct

noncomputable section
set_option linter.style.haveILetI false

universe u v

/-- Tensoring a module with `V/I` kills exactly the submodule `I • M`. -/
theorem ker_quotient_tensor_mk_one
    {V M : Type*} [CommRing V]
    [AddCommGroup M] [Module V M] (I : Ideal V) :
    LinearMap.ker (TensorProduct.mk V (V ⧸ I) M 1) =
      I • (⊤ : Submodule V M) := by
  ext x
  constructor
  · intro hx
    have hzero : TensorProduct.quotTensorEquivQuotSMul M I
        ((1 : V ⧸ I) ⊗ₜ[V] x) = 0 := by
      change (TensorProduct.quotTensorEquivQuotSMul M I)
        ((TensorProduct.mk V (V ⧸ I) M 1) x) = 0
      rw [LinearMap.mem_ker.mp hx, map_zero]
    rw [TensorProduct.quotTensorEquivQuotSMul_mk_one_tmul] at hzero
    exact (Submodule.Quotient.mk_eq_zero _).mp hzero
  · intro hx
    apply (TensorProduct.quotTensorEquivQuotSMul M I).injective
    change (TensorProduct.quotTensorEquivQuotSMul M I) ((1 : V ⧸ I) ⊗ₜ[V] x) =
      (TensorProduct.quotTensorEquivQuotSMul M I) 0
    rw [TensorProduct.quotTensorEquivQuotSMul_mk_one_tmul,
      (Submodule.Quotient.mk_eq_zero _).mpr hx, map_zero]

theorem ker_residue_tensor_mk_one
    {V M : Type*} [CommRing V] [IsLocalRing V]
    [AddCommGroup M] [Module V M] :
    LinearMap.ker (TensorProduct.mk V (ResidueField V) M 1) =
      maximalIdeal V • (⊤ : Submodule V M) := by
  change LinearMap.ker (TensorProduct.mk V (V ⧸ maximalIdeal V) M 1) = _
  exact ker_quotient_tensor_mk_one (maximalIdeal V)

/-- If the maximal ideal is generated by `t`, reduction of Kähler
differentials has kernel `V · d t + 𝔪 · Ω[V/k]`.

The summand generated by `d t` is essential: the kernel is generally larger
than `𝔪 · Ω[V/k]`. -/
theorem ker_kaehler_residue_map_eq
    {k V : Type*} [CommRing k] [CommRing V] [IsLocalRing V]
    [Algebra k V] (t : V) (hmax : maximalIdeal V = Ideal.span {t}) :
    LinearMap.ker
        (KaehlerDifferential.map k k V (ResidueField V)) =
      Submodule.span V {KaehlerDifferential.D k V t} ⊔
        maximalIdeal V • (⊤ : Submodule V (Ω[V⁄k])) := by
  let f : Ω[V⁄k] →ₗ[V] ResidueField V ⊗[V] Ω[V⁄k] :=
    TensorProduct.mk V (ResidueField V) Ω[V⁄k] 1
  let g : ResidueField V ⊗[V] Ω[V⁄k] →ₗ[ResidueField V] Ω[ResidueField V⁄k] :=
    KaehlerDifferential.mapBaseChange k V (ResidueField V)
  apply le_antisymm
  · intro ω hω
    have hgf : g (f ω) = 0 := by
      simpa [f, g, KaehlerDifferential.mapBaseChange_tmul] using
        (LinearMap.mem_ker.mp hω)
    have hfrange : f ω ∈ LinearMap.range
        (KaehlerDifferential.kerCotangentToTensor k V (ResidueField V)) := by
      rw [KaehlerDifferential.range_kerCotangentToTensor k V (ResidueField V)
        IsLocalRing.residue_surjective]
      exact hgf
    obtain ⟨z, hz⟩ := hfrange
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective _ z
    have hxmax : (x : V) ∈ maximalIdeal V := by
      simpa only [IsLocalRing.ker_residue, ResidueField.algebraMap_eq] using x.property
    rw [hmax, Ideal.mem_span_singleton] at hxmax
    obtain ⟨a, ha⟩ := hxmax
    have hfa : f (a • KaehlerDifferential.D k V t) =
        KaehlerDifferential.kerCotangentToTensor k V (ResidueField V)
          (Ideal.toCotangent _ x) := by
      have htresidue : residue V t = 0 :=
        (IsLocalRing.residue_eq_zero_iff t).2
          (hmax.symm ▸ Ideal.mem_span_singleton_self t)
      rw [KaehlerDifferential.kerCotangentToTensor_toCotangent]
      rw [ha, Derivation.leibniz]
      simp only [f, map_smul, TensorProduct.tmul_add,
        TensorProduct.tmul_smul, TensorProduct.smul_tmul']
      simp [Algebra.smul_def, htresidue]
      change (algebraMap V (ResidueField V) a) •
          ((1 : ResidueField V) ⊗ₜ[V] KaehlerDifferential.D k V t) = _
      rw [ResidueField.algebraMap_eq, TensorProduct.smul_tmul']
      simp
    have hdiff : ω - a • KaehlerDifferential.D k V t ∈
        maximalIdeal V • (⊤ : Submodule V (Ω[V⁄k])) := by
      rw [← ker_residue_tensor_mk_one]
      apply LinearMap.mem_ker.mpr
      rw [map_sub, hfa, ← hz, sub_self]
    rw [show ω = a • KaehlerDifferential.D k V t +
        (ω - a • KaehlerDifferential.D k V t) by abel]
    exact Submodule.add_mem _
      (Submodule.mem_sup_left (Submodule.smul_mem _ _
        (Submodule.subset_span (Set.mem_singleton _))))
      (Submodule.mem_sup_right hdiff)
  · refine sup_le ?_ ?_
    · rw [Submodule.span_le]
      rintro _ rfl
      apply LinearMap.mem_ker.mpr
      rw [KaehlerDifferential.map_D,
        ResidueField.algebraMap_eq,
        (IsLocalRing.residue_eq_zero_iff t).2 (hmax.symm ▸ Ideal.mem_span_singleton_self t)]
      simp
    · intro ω hω
      apply LinearMap.mem_ker.mpr
      have hf : f ω = 0 := by
        rw [← LinearMap.mem_ker, ker_residue_tensor_mk_one]
        exact hω
      simpa [f, g, KaehlerDifferential.mapBaseChange_tmul] using
        congrArg g hf

/-- In characteristic zero, coordinate differentials span after an algebraic
extension of the field generated by the coordinates. -/
theorem kaehler_span_of_isAlgebraic_adjoin
    {k K : Type u} {ι : Type v} [Field k] [CharZero k] [Field K] [Algebra k K]
    (q : ι → K)
    (halg : Algebra.IsAlgebraic
      (IntermediateField.adjoin k (Set.range q) : IntermediateField k K) K) :
    Submodule.span K
      (Set.range fun i ↦ KaehlerDifferential.D k K (q i)) = ⊤ := by
  let L : IntermediateField k K :=
    IntermediateField.adjoin k (Set.range q)
  let qL : ι → L := fun i ↦
    ⟨q i, IntermediateField.subset_adjoin k (Set.range q) ⟨i, rfl⟩⟩
  letI : Algebra L K := L.toSubalgebra.toAlgebra
  letI : IsScalarTower k L K :=
    IsScalarTower.of_algebraMap_eq (fun _ ↦ rfl)
  letI : Algebra.IsAlgebraic L K := halg
  letI : Algebra.IsSeparable L K := inferInstance
  have hgenL : IntermediateField.adjoin k (Set.range qL) = ⊤ := by
    apply top_unique
    rintro ⟨z, hz⟩ -
    apply IntermediateField.adjoin_induction k
        (p := fun x hx ↦
          (⟨x, hx⟩ : L) ∈ IntermediateField.adjoin k (Set.range qL))
    · intro x hx
      obtain ⟨i, rfl⟩ := hx
      exact IntermediateField.subset_adjoin k _ ⟨i, rfl⟩
    · intro a
      exact (IntermediateField.adjoin k (Set.range qL)).algebraMap_mem a
    · intro a b _ _ ha hb
      exact (IntermediateField.adjoin k (Set.range qL)).add_mem ha hb
    · intro a _ ha
      exact (IntermediateField.adjoin k (Set.range qL)).inv_mem ha
    · intro a b _ _ ha hb
      exact (IntermediateField.adjoin k (Set.range qL)).mul_mem ha hb
  have hspan :=
    Stafford38.Geometry.KaehlerSpanSeparableAdjoin.kaehler_span_of_separable_adjoin_eq_top
      (k := k) (E := L) (K := K) qL hgenL
  simpa only [qL, IntermediateField.algebraMap_apply] using hspan

/-- The source differential module is generated modulo the maximal ideal by
`d t` and the chosen coordinate differentials. -/
theorem kaehler_le_coordinate_span_sup_maximalIdeal_smul
    {k V : Type u} {ι : Type v}
    [Field k] [CharZero k] [CommRing V] [IsLocalRing V] [Algebra k V]
    (t : V) (hmax : maximalIdeal V = Ideal.span {t}) (q : ι → V)
    (halg : Algebra.IsAlgebraic
      (IntermediateField.adjoin k
        (Set.range fun i ↦ residue V (q i)) :
          IntermediateField k (ResidueField V))
      (ResidueField V)) :
    (⊤ : Submodule V (Ω[V⁄k])) ≤
      (Submodule.span V {KaehlerDifferential.D k V t} ⊔
          Submodule.span V
            (Set.range fun i ↦ KaehlerDifferential.D k V (q i))) ⊔
        maximalIdeal V • (⊤ : Submodule V (Ω[V⁄k])) := by
  let C : Submodule V (Ω[V⁄k]) :=
    Submodule.span V {KaehlerDifferential.D k V t} ⊔
      Submodule.span V (Set.range fun i ↦ KaehlerDifferential.D k V (q i))
  let S : Submodule (ResidueField V) (Ω[ResidueField V⁄k]) :=
    Submodule.span (ResidueField V)
      (Set.range fun i ↦ KaehlerDifferential.D k (ResidueField V) (residue V (q i)))
  have hS : S = ⊤ := kaehler_span_of_isAlgebraic_adjoin
    (fun i ↦ residue V (q i)) halg
  intro ω _
  have himage : KaehlerDifferential.map k k V (ResidueField V) ω ∈ S := by
    rw [hS]
    trivial
  have hlift : ∀ z ∈ S, ∃ η ∈ C,
      KaehlerDifferential.map k k V (ResidueField V) η = z := by
    intro z hz
    induction hz using Submodule.span_induction with
    | mem z hz =>
        obtain ⟨i, rfl⟩ := hz
        refine ⟨KaehlerDifferential.D k V (q i), ?_, ?_⟩
        · exact Submodule.mem_sup_right (Submodule.subset_span ⟨i, rfl⟩)
        · rw [KaehlerDifferential.map_D, ResidueField.algebraMap_eq]
    | zero => exact ⟨0, C.zero_mem, map_zero _⟩
    | add x y hx hy hx' hy' =>
        obtain ⟨x', hx'C, hx'map⟩ := hx'
        obtain ⟨y', hy'C, hy'map⟩ := hy'
        refine ⟨x' + y', C.add_mem hx'C hy'C, ?_⟩
        rw [map_add, hx'map, hy'map]
    | smul a x hx hx' =>
        obtain ⟨x', hx'C, hx'map⟩ := hx'
        obtain ⟨a', ha'⟩ := IsLocalRing.residue_surjective a
        refine ⟨a' • x', C.smul_mem a' hx'C, ?_⟩
        rw [map_smul, hx'map]
        change (algebraMap V (ResidueField V) a') • x = a • x
        rw [ResidueField.algebraMap_eq, ha']
  obtain ⟨η, hηC, hη⟩ := hlift _ himage
  have hker : ω - η ∈ LinearMap.ker
      (KaehlerDifferential.map k k V (ResidueField V)) := by
    apply LinearMap.mem_ker.mpr
    rw [map_sub, hη, sub_self]
  rw [ker_kaehler_residue_map_eq t hmax] at hker
  obtain ⟨δ, hδdt, μ, hμm, hsum⟩ := Submodule.mem_sup.mp hker
  rw [show ω = η + (δ + μ) by rw [hsum]; abel]
  exact Submodule.add_mem _
    (Submodule.mem_sup_left hηC)
    (Submodule.add_mem _
      (Submodule.mem_sup_left
        (Submodule.mem_sup_left hδdt))
      (Submodule.mem_sup_right hμm))

/-- The image of `Ω[V/k]` in `Ω[F/k]` satisfies the visibility condition
for an independent generator `t` of the maximal ideal. -/
theorem kaehler_image_visible
    {k V F : Type u} {ι : Type v}
    [Fintype ι]
    [Field k] [CharZero k] [CommRing V] [IsLocalRing V] [Field F]
    [Algebra k V] [Algebra k F] [Algebra V F] [IsScalarTower k V F]
    (t : V) (hmax : maximalIdeal V = Ideal.span {t}) (q : ι → V)
    (halg : Algebra.IsAlgebraic
      (IntermediateField.adjoin k
        (Set.range fun i ↦ residue V (q i)) :
          IntermediateField k (ResidueField V))
      (ResidueField V)) :
    LinearMap.range (KaehlerDifferential.map k k V F) ≤
      Stafford38.Geometry.DivisorTangentLattice.coordinateFrame
          (KaehlerDifferential.D k F) t q ⊔
        Ideal.span {t} •
          LinearMap.range (KaehlerDifferential.map k k V F) := by
  let φ : Ω[V⁄k] →ₗ[V] Ω[F⁄k] :=
    KaehlerDifferential.map k k V F
  let C : Submodule V (Ω[V⁄k]) :=
    Submodule.span V {KaehlerDifferential.D k V t} ⊔
      Submodule.span V (Set.range fun i ↦ KaehlerDifferential.D k V (q i))
  let CF : Submodule V (Ω[F⁄k]) :=
    Stafford38.Geometry.DivisorTangentLattice.coordinateFrame
      (KaehlerDifferential.D k F) t q
  have hsource := kaehler_le_coordinate_span_sup_maximalIdeal_smul
    t hmax q halg
  have hcoord : C ≤ Submodule.comap φ CF := by
    refine sup_le ?_ ?_
    · rw [Submodule.span_le, Set.singleton_subset_iff]
      change φ (KaehlerDifferential.D k V t) ∈ CF
      change KaehlerDifferential.map k k V F
        (KaehlerDifferential.D k V t) ∈ CF
      rw [KaehlerDifferential.map_D]
      exact Submodule.mem_sup_left
        (Submodule.subset_span (Set.mem_singleton _))
    · rw [Submodule.span_le]
      rintro _ ⟨i, rfl⟩
      change φ (KaehlerDifferential.D k V (q i)) ∈ CF
      change KaehlerDifferential.map k k V F
        (KaehlerDifferential.D k V (q i)) ∈ CF
      rw [KaehlerDifferential.map_D]
      exact Stafford38.Geometry.DivisorTangentLattice.dQ_mem_coordinateFrame
        (KaehlerDifferential.D k F) t q i
  rintro w ⟨ω, rfl⟩
  have hω := hsource (show ω ∈ (⊤ : Submodule V (Ω[V⁄k])) from trivial)
  rw [hmax] at hω
  obtain ⟨η, hηC, μ, hμm, hsum⟩ := Submodule.mem_sup.mp hω
  have hηCF : φ η ∈ CF := hcoord hηC
  have hμW : φ μ ∈ Ideal.span {t} • LinearMap.range φ := by
    have hmapped : φ μ ∈ Submodule.map φ
        (Ideal.span {t} • (⊤ : Submodule V (Ω[V⁄k]))) :=
      Submodule.mem_map_of_mem hμm
    rwa [Submodule.map_smul'', Submodule.map_top] at hmapped
  rw [← hsum, map_add]
  exact Submodule.add_mem _
    (Submodule.mem_sup_left hηCF)
    (Submodule.mem_sup_right hμW)

/-- Package the Kähler image as the lattice of a visible divisor frame once
the independent DVR and projective-order data have been supplied. -/
theorem exists_visibleDivisorFrame_of_kaehler_image
    {k V F : Type u} {ι : Type v}
    [Fintype ι]
    [Field k] [CharZero k] [CommRing V] [IsLocalRing V] [Field F]
    [Algebra k V] [Algebra k F] [Algebra V F] [IsScalarTower k V F]
    [Module.Finite V (Ω[V⁄k])]
    (Q₀ Q₁ t u w : V) (Q : ι → V) (a e : ℕ) (j₀ : ι)
    (hmax : maximalIdeal V = Ideal.span {t})
    (t_ne : t ≠ 0) (u_unit : IsUnit u)
    (one_le_a : 1 ≤ a) (one_le_e : 1 ≤ e)
    (Q₀_eq : Q₀ = t ^ a * u) (Q₁_eq : Q₁ = t ^ (a + e) * w)
    (Q_j₀ : Q j₀ = 1)
    (halg : Algebra.IsAlgebraic
      (IntermediateField.adjoin k
        (Set.range fun i ↦ residue V (Q i)) :
          IntermediateField k (ResidueField V))
      (ResidueField V)) :
    ∃ D : Stafford38.Geometry.DivisorTangentLattice.VisibleDivisorFrame
        (V := V) (KaehlerDifferential.D k F) ι,
      D.Q₀ = Q₀ ∧ D.Q₁ = Q₁ ∧ D.t = t ∧ D.u = u ∧ D.w = w ∧
        D.Q = Q ∧ D.a = a ∧ D.e = e ∧ D.j₀ = j₀ ∧
        D.W = LinearMap.range (KaehlerDifferential.map k k V F) := by
  let φ : Ω[V⁄k] →ₗ[V] Ω[F⁄k] :=
    KaehlerDifferential.map k k V F
  have W_fg : (LinearMap.range φ).FG := by
    rw [LinearMap.range_eq_map]
    exact Module.Finite.fg_top.map φ
  let D : Stafford38.Geometry.DivisorTangentLattice.VisibleDivisorFrame
      (V := V) (KaehlerDifferential.D k F) ι :=
    { Q₀ := Q₀
      Q₁ := Q₁
      t := t
      u := u
      w := w
      Q := Q
      a := a
      e := e
      j₀ := j₀
      W := LinearMap.range φ
      t_mem := hmax.symm ▸ Ideal.mem_span_singleton_self t
      t_ne := t_ne
      u_unit := u_unit
      a_unit := by
        have hak : (a : k) ≠ 0 := Nat.cast_ne_zero.mpr
          (Nat.ne_of_gt (lt_of_lt_of_le Nat.zero_lt_one one_le_a))
        exact_mod_cast (isUnit_iff_ne_zero.mpr hak).map (algebraMap k V)
      one_le_a := one_le_a
      one_le_e := one_le_e
      Q₀_eq := Q₀_eq
      Q₁_eq := Q₁_eq
      Q_j₀ := Q_j₀
      W_fg := W_fg
      dt_mem := ⟨KaehlerDifferential.D k V t, by
        simp only [φ, KaehlerDifferential.map_D]⟩
      du_mem := ⟨KaehlerDifferential.D k V u, by
        simp only [φ, KaehlerDifferential.map_D]⟩
      dw_mem := ⟨KaehlerDifferential.D k V w, by
        simp only [φ, KaehlerDifferential.map_D]⟩
      dQ_mem := fun j ↦ ⟨KaehlerDifferential.D k V (Q j), by
        simp only [φ, KaehlerDifferential.map_D]⟩
      visible := kaehler_image_visible t hmax Q halg }
  exact ⟨D, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

#print axioms ker_kaehler_residue_map_eq
#print axioms kaehler_image_visible
#print axioms exists_visibleDivisorFrame_of_kaehler_image

end

end Stafford38.Geometry.KaehlerDVRVisibility
