import Stafford38.Geometry.KaehlerDVRVisibility
import Stafford38.Geometry.DivisorTangentLattice
import Stafford38.Geometry.KaehlerSpanSeparableAdjoin
import Stafford38.Geometry.GenericPointKaehlerConormal
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.LinearIndependent.BaseChange

/-!
# Generic Kähler rank at a retained divisorial place

A finite differential lattice over a DVR has generic rank at most one more
than the dimension of the residue-field cotangent space.  The proof uses the
actual Kähler module of the fraction field, reduction modulo the divisor, and
Nakayama; it does not assume a tangent-dimension estimate.
-/

namespace Stafford38.Geometry.PaperGenericTangentRank

open IsLocalRing
open Stafford38.Geometry.CoisotropicTranslation
open Stafford38.Geometry.DivisorTangentLattice
open Stafford38.Geometry.KaehlerDVRVisibility

noncomputable section

universe u v w

/-- A finite family spanning a finite-dimensional vector space contains a
subfamily indexed by its finrank which still spans. -/
theorem exists_spanning_subfamily_of_span_eq_top
    {K M ι : Type*} [Field K] [AddCommGroup M] [Module K M]
    [FiniteDimensional K M] [Fintype ι]
    (v : ι → M)
    (hspan : Submodule.span K (Set.range v) = ⊤) :
    ∃ rows : Fin (Module.finrank K M) ↪ ι,
      Submodule.span K (Set.range fun i ↦ v (rows i)) = ⊤ := by
  classical
  let b := Module.Basis.ofSpan (K := K)
    (s := Set.range v) hspan.ge
  letI : Fintype ((linearIndepOn_empty K (id : M → M)).extend
      (Set.empty_subset (Set.range v))) := Fintype.ofFinite _
  let e : Fin (Module.finrank K M) ≃
      ((linearIndepOn_empty K (id : M → M)).extend
        (Set.empty_subset (Set.range v))) :=
    Fintype.equivOfCardEq (by
      rw [Fintype.card_fin, ← Module.finrank_eq_card_basis b])
  have hb_range (a : Fin (Module.finrank K M)) : b (e a) ∈ Set.range v :=
    Module.Basis.ofSpan_subset (K := K) (V := M) hspan.ge ⟨e a, rfl⟩
  let row (a : Fin (Module.finrank K M)) : ι := Classical.choose (hb_range a)
  have hrow (a : Fin (Module.finrank K M)) : v (row a) = b (e a) :=
    Classical.choose_spec (hb_range a)
  have hrows : Function.Injective row := by
    intro a a' haa'
    apply e.injective
    apply b.injective
    rw [← hrow a, ← hrow a', haa']
  let rows : Fin (Module.finrank K M) ↪ ι := ⟨row, hrows⟩
  refine ⟨rows, ?_⟩
  have hrange : Set.range (fun a : Fin (Module.finrank K M) ↦ v (rows a)) =
      Set.range b := by
    ext z
    constructor
    · rintro ⟨a, rfl⟩
      exact ⟨e a, (hrow a).symm⟩
    · rintro ⟨j, rfl⟩
      refine ⟨e.symm j, ?_⟩
      change v (row (e.symm j)) = b j
      rw [hrow, e.apply_symm_apply]
  rw [hrange, b.span_eq]

end

end Stafford38.Geometry.PaperGenericTangentRank

namespace Stafford38.Geometry.PaperGenericTangentRank

open IsLocalRing
open Stafford38.Geometry.DivisorTangentLattice
open Stafford38.Geometry.KaehlerDVRVisibility

noncomputable section

set_option maxHeartbeats 1000000

universe u v w x

/-- A finite family over which the whole residue field is algebraic supplies
a spanning subfamily of Kähler differentials of cardinality `finrank`. -/
theorem exists_residue_kaehler_basis_rows_of_algebraic_generators
    {k K : Type u} [Field k] [CharZero k] [Field K] [Algebra k K]
    {ι : Type v} [Fintype ι] (q : ι → K)
    (halg : Algebra.IsAlgebraic
      (IntermediateField.adjoin k (Set.range q) : IntermediateField k K) K) :
    ∃ rows : Fin (Module.finrank K (Ω[K⁄k])) → ι,
      Submodule.span K
        (Set.range fun i ↦ KaehlerDifferential.D k K (q (rows i))) = ⊤ := by
  classical
  have hspan : Submodule.span K
      (Set.range fun i ↦ KaehlerDifferential.D k K (q i)) = ⊤ :=
    Stafford38.Geometry.KaehlerDVRVisibility.kaehler_span_of_isAlgebraic_adjoin
      q halg
  letI : FiniteDimensional K (Ω[K⁄k]) := by
    letI : FiniteDimensional K
        (Submodule.span K
          (Set.range fun i ↦ KaehlerDifferential.D k K (q i))) :=
      FiniteDimensional.span_of_finite K (Set.finite_range _)
    letI : FiniteDimensional K (⊤ : Submodule K (Ω[K⁄k])) :=
      (LinearEquiv.ofEq _ _ hspan).finiteDimensional
    exact Submodule.topEquiv.finiteDimensional
  obtain ⟨rows, hrows⟩ := exists_spanning_subfamily_of_span_eq_top
    (fun i ↦ KaehlerDifferential.D k K (q i)) hspan
  exact ⟨fun i ↦ rows i, hrows⟩

/-- A visible divisor lattice is generated by the uniformizer differential
and any residue-coordinate subfamily whose differentials span the residue
cotangent space. -/
theorem visibleFrame_le_selectedCoordinateFrame
    {k V F : Type*} [Field k] [CharZero k] [CommRing V] [IsLocalRing V]
    [Field F] [Algebra k V] [Algebra k F] [Algebra V F]
    [IsScalarTower k V F]
    {ι : Type x} [Fintype ι]
    (D : VisibleDivisorFrame (V := V) (KaehlerDifferential.D k F) ι)
    (hmax : maximalIdeal V = Ideal.span {D.t})
    (himage : ∀ ω : Ω[V⁄k],
      KaehlerDifferential.map k k V F ω ∈ D.W)
    {s : ℕ} (rows : Fin s → ι)
    (hspan : Submodule.span (ResidueField V)
      (Set.range fun i : Fin s ↦
        KaehlerDifferential.D k (ResidueField V)
          (residue V (D.Q (rows i)))) = ⊤) :
    D.W ≤ coordinateFrame (KaehlerDifferential.D k F) D.t
      (fun i : Fin s ↦ D.Q (rows i)) := by
  classical
  let φ : Ω[V⁄k] →ₗ[V] Ω[F⁄k] := KaehlerDifferential.map k k V F
  let ψ : Ω[V⁄k] →ₗ[V] Ω[ResidueField V⁄k] :=
    KaehlerDifferential.map k k V (ResidueField V)
  let C0 : Submodule V (Ω[V⁄k]) :=
    Submodule.span V (Set.range fun i : Fin s ⊕ Unit ↦
      match i with
      | Sum.inl j => KaehlerDifferential.D k V (D.Q (rows j))
      | Sum.inr _ => KaehlerDifferential.D k V D.t)
  let C : Submodule V (Ω[F⁄k]) :=
    coordinateFrame (KaehlerDifferential.D k F) D.t
      (fun i : Fin s ↦ D.Q (rows i))
  let S : Submodule (ResidueField V) (Ω[ResidueField V⁄k]) :=
    Submodule.span (ResidueField V)
      (Set.range fun i : Fin s ↦
        KaehlerDifferential.D k (ResidueField V)
          (residue V (D.Q (rows i))))
  have hmapC0 : ∀ η ∈ C0, φ η ∈ C := by
    intro η hη
    induction hη using Submodule.span_induction with
    | mem z hz =>
        obtain ⟨i, rfl⟩ := hz
        cases i with
        | inl i =>
            change KaehlerDifferential.map k k V F
              (KaehlerDifferential.D k V (D.Q (rows i))) ∈ C
            rw [KaehlerDifferential.map_D]
            exact Submodule.mem_sup_right
              (Submodule.subset_span ⟨i, rfl⟩)
        | inr j =>
            cases j
            change KaehlerDifferential.map k k V F
              (KaehlerDifferential.D k V D.t) ∈ C
            rw [KaehlerDifferential.map_D]
            exact Submodule.mem_sup_left
              (Submodule.subset_span (Set.mem_singleton _))
    | zero => exact C.zero_mem
    | add _ _ _ _ hx hy =>
        rw [map_add]
        exact C.add_mem hx hy
    | smul a _ _ hx =>
        simpa only [LinearMap.map_smul, IsScalarTower.algebraMap_smul] using
          C.smul_mem a hx
  have hlift : ∀ z ∈ S, ∃ η ∈ C0, ψ η = z := by
    intro z hz
    induction hz using Submodule.span_induction with
    | mem z hz =>
        obtain ⟨i, rfl⟩ := hz
        refine ⟨KaehlerDifferential.D k V (D.Q (rows i)), ?_, ?_⟩
        · exact Submodule.subset_span ⟨Sum.inl i, rfl⟩
        · change KaehlerDifferential.map k k V (ResidueField V)
            (KaehlerDifferential.D k V (D.Q (rows i))) = _
          rw [KaehlerDifferential.map_D, ResidueField.algebraMap_eq]
    | zero => exact ⟨0, C0.zero_mem, map_zero _⟩
    | add _ _ _ _ hx hy =>
        obtain ⟨x, hxC, hxmap⟩ := hx
        obtain ⟨y, hyC, hymap⟩ := hy
        exact ⟨x + y, C0.add_mem hxC hyC, by rw [map_add, hxmap, hymap]⟩
    | smul a z₀ _ hx =>
        obtain ⟨x, hxC, hxmap⟩ := hx
        obtain ⟨a', ha'⟩ := IsLocalRing.residue_surjective a
        refine ⟨a' • x, C0.smul_mem a' hxC, ?_⟩
        rw [map_smul, hxmap]
        change (algebraMap V (ResidueField V) a') • z₀ = a • z₀
        rw [ResidueField.algebraMap_eq, ha']
  have hq : ∀ j : ι,
      KaehlerDifferential.D k F (algebraMap V F (D.Q j)) ∈
        C ⊔ Ideal.span {D.t} • D.W := by
    intro j
    have hres : ψ (KaehlerDifferential.D k V (D.Q j)) ∈ S := by
      change KaehlerDifferential.map k k V (ResidueField V)
        (KaehlerDifferential.D k V (D.Q j)) ∈ S
      rw [KaehlerDifferential.map_D, ResidueField.algebraMap_eq]
      change KaehlerDifferential.D k (ResidueField V)
        (residue V (D.Q j)) ∈
          Submodule.span (ResidueField V)
            (Set.range fun i : Fin s ↦
              KaehlerDifferential.D k (ResidueField V)
                (residue V (D.Q (rows i))))
      rw [hspan]
      trivial
    obtain ⟨η, hηC, hη⟩ := hlift _ hres
    have hker : KaehlerDifferential.D k V (D.Q j) - η ∈ LinearMap.ker ψ := by
      apply LinearMap.mem_ker.mpr
      simp only [map_sub]
      exact sub_eq_zero.mpr hη.symm
    rw [ker_kaehler_residue_map_eq D.t hmax] at hker
    obtain ⟨δ, hδ, μ, hμ, hsum⟩ := Submodule.mem_sup.mp hker
    have hdtC0 : KaehlerDifferential.D k V D.t ∈ C0 :=
      Submodule.subset_span ⟨Sum.inr (), rfl⟩
    have hδC0 : δ ∈ C0 := by
      have hle : Submodule.span V {KaehlerDifferential.D k V D.t} ≤ C0 := by
        rw [Submodule.span_le]
        intro z hz
        rw [Set.mem_singleton_iff] at hz
        simpa [hz] using hdtC0
      exact hle hδ
    have hδC : φ δ ∈ C := hmapC0 δ hδC0
    have hμW : φ μ ∈ Ideal.span {D.t} • D.W := by
      rw [hmax] at hμ
      refine Submodule.smul_induction_on hμ ?_ ?_
      · intro a ha ω hω
        rw [map_smul]
        exact Submodule.smul_mem_smul ha (himage ω)
      · intro x y hx hy
        rw [map_add]
        exact add_mem hx hy
    have hdecomp :
        KaehlerDifferential.D k F (algebraMap V F (D.Q j)) - φ η = φ δ + φ μ := by
      have := congrArg φ hsum
      simpa [φ, KaehlerDifferential.map_D] using this.symm
    have hηC' : φ η ∈ C := hmapC0 η hηC
    have heq : KaehlerDifferential.D k F (algebraMap V F (D.Q j)) =
        φ η + φ δ + φ μ := by
      calc
        _ = (_ - φ η) + φ η := by abel
        _ = (φ δ + φ μ) + φ η := by rw [hdecomp]
        _ = φ η + φ δ + φ μ := by abel
    have hsumC : φ η + φ δ + φ μ ∈ C ⊔ Ideal.span {D.t} • D.W := by
      have hηδ : φ η + φ δ ∈ C := C.add_mem hηC' hδC
      exact add_mem (Submodule.mem_sup_left hηδ)
        (Submodule.mem_sup_right hμW)
    rw [heq]
    exact hsumC
  have hall : coordinateFrame (KaehlerDifferential.D k F) D.t D.Q ≤
      C ⊔ Ideal.span {D.t} • D.W := by
    refine sup_le ?_ ?_
    · rw [Submodule.span_le, Set.singleton_subset_iff]
      have hdtC : KaehlerDifferential.D k F (algebraMap V F D.t) ∈ C :=
        Submodule.mem_sup_left (Submodule.subset_span (Set.mem_singleton _))
      exact Submodule.mem_sup_left hdtC
    · rw [Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      exact hq j
  have hvisible : D.W ≤ C ⊔ Ideal.span {D.t} • D.W := by
    exact D.visible.trans (sup_le hall le_sup_right)
  exact Submodule.le_of_le_smul_of_le_jacobson_bot D.W_fg
    D.parameterIdeal_le_jacobson hvisible

/-- At an actual retained DVR on a finitely-generated component, the generic
Kähler rank is at most one plus the residue-field Kähler rank.  The numerator
coordinates and the nonzero projective denominator generate the component
function field: their ratio family is assumed to be its explicit generic
coordinate family.  The denominator differential is supplied by its actual
factorization `t^a * u` in the visible frame. -/
theorem componentFractionField_kaehler_finrank_le_residue_add_one
    {k V F : Type u} [Field k] [CharZero k] [CommRing V] [IsLocalRing V]
    [Field F] [Algebra k V] [Algebra k F] [Algebra V F]
    [IsScalarTower k V F]
    {ι : Type x} [Fintype ι]
    (D : VisibleDivisorFrame (V := V) (KaehlerDifferential.D k F) ι)
    (hmax : maximalIdeal V = Ideal.span {D.t})
    (himage : ∀ ω : Ω[V⁄k],
      KaehlerDifferential.map k k V F ω ∈ D.W)
    (halg : Algebra.IsAlgebraic
      (IntermediateField.adjoin k
        (Set.range fun j : ι ↦ residue V (D.Q j)) :
          IntermediateField k (ResidueField V)) (ResidueField V))
    (x : ι → F)
    (hcoordinate : ∀ j, x j =
      algebraMap V F (D.Q j) / algebraMap V F D.Q₀)
    (hgen : IntermediateField.adjoin k (Set.range x) = ⊤) :
    Module.finrank F (Ω[F⁄k]) ≤
      Module.finrank (ResidueField V) (Ω[ResidueField V⁄k]) + 1 := by
  classical
  let κ := ResidueField V
  obtain ⟨rows, hspanRows⟩ :=
    exists_residue_kaehler_basis_rows_of_algebraic_generators
      (fun j : ι ↦ residue V (D.Q j)) (by simpa [κ] using halg)
  letI : FiniteDimensional κ (Ω[κ⁄k]) := by
    letI : FiniteDimensional κ
        (Submodule.span κ
          (Set.range fun i ↦ KaehlerDifferential.D k κ
            (residue V (D.Q (rows i))))) :=
      FiniteDimensional.span_of_finite κ (Set.finite_range _)
    letI : FiniteDimensional κ (⊤ : Submodule κ (Ω[κ⁄k])) :=
      (LinearEquiv.ofEq _ _ hspanRows).finiteDimensional
    exact Submodule.topEquiv.finiteDimensional
  have hW := visibleFrame_le_selectedCoordinateFrame
    D hmax himage rows (by simpa [κ] using hspanRows)
  let G : Fin (Module.finrank κ (Ω[κ⁄k])) ⊕ Unit → Ω[F⁄k] := fun i ↦
    match i with
    | Sum.inl j => KaehlerDifferential.D k F
        (algebraMap V F (D.Q (rows j)))
    | Sum.inr _ => KaehlerDifferential.D k F (algebraMap V F D.t)
  let T : Submodule F (Ω[F⁄k]) := Submodule.span F (Set.range G)
  have hC : coordinateFrame (KaehlerDifferential.D k F) D.t
      (fun j : Fin (Module.finrank κ (Ω[κ⁄k])) ↦ D.Q (rows j)) ≤
        T.restrictScalars V := by
    unfold coordinateFrame T
    refine sup_le ?_ ?_
    · rw [Submodule.span_le, Set.singleton_subset_iff]
      exact Submodule.subset_span ⟨Sum.inr (), rfl⟩
    · rw [Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      exact Submodule.subset_span ⟨Sum.inl j, rfl⟩
  have hW_T : D.W ≤ T.restrictScalars V := hW.trans hC
  have hq0 : KaehlerDifferential.D k F (algebraMap V F D.Q₀) ∈ D.W := by
    have h := himage (KaehlerDifferential.D k V D.Q₀)
    rw [KaehlerDifferential.map_D] at h
    exact h
  have hcoordinateD : ∀ j : ι,
      KaehlerDifferential.D k F (x j) ∈ T := by
    intro j
    rw [hcoordinate j, Derivation.leibniz_div]
    have hnum : KaehlerDifferential.D k F
        (algebraMap V F (D.Q j)) ∈ T :=
      hW_T (D.dQ_mem j)
    have hden : KaehlerDifferential.D k F
        (algebraMap V F D.Q₀) ∈ T := hW_T hq0
    exact T.smul_mem _ (T.sub_mem (T.smul_mem _ hnum)
      (T.smul_mem _ hden))
  have hcoordinateSpan :=
    Stafford38.Geometry.KaehlerSpanSeparableAdjoin.kaehler_span_of_intermediateField_adjoin_eq_top
      (k := k) (E := F) x hgen
  have hTtop : T = ⊤ := by
    apply top_unique
    rw [← hcoordinateSpan, Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    exact hcoordinateD j
  have hTfin : Module.finrank F T ≤
      Fintype.card (Fin (Module.finrank κ (Ω[κ⁄k])) ⊕ Unit) := by
    simpa [T, Set.finrank] using (finrank_range_le_card G)
  calc
    Module.finrank F (Ω[F⁄k]) = Module.finrank F (⊤ : Submodule F (Ω[F⁄k])) :=
      (finrank_top F (Ω[F⁄k])).symm
    _ = Module.finrank F T := by rw [hTtop]
    _ ≤ Fintype.card (Fin (Module.finrank κ (Ω[κ⁄k])) ⊕ Unit) := hTfin
    _ = Module.finrank κ (Ω[κ⁄k]) + 1 := by simp

/-- The scalar extension of a generic-point Kähler relation is still an
equation conormal at the same generic point after extending the coefficient
field.  This is the bridge needed to compare tangent dimensions over the
completed Laurent field with Kähler rank over the component function field. -/
theorem mapped_generic_kaehler_relation_mem_affineConormalSpace
    {k F E : Type u} [Field k] [Field F] [Field E]
    [Algebra k F] [Algebra k E] [Algebra F E] [IsScalarTower k F E]
    {m : ℕ} {I : Ideal (MvPolynomial (Fin m) k)} [I.IsPrime]
    [Algebra (MvPolynomial (Fin m) k ⧸ I) F]
    [IsScalarTower k (MvPolynomial (Fin m) k ⧸ I) F]
    [IsFractionRing (MvPolynomial (Fin m) k ⧸ I) F]
    (xi : Fin m → F)
    (hxi : ∑ i, xi i • KaehlerDifferential.D k F
      (GenericPointKaehlerConormal.genericPoint I F i) = 0) :
    AffineConormalSpan.coordinateCovector
        (fun i ↦ algebraMap F E (xi i)) ∈
      AffineConormalSpan.affineConormalSpace
        (fun i ↦ algebraMap F E
          (GenericPointKaehlerConormal.genericPoint I F i))
        (I.map (MvPolynomial.map (algebraMap k E))) := by
  classical
  let yF := GenericPointKaehlerConormal.genericPoint I F
  let yE : Fin m → E := fun i ↦ algebraMap F E (yF i)
  let IF : Ideal (MvPolynomial (Fin m) F) :=
    GenericPointKaehlerConormal.extendedIdeal I F
  let IE : Ideal (MvPolynomial (Fin m) E) :=
    I.map (MvPolynomial.map (algebraMap k E))
  let φ : MvPolynomial (Fin m) F →+* MvPolynomial (Fin m) E :=
    MvPolynomial.map (algebraMap F E)
  have hcomp : φ.comp (MvPolynomial.map (algebraMap k F)) =
      MvPolynomial.map (algebraMap k E) := by
    apply MvPolynomial.ringHom_ext
    · intro a
      change MvPolynomial.map (algebraMap F E)
          (MvPolynomial.map (algebraMap k F) (MvPolynomial.C a)) =
        MvPolynomial.map (algebraMap k E) (MvPolynomial.C a)
      rw [MvPolynomial.map_C, MvPolynomial.map_C]
      simpa only [MvPolynomial.map_C] using congrArg MvPolynomial.C
        (IsScalarTower.algebraMap_apply k F E a).symm
    · intro i
      change MvPolynomial.map (algebraMap F E)
          (MvPolynomial.map (algebraMap k F) (MvPolynomial.X i)) =
        MvPolynomial.map (algebraMap k E) (MvPolynomial.X i)
      simp
  have hmapIdeal : IF.map φ = IE := by
    dsimp [IF, IE, GenericPointKaehlerConormal.extendedIdeal, φ]
    rw [Ideal.map_map]
    rw [hcomp]
  have hdiff (f : MvPolynomial (Fin m) F) (i : Fin m) :
      Stafford38.Geometry.CoisotropicTranslation.differentialAt yE (φ f) i =
        algebraMap F E
          (Stafford38.Geometry.CoisotropicTranslation.differentialAt yF f i) := by
    simp only [Stafford38.Geometry.CoisotropicTranslation.differentialAt, φ,
      MvPolynomial.pderiv_map, MvPolynomial.eval_map]
    change MvPolynomial.eval₂ (algebraMap F E) (algebraMap F E ∘ yF)
        (MvPolynomial.pderiv i f) =
      algebraMap F E (MvPolynomial.eval yF (MvPolynomial.pderiv i f))
    exact (MvPolynomial.eval₂_comp (algebraMap F E) yF
      (MvPolynomial.pderiv i f)).symm
  have hFconormal :=
    GenericPointKaehlerConormal.coordinateCovector_mem_affineConormalSpace_of_kaehler_sum_eq_zero
      xi (by simpa [yF] using hxi)
  obtain ⟨c, hc⟩ :=
    AffineConormalSpan.coordinate_mem_affineConormalSpace_exists_finsupp
      yF xi IF hFconormal
  have hcomponent (i : Fin m) : algebraMap F E (xi i) =
      ∑ f ∈ c.support, algebraMap F E (c f) *
        Stafford38.Geometry.CoisotropicTranslation.differentialAt yE (φ f.1) i := by
    rw [hc i, map_sum]
    apply Finset.sum_congr rfl
    intro f hf
    rw [map_mul, hdiff]
  let η : Fin m → E := fun i ↦
    ∑ f ∈ c.support, algebraMap F E (c f) *
      Stafford38.Geometry.CoisotropicTranslation.differentialAt yE (φ f.1) i
  have hη : (fun i ↦ algebraMap F E (xi i)) = η := by
    funext i
    exact hcomponent i
  have hsumCovector :
      AffineConormalSpan.coordinateCovector η =
        ∑ f ∈ c.support, algebraMap F E (c f) •
          AffineConormalSpan.differentialCovector yE (φ f.1) := by
    apply LinearMap.ext
    intro v
    simp only [AffineConormalSpan.coordinateCovector_apply,
      LinearMap.sum_apply, LinearMap.smul_apply,
      AffineConormalSpan.differentialCovector_apply, smul_eq_mul]
    change (∑ i, η i * v i) =
      ∑ f ∈ c.support, algebraMap F E (c f) *
        (∑ i, Stafford38.Geometry.CoisotropicTranslation.differentialAt
          yE (φ f.1) i * v i)
    calc
      (∑ i, η i * v i) =
          ∑ i, ∑ f ∈ c.support,
            algebraMap F E (c f) *
              Stafford38.Geometry.CoisotropicTranslation.differentialAt
                yE (φ f.1) i * v i := by
        apply Finset.sum_congr rfl
        intro i hi
        rw [Finset.sum_mul]
      _ = ∑ f ∈ c.support, ∑ i,
            algebraMap F E (c f) *
              Stafford38.Geometry.CoisotropicTranslation.differentialAt
                yE (φ f.1) i * v i := by
        rw [Finset.sum_comm]
      _ = ∑ f ∈ c.support, algebraMap F E (c f) *
            (∑ i, Stafford38.Geometry.CoisotropicTranslation.differentialAt
              yE (φ f.1) i * v i) := by
        apply Finset.sum_congr rfl
        intro f hf
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro i hi
        ring
  have hcovector :
      AffineConormalSpan.coordinateCovector
          (fun i ↦ algebraMap F E (xi i)) =
        ∑ f ∈ c.support, algebraMap F E (c f) •
          AffineConormalSpan.differentialCovector yE (φ f.1) := by
    rw [hη, hsumCovector]
  rw [AffineConormalSpan.affineConormalSpace_eq_equationCovectorSpan,
    AffineConormalSpan.equationCovectorSpan]
  rw [hcovector]
  refine Submodule.sum_mem _ fun f hf ↦ ?_
  apply Submodule.smul_mem _
  change AffineConormalSpan.differentialCovector yE (φ f.1) ∈
    Submodule.span E (Set.range fun g : IE ↦
      AffineConormalSpan.differentialCovector yE g.1)
  apply Submodule.subset_span
  refine ⟨⟨φ f.1, ?_⟩, rfl⟩
  rw [← hmapIdeal]
  exact Ideal.mem_map_of_mem φ f.2

/-- The embedded tangent dimension at a generic component point cannot grow
after extending the coefficient field: it is bounded by the Kähler rank of
the component function field.  The proof transfers a basis of the generic
Kähler-relation space into the equation conormal, then takes annihilators. -/
theorem generic_tangent_finrank_le_component_kaehler_finrank
    {k F E : Type u} [Field k] [Field F] [Field E]
    [Algebra k F] [Algebra k E] [Algebra F E] [IsScalarTower k F E]
    {m : ℕ} {I : Ideal (MvPolynomial (Fin m) k)} [I.IsPrime]
    [Algebra (MvPolynomial (Fin m) k ⧸ I) F]
    [IsScalarTower k (MvPolynomial (Fin m) k ⧸ I) F]
    [IsFractionRing (MvPolynomial (Fin m) k ⧸ I) F]
    (hgen : IntermediateField.adjoin k
      (Set.range (GenericPointKaehlerConormal.genericPoint I F)) = ⊤) :
    Module.finrank E
        (AffineConormalSpan.zariskiTangentSpace
          (fun i ↦ algebraMap F E
            (GenericPointKaehlerConormal.genericPoint I F i))
          (I.map (MvPolynomial.map (algebraMap k E)))) ≤
      Module.finrank F (Ω[F⁄k]) := by
  classical
  let yF := GenericPointKaehlerConormal.genericPoint I F
  let yE : Fin m → E := fun i ↦ algebraMap F E (yF i)
  let IE : Ideal (MvPolynomial (Fin m) E) :=
    I.map (MvPolynomial.map (algebraMap k E))
  have hspan : Submodule.span F
      (Set.range fun i ↦ KaehlerDifferential.D k F (yF i)) = ⊤ :=
    Stafford38.Geometry.KaehlerSpanSeparableAdjoin.kaehler_span_of_intermediateField_adjoin_eq_top
      (k := k) (E := F) yF hgen
  letI : FiniteDimensional F (Ω[F⁄k]) := by
    letI : FiniteDimensional F
        (Submodule.span F
          (Set.range fun i ↦ KaehlerDifferential.D k F (yF i))) :=
      FiniteDimensional.span_of_finite F (Set.finite_range _)
    letI : FiniteDimensional F (⊤ : Submodule F (Ω[F⁄k])) :=
      (LinearEquiv.ofEq _ _ hspan).finiteDimensional
    exact Submodule.topEquiv.finiteDimensional
  let δ : (Fin m → F) →ₗ[F] Ω[F⁄k] :=
    { toFun := fun v ↦ ∑ i, v i • KaehlerDifferential.D k F (yF i)
      map_add' := by
        intro v w
        simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
      map_smul' := by
        intro a v
        simp [Pi.smul_apply, smul_eq_mul, Finset.smul_sum, mul_smul,
          mul_assoc] }
  have hsurj : LinearMap.range δ = ⊤ := by
    apply top_unique
    rw [← hspan, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    refine ⟨Pi.single i 1, ?_⟩
    simp [δ]
  let b := Module.finBasis F (LinearMap.ker δ)
  let z : Fin (Module.finrank F (LinearMap.ker δ)) → Fin m → F :=
    fun j ↦ (LinearMap.ker δ).subtype (b j)
  have hzker (j : Fin (Module.finrank F (LinearMap.ker δ))) : δ (z j) = 0 :=
    (b j).property
  have hliF : LinearIndependent F z := by
    apply b.linearIndependent.map' (LinearMap.ker δ).subtype
    rw [LinearMap.ker_eq_bot]
    exact (LinearMap.ker δ).subtype_injective
  have hliE : LinearIndependent E
      (fun j i ↦ algebraMap F E (z j i)) :=
    (linearIndependent_algebraMap_comp_iff (R := F) (S := E)
      (ι' := Fin m)).2 hliF
  let cv : (Fin m → E) →ₗ[E]
      Module.Dual E (AffineConormalSpan.AffineTangentVector E m) :=
    { toFun := AffineConormalSpan.coordinateCovector
      map_add' := by
        intro v w
        apply LinearMap.ext
        intro z
        change (∑ i, (v i + w i) * z i) =
          (∑ i, v i * z i) + ∑ i, w i * z i
        calc
          _ = ∑ i, (v i * z i + w i * z i) := by
            apply Finset.sum_congr rfl
            intro i hi
            ring
          _ = _ := Finset.sum_add_distrib
      map_smul' := by
        intro a v
        apply LinearMap.ext
        intro z
        change (∑ i, (a * v i) * z i) =
          a * (∑ i, v i * z i)
        calc
          _ = ∑ i, a * (v i * z i) := by
            apply Finset.sum_congr rfl
            intro i hi
            ring
          _ = a * (∑ i, v i * z i) :=
            (Finset.mul_sum Finset.univ (fun i ↦ v i * z i) a).symm }
  have hcvker : LinearMap.ker cv = ⊥ := by
    apply LinearMap.ker_eq_bot.mpr
    intro v w hvw
    exact AffineConormalSpan.coordinateCovector_injective hvw
  have hliCov : LinearIndependent E
      (fun j ↦ AffineConormalSpan.coordinateCovector
        (fun i ↦ algebraMap F E (z j i))) :=
    hliE.map' cv hcvker
  let R : Submodule E (Module.Dual E
      (AffineConormalSpan.AffineTangentVector E m)) :=
    Submodule.span E (Set.range fun j ↦ cv (fun i ↦ algebraMap F E (z j i)))
  have hRle : R ≤ AffineConormalSpan.equationCovectorSpan yE IE := by
    change Submodule.span E
        (Set.range fun j ↦ cv (fun i ↦ algebraMap F E (z j i))) ≤ _
    rw [Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    have hrel : ∑ i, z j i • KaehlerDifferential.D k F (yF i) = 0 := by
      simpa [δ] using hzker j
    simpa [cv, yF, yE, IE,
      AffineConormalSpan.affineConormalSpace_eq_equationCovectorSpan] using
      mapped_generic_kaehler_relation_mem_affineConormalSpace
        (I := I) (E := E) (xi := z j) hrel
  have htan : AffineConormalSpan.zariskiTangentSpace yE IE ≤
      R.dualCoannihilator := by
    change (AffineConormalSpan.equationCovectorSpan yE IE).dualCoannihilator ≤
      R.dualCoannihilator
    intro v hv
    rw [Submodule.mem_dualCoannihilator] at hv ⊢
    intro c hc
    exact hv c (hRle hc)
  have hRdim : Module.finrank E R =
      Module.finrank F (LinearMap.ker δ) := by
    change Module.finrank E
        (Submodule.span E (Set.range fun j ↦
          AffineConormalSpan.coordinateCovector
            (fun i ↦ algebraMap F E (z j i)))) = _
    rw [finrank_span_eq_card hliCov]
    simp
  have hconormalRank :=
    Subspace.finrank_add_finrank_dualCoannihilator_eq R
  have hkerRank := LinearMap.finrank_range_add_finrank_ker δ
  rw [hsurj] at hkerRank
  have hdomainRank : Module.finrank F (Fin m → F) = m := by simp
  have hkerEquation : Module.finrank F (LinearMap.ker δ) +
      Module.finrank F (Ω[F⁄k]) = m := by
    have hkerEquation' : Module.finrank F (Ω[F⁄k]) +
        Module.finrank F (LinearMap.ker δ) = m := by
      simpa only [finrank_top, hdomainRank] using hkerRank
    omega
  have hambientRank : Module.finrank E
      (AffineConormalSpan.AffineTangentVector E m) = m := by simp
  have hconormalEquation : Module.finrank E R +
      Module.finrank E R.dualCoannihilator = m := by
    calc
      _ = Module.finrank E
          (AffineConormalSpan.AffineTangentVector E m) := hconormalRank
      _ = m := hambientRank
  have hdualRank : Module.finrank F (LinearMap.ker δ) +
      Module.finrank E R.dualCoannihilator = m := by
    calc
      _ = Module.finrank E R + Module.finrank E R.dualCoannihilator := by
        rw [hRdim]
      _ = m := hconormalEquation
  have htanRank : Module.finrank E
      (AffineConormalSpan.zariskiTangentSpace yE IE) ≤
        Module.finrank E R.dualCoannihilator := Submodule.finrank_mono htan
  have hdualLe : Module.finrank E R.dualCoannihilator ≤
      Module.finrank F (Ω[F⁄k]) := by omega
  have hresult : Module.finrank E
      (AffineConormalSpan.zariskiTangentSpace yE IE) ≤
        Module.finrank F (Ω[F⁄k]) := htanRank.trans hdualLe
  simpa [yE, IE] using hresult

end

end Stafford38.Geometry.PaperGenericTangentRank
