module
public import Mathlib.Data.Fin.Tuple.Basic
public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.Algebra.MvPolynomial.Monad
public import Mathlib.Algebra.MvPolynomial.Rename
public import Mathlib.RingTheory.MvPolynomial.Homogeneous

@[expose] public section

/-!
# Shared coordinates for projective affine charts

The point insertion and polynomial dehomogenization maps are owned here so
that fixed-chart algebra and arbitrary-chart geometry use one construction.
The complement equivalence is an explicit parameter: this preserves the
existing arbitrary-chart ordering while allowing the zeroth chart to use the
usual `Fin.succ` ordering.
-/

namespace Stafford38.Geometry.ProjectiveChartCoordinates

noncomputable section

universe u

variable {K : Type u} [Field K]

/-- Indices in the projective coordinate set other than the selected chart. -/
abbrev ChartAffineIndex (ι : Type*) (chart : ι) := {i : ι // i ≠ chart}

/-- Insert a normalized projective chart coordinate and fill the complement
using the explicitly chosen affine-coordinate ordering. -/
def insertProjectiveChart {m : ℕ} (chart : Fin (m + 1))
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) chart)
    (y : Fin m → K) : Fin (m + 1) → K :=
  fun a ↦ if h : a = chart then 1 else y (e.symm ⟨a, h⟩)

/-- Differential of a normalized projective coordinate `q_i / q_chart` in
the projective direction `w`.  This single formula owns both the arbitrary
chart and fixed zeroth-chart tangent columns. -/
def dehomogenizedTangentColumn {ι : Type*} (chart : ι)
    (q w : ι → K) : ChartAffineIndex ι chart → K :=
  fun i ↦ (w i.1 * q chart - q i.1 * w chart) / q chart ^ 2

@[simp] theorem dehomogenizedTangentColumn_apply {ι : Type*} (chart : ι)
    (q w : ι → K) (i : ChartAffineIndex ι chart) :
    dehomogenizedTangentColumn chart q w i =
      (w i.1 * q chart - q i.1 * w chart) / q chart ^ 2 := rfl

/-- Dehomogenize a projective polynomial in a selected chart, using the same
explicit ordering of complementary coordinates as `insertProjectiveChart`. -/
def dehomogenizeProjectiveChart {m : ℕ} (chart : Fin (m + 1))
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) chart) :
    MvPolynomial (Fin (m + 1)) K →ₐ[K] MvPolynomial (Fin m) K :=
  MvPolynomial.aeval fun a ↦
    if h : a = chart then 1 else MvPolynomial.X (e.symm ⟨a, h⟩)

/-- Evaluation after dehomogenization is evaluation at the inserted chart
point. -/
theorem eval_dehomogenizeProjectiveChart {m : ℕ} (chart : Fin (m + 1))
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) chart)
    (p : MvPolynomial (Fin (m + 1)) K) (y : Fin m → K) :
    MvPolynomial.eval y (dehomogenizeProjectiveChart chart e p) =
      MvPolynomial.eval (insertProjectiveChart chart e y) p := by
  rw [show dehomogenizeProjectiveChart chart e p = MvPolynomial.bind₁
      (fun a ↦ if h : a = chart then 1 else MvPolynomial.X (e.symm ⟨a, h⟩)) p by rfl]
  rw [MvPolynomial.hom_bind₁]
  change MvPolynomial.eval₂ _ _ p = MvPolynomial.eval₂ _ _ p
  have hcoeff : (MvPolynomial.eval y).comp MvPolynomial.C = RingHom.id K := by
    ext a
    simp
  rw [hcoeff]
  apply MvPolynomial.eval₂_congr
  intro a
  by_cases h : a = chart
  · subst a
    simp [insertProjectiveChart]
  · simp [insertProjectiveChart, h]

/-- The affine ideal generated by a family of equations after dehomogenizing
in one chosen projective chart.  This is the shared owner for fixed-chart and
arbitrary-chart equation ideals. -/
def dehomogenizedEquationIdeal {m : ℕ} {ι : Type*}
    (chart : Fin (m + 1))
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) chart)
    (equations : ι → MvPolynomial (Fin (m + 1)) K) :
    Ideal (MvPolynomial (Fin m) K) :=
  Ideal.span (Set.range fun i ↦ dehomogenizeProjectiveChart chart e (equations i))

/-- Every member of the chart-dehomogenized equation ideal vanishes at an
affine point whenever all inserted projective generators vanish there. -/
theorem eval_eq_zero_of_mem_dehomogenizedEquationIdeal
    {m : ℕ} {ι : Type*} (chart : Fin (m + 1))
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) chart)
    (equations : ι → MvPolynomial (Fin (m + 1)) K)
    (y : Fin m → K)
    (hvanish : ∀ i,
      MvPolynomial.eval (insertProjectiveChart chart e y) (equations i) = 0)
    (f : MvPolynomial (Fin m) K)
    (hf : f ∈ dehomogenizedEquationIdeal chart e equations) :
    MvPolynomial.eval y f = 0 := by
  have hle : dehomogenizedEquationIdeal chart e equations ≤
      RingHom.ker (MvPolynomial.eval y) := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    change MvPolynomial.eval y (dehomogenizeProjectiveChart chart e (equations i)) = 0
    rw [eval_dehomogenizeProjectiveChart]
    exact hvanish i
  exact hle hf

/-- The canonical complementary ordering for the zeroth chart. -/
def zerothChartEquiv {m : ℕ} :
    Fin m ≃ ChartAffineIndex (Fin (m + 1)) (0 : Fin (m + 1)) :=
  Equiv.ofBijective
    (fun i ↦ (⟨i.succ, Fin.succ_ne_zero i⟩ :
      ChartAffineIndex (Fin (m + 1)) (0 : Fin (m + 1))))
    ⟨by
      intro i j h
      exact (Fin.succ_injective _ ) (congrArg Subtype.val h),
     by
      intro ⟨j, hj⟩
      rcases Fin.eq_zero_or_eq_succ j with hzero | ⟨i, hi⟩
      · exact (hj hzero).elim
      · refine ⟨i, ?_⟩
        apply Subtype.ext
        exact hi.symm⟩

@[simp] theorem zerothChartEquiv_apply {m : ℕ} (i : Fin m) :
    zerothChartEquiv (m := m) i = ⟨i.succ, Fin.succ_ne_zero i⟩ := rfl

@[simp] theorem zerothChartEquiv_symm_apply_succ {m : ℕ} (i : Fin m) :
    (zerothChartEquiv (m := m)).symm ⟨i.succ, Fin.succ_ne_zero i⟩ = i :=
  Equiv.apply_symm_apply _ i

/-- The zeroth-chart specialization is exactly the standard tuple
`(1,y₀,…,y_{m-1})`. -/
@[simp] theorem insertProjectiveChart_zero {m : ℕ} (y : Fin m → K) :
    insertProjectiveChart (0 : Fin (m + 1)) (zerothChartEquiv (m := m)) y =
      Fin.cases 1 y := by
  funext a
  refine Fin.cases ?_ (fun i ↦ ?_) a
  · simp [insertProjectiveChart]
  · simp [insertProjectiveChart]

/-- Changing the chosen zeroth-chart complement ordering only reindexes the
affine tuple; the inserted projective point is unchanged. -/
theorem insertProjectiveChart_zero_transport {m : ℕ}
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) (0 : Fin (m + 1)))
    (y : Fin m → K) :
    insertProjectiveChart (0 : Fin (m + 1)) e y =
      insertProjectiveChart (0 : Fin (m + 1)) (zerothChartEquiv (m := m))
        (fun i ↦ y ((zerothChartEquiv (m := m)).trans e.symm i)) := by
  funext a
  rcases Fin.eq_zero_or_eq_succ a with rfl | ⟨i, rfl⟩
  · simp [insertProjectiveChart]
  · simp [insertProjectiveChart]

/-- The zeroth-chart polynomial map is exactly substitution
`X₀ ↦ 1`, `X_(i+1) ↦ X_i`. -/
@[simp] theorem dehomogenizeProjectiveChart_zero {m : ℕ}
    : dehomogenizeProjectiveChart (0 : Fin (m + 1)) (zerothChartEquiv (m := m)) =
      MvPolynomial.aeval (R := K) (S₁ := MvPolynomial (Fin m) K)
        (Fin.cases (1 : MvPolynomial (Fin m) K) fun i ↦ MvPolynomial.X i) := by
  apply MvPolynomial.algHom_ext
  intro a
  refine Fin.cases ?_ (fun i ↦ ?_) a
  · simp [dehomogenizeProjectiveChart]
  · simp [dehomogenizeProjectiveChart]

/-- Changing the chosen zeroth-chart complement ordering changes the
dehomogenization map only by the corresponding affine-variable renaming. -/
theorem dehomogenizeProjectiveChart_zero_transport {m : ℕ}
    (e : Fin m ≃ ChartAffineIndex (Fin (m + 1)) (0 : Fin (m + 1))) :
    (MvPolynomial.renameEquiv K
        ((zerothChartEquiv (m := m)).trans e.symm)).toAlgHom.comp
        (dehomogenizeProjectiveChart (0 : Fin (m + 1))
          (zerothChartEquiv (m := m))) =
      dehomogenizeProjectiveChart (0 : Fin (m + 1)) e := by
  apply MvPolynomial.algHom_ext
  intro a
  rcases Fin.eq_zero_or_eq_succ a with rfl | ⟨i, rfl⟩
  · simp [dehomogenizeProjectiveChart]
  · simp [dehomogenizeProjectiveChart]

#print axioms eval_dehomogenizeProjectiveChart
#print axioms insertProjectiveChart_zero
#print axioms insertProjectiveChart_zero_transport
#print axioms dehomogenizeProjectiveChart_zero
#print axioms dehomogenizeProjectiveChart_zero_transport

end
end Stafford38.Geometry.ProjectiveChartCoordinates
