import Stafford38.Geometry.JacobianConormalComparison
import Stafford38.Geometry.RetractionSpecialization

/-!
# Dehomogenizing projective conormal data

This file isolates the field-level calculation that turns a projective point,
projective tangent columns, and a projective annihilating row into affine
conormal data in the chart where the zeroth coordinate is nonzero.

No projective closure, normalization, formal chart, tangent-space comparison,
Laurent specialization, closure theorem, or coisotropy statement is constructed
here.  The tangent-space equality and the base equations are explicit inputs.
-/

namespace Stafford38.Geometry.ProjectiveConormalDehomogenization

open Stafford38.Geometry.AffineConormalClosure
open Stafford38.Geometry.AffineConormalSpan
open Stafford38.Geometry.JacobianConormalComparison
open Stafford38.GeometryRetractionSpecialization

noncomputable section

variable {K : Type*} [Field K] {n : ℕ}

/-- The affine point represented by `q` in the chart `q 0 ≠ 0`. -/
def dehomogenizedPoint (q : Fin (n + 1) → K) : Fin n → K :=
  fun i ↦ q i.succ / q 0

/-- The derivative of the affine chart coordinate `q_(i+1) / q_0` in the
projective tangent direction `w`. -/
def dehomogenizedTangentColumn
    (q w : Fin (n + 1) → K) : Fin n → K :=
  fun i ↦ (w i.succ * q 0 - q i.succ * w 0) / q 0 ^ 2

/-- The affine tangent subspace generated by dehomogenizing the supplied
projective tangent columns. -/
def dehomogenizedTangentSpan {κ : Type*}
    (q : Fin (n + 1) → K) (B : Matrix (Fin (n + 1)) κ K) :
    Submodule K (AffineTangentVector K n) :=
  Submodule.span K
    (Set.range fun j ↦ dehomogenizedTangentColumn q (fun i ↦ B i j))

/-- A projective row annihilating both the point and every supplied
projective tangent column gives an affine coordinate covector annihilating
the dehomogenized tangent span. -/
theorem coordinateCovector_mem_dehomogenizedTangentSpan_dualAnnihilator
    {κ : Type*}
    (q ell : Fin (n + 1) → K) (B : Matrix (Fin (n + 1)) κ K)
    (hq0 : q 0 ≠ 0)
    (hq : ∑ i, ell i * q i = 0)
    (hB : rowMul ell B = 0) :
    coordinateCovector (fun i ↦ ell i.succ) ∈
      (dehomogenizedTangentSpan q B).dualAnnihilator := by
  rw [Submodule.mem_dualAnnihilator]
  intro v hv
  rw [dehomogenizedTangentSpan] at hv
  induction hv using Submodule.span_induction with
  | mem v hv =>
    rcases hv with ⟨j, rfl⟩
    have hqTail : ∑ i : Fin n, ell i.succ * q i.succ = -(ell 0 * q 0) := by
      rw [Fin.sum_univ_succ] at hq
      linear_combination hq
    have hBTail : ∑ i : Fin n, ell i.succ * B i.succ j = -(ell 0 * B 0 j) := by
      have hj := congrFun hB j
      simp only [Pi.zero_apply, rowMul, Fin.sum_univ_succ] at hj
      linear_combination hj
    simp only [coordinateCovector_apply, dehomogenizedTangentColumn]
    simp_rw [← mul_div_assoc]
    rw [← Finset.sum_div]
    field_simp [hq0]
    calc
      (∑ i : Fin n, ell i.succ *
          (B i.succ j * q 0 - q i.succ * B 0 j)) =
          (∑ i : Fin n, (ell i.succ * B i.succ j) * q 0) -
            ∑ i : Fin n, (ell i.succ * q i.succ) * B 0 j := by
              rw [← Finset.sum_sub_distrib]
              apply Finset.sum_congr rfl
              intro i hi
              ring
      _ = (∑ i : Fin n, ell i.succ * B i.succ j) * q 0 -
            (∑ i : Fin n, ell i.succ * q i.succ) * B 0 j := by
              rw [Finset.sum_mul, Finset.sum_mul]
      _ = q 0 ^ 2 * 0 := by rw [hBTail, hqTail]; ring
  | zero => exact map_zero (coordinateCovector (fun i ↦ ell i.succ))
  | add x y _ _ hx hy =>
      simpa [hx, hy] using map_add (coordinateCovector (fun i ↦ ell i.succ)) x y
  | smul a x _ hx =>
      simp [map_smul, hx]

/-- If the dehomogenized column span is the embedded Zariski tangent space,
then the tail of the projective annihilating row is an affine conormal
covector. -/
theorem coordinateCovector_mem_affineConormalSpace_of_projective_row
    {κ : Type*}
    (I : Ideal (MvPolynomial (Fin n) K))
    (q ell : Fin (n + 1) → K) (B : Matrix (Fin (n + 1)) κ K)
    (hq0 : q 0 ≠ 0)
    (hq : ∑ i, ell i * q i = 0)
    (hB : rowMul ell B = 0)
    (htangent :
      dehomogenizedTangentSpan q B = zariskiTangentSpace (dehomogenizedPoint q) I) :
    coordinateCovector (fun i ↦ ell i.succ) ∈
      affineConormalSpace (dehomogenizedPoint q) I := by
  rw [affineConormalSpace, ← htangent]
  exact coordinateCovector_mem_dehomogenizedTangentSpan_dualAnnihilator
    q ell B hq0 hq hB

/-- Projective point and tangent data produce a point of the equation-defined
affine conormal locus once base-equation membership and the exact Zariski
tangent-space identification are supplied. -/
theorem phasePoint_mem_equationConormalLocus_of_projective_row
    {κ : Type*}
    (I : Ideal (MvPolynomial (Fin n) K))
    (q ell : Fin (n + 1) → K) (B : Matrix (Fin (n + 1)) κ K)
    (hq0 : q 0 ≠ 0)
    (hq : ∑ i, ell i * q i = 0)
    (hB : rowMul ell B = 0)
    (hbase : ∀ f ∈ I, MvPolynomial.eval (dehomogenizedPoint q) f = 0)
    (htangent :
      dehomogenizedTangentSpan q B = zariskiTangentSpace (dehomogenizedPoint q) I) :
    Sum.elim (dehomogenizedPoint q) (fun i ↦ ell i.succ) ∈
      equationConormalLocus I := by
  refine ⟨?_, ?_⟩
  · simpa using hbase
  · simpa using coordinateCovector_mem_affineConormalSpace_of_projective_row
      I q ell B hq0 hq hB htangent

/-- Jacobian-facing form of the same bridge.  The supplied equations belong
to `I`, and the dehomogenized column span is identified exactly with their
Jacobian tangent kernel. -/
theorem phasePoint_mem_equationConormalLocus_of_projective_row_jacobian
    {κ ι : Type*}
    (I : Ideal (MvPolynomial (Fin n) K))
    (equations : ι → MvPolynomial (Fin n) K)
    (hequations : ∀ i, equations i ∈ I)
    (q ell : Fin (n + 1) → K) (B : Matrix (Fin (n + 1)) κ K)
    (hq0 : q 0 ≠ 0)
    (hq : ∑ i, ell i * q i = 0)
    (hB : rowMul ell B = 0)
    (hbase : ∀ f ∈ I, MvPolynomial.eval (dehomogenizedPoint q) f = 0)
    (htangent :
      dehomogenizedTangentSpan q B =
        jacobianTangentSpace (dehomogenizedPoint q) equations) :
    Sum.elim (dehomogenizedPoint q) (fun i ↦ ell i.succ) ∈
      equationConormalLocus I := by
  refine ⟨?_, ?_⟩
  · simpa using hbase
  · apply jacobianConormalSpace_le_affineConormalSpace
      (dehomogenizedPoint q) I equations hequations
    change coordinateCovector (fun i ↦ ell i.succ) ∈
      (jacobianTangentSpace (dehomogenizedPoint q) equations).dualAnnihilator
    rw [← htangent]
    exact coordinateCovector_mem_dehomogenizedTangentSpan_dualAnnihilator
      q ell B hq0 hq hB

#print axioms coordinateCovector_mem_dehomogenizedTangentSpan_dualAnnihilator
#print axioms coordinateCovector_mem_affineConormalSpace_of_projective_row
#print axioms phasePoint_mem_equationConormalLocus_of_projective_row
#print axioms phasePoint_mem_equationConormalLocus_of_projective_row_jacobian

end

end Stafford38.Geometry.ProjectiveConormalDehomogenization
