import Stafford38.Geometry.FormalDivisorLaurentConormal
import Mathlib.RingTheory.MvPolynomial.Homogeneous

/-!
# Projective equations on a formal affine chart

This file removes the base-equation part of the formal-divisor producer.
A homogeneous projective equation which vanishes at a projective point also
vanishes after dehomogenizing in any nonzero chart.  The result is extended
from a family of homogeneous equations to the affine ideal generated by their
dehomogenizations, and then connected directly to the formal Laurent conormal
handoff.

No projective closure, normalization, divisor, formal parameter, smoothness,
or tangent-space equality is constructed here.  Those geometric existence
statements remain outside this algebraic chart calculation.
-/

namespace Stafford38.Geometry.ProjectiveEquationFormalChart

open MvPolynomial
open Stafford38.Geometry.AffineConormalClosure
open Stafford38.Geometry.AffineConormalSpan
open Stafford38.Geometry.FormalDivisorLaurentConormal
open Stafford38.Geometry.ProjectiveConormalDehomogenization
open Stafford38.GeometryFormalDivisorTangent
open Stafford38.GeometryRetractionSpecialization

noncomputable section

variable {K : Type*} [Field K] {n : ℕ}

/-- Normalize every projective coordinate by the chosen chart denominator. -/
def normalizedProjectivePoint {m : ℕ} (q : Fin m → K) (q₀ : K) : Fin m → K :=
  fun i ↦ q i / q₀

/-- Substitute `X₀ = 1` and `X_(i+1) = X_i` in a projective polynomial. -/
def projectiveDehomogenize :
    MvPolynomial (Fin (n + 1)) K →ₐ[K] MvPolynomial (Fin n) K :=
  MvPolynomial.aeval (Fin.cases 1 fun i ↦ MvPolynomial.X i)

/-- Evaluation after projective dehomogenization is evaluation at the
projective chart point `(1,y)`. -/
theorem eval_projectiveDehomogenize
    (p : MvPolynomial (Fin (n + 1)) K) (y : Fin n → K) :
    MvPolynomial.eval y (projectiveDehomogenize p) =
      MvPolynomial.eval (Fin.cases 1 y) p := by
  rw [show projectiveDehomogenize p =
      MvPolynomial.bind₁ (Fin.cases 1 fun i ↦ MvPolynomial.X i) p by
        rfl]
  rw [MvPolynomial.hom_bind₁]
  change MvPolynomial.eval₂ _ _ p = MvPolynomial.eval₂ _ _ p
  have hf : (MvPolynomial.eval y).comp MvPolynomial.C = RingHom.id K := by
    ext a
    simp
  rw [hf]
  apply MvPolynomial.eval₂_congr
  intro i
  refine Fin.cases ?_ (fun j ↦ ?_) i <;> simp

/-- Scaling all coordinates of a homogeneous polynomial scales its value by
the corresponding power.  This explicit finite-product form is the algebraic
valuation identity used in the chart argument. -/
theorem eval_eq_pow_mul_eval_normalizedProjectivePoint
    {m : ℕ} (p : MvPolynomial (Fin m) K) (d : ℕ)
    (hp : p.IsHomogeneous d) (q : Fin m → K) (q₀ : K) (hq₀ : q₀ ≠ 0) :
    MvPolynomial.eval q p =
      q₀ ^ d * MvPolynomial.eval (normalizedProjectivePoint q q₀) p := by
  change p.eval₂ (RingHom.id K) q =
    q₀ ^ d * p.eval₂ (RingHom.id K) (normalizedProjectivePoint q q₀)
  rw [MvPolynomial.eval₂_eq', MvPolynomial.eval₂_eq']
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro s hs
  have hdegree : ∑ i, s i = d := by
    have hweight := hp (MvPolynomial.mem_support_iff.mp hs)
    rw [Finsupp.weight_apply,
      Finsupp.sum_fintype s
        (fun i c ↦ c • (1 : Fin m → ℕ) i) (by simp)] at hweight
    simpa only [Pi.one_apply, smul_eq_mul, mul_one] using hweight
  have hcoordinate : ∀ i : Fin m,
      q₀ * normalizedProjectivePoint q q₀ i = q i := by
    intro i
    exact mul_div_cancel₀ (q i) hq₀
  have hproduct : (∏ i : Fin m, q i ^ s i) =
      q₀ ^ d * ∏ i : Fin m, normalizedProjectivePoint q q₀ i ^ s i := by
    calc
      (∏ i : Fin m, q i ^ s i) =
          ∏ i : Fin m, (q₀ * normalizedProjectivePoint q q₀ i) ^ s i := by
            simp_rw [hcoordinate]
      _ = (∏ i : Fin m, q₀ ^ s i) *
          ∏ i : Fin m, normalizedProjectivePoint q q₀ i ^ s i := by
            simp_rw [mul_pow]
            rw [Finset.prod_mul_distrib]
      _ = q₀ ^ d *
          ∏ i : Fin m, normalizedProjectivePoint q q₀ i ^ s i := by
            rw [Finset.prod_pow_eq_pow_sum, hdegree]
  rw [hproduct]
  ring

/-- The normalized projective point is exactly `(1, dehomogenizedPoint q)`
in the chart with denominator `q 0`. -/
theorem normalizedProjectivePoint_eq_chartPoint
    (q : Fin (n + 1) → K) (hq₀ : q 0 ≠ 0) :
    normalizedProjectivePoint q (q 0) =
      Fin.cases 1 (dehomogenizedPoint q) := by
  funext i
  refine Fin.cases ?_ (fun j ↦ ?_) i
  · simp [normalizedProjectivePoint, hq₀]
  · rfl

/-- A homogeneous projective equation vanishing at `q` gives a vanishing
affine equation after dehomogenization in the nonzero zeroth chart. -/
theorem eval_projectiveDehomogenize_eq_zero_of_homogeneous
    (p : MvPolynomial (Fin (n + 1)) K) (d : ℕ)
    (hp : p.IsHomogeneous d) (q : Fin (n + 1) → K)
    (hq₀ : q 0 ≠ 0) (hvanish : MvPolynomial.eval q p = 0) :
    MvPolynomial.eval (dehomogenizedPoint q) (projectiveDehomogenize p) = 0 := by
  have hscale := eval_eq_pow_mul_eval_normalizedProjectivePoint
    p d hp q (q 0) hq₀
  rw [hvanish] at hscale
  have hnormalized :
      MvPolynomial.eval (normalizedProjectivePoint q (q 0)) p = 0 :=
    (mul_eq_zero.mp hscale.symm).resolve_left (pow_ne_zero d hq₀)
  rw [eval_projectiveDehomogenize,
    ← normalizedProjectivePoint_eq_chartPoint q hq₀]
  exact hnormalized

/-- The affine ideal generated by dehomogenizing a supplied family of
projective equations. -/
def dehomogenizedEquationIdeal {I : Type*}
    (equations : I → MvPolynomial (Fin (n + 1)) K) :
    Ideal (MvPolynomial (Fin n) K) :=
  Ideal.span (Set.range fun i ↦ projectiveDehomogenize (equations i))

/-- Vanishing descends not only for each homogeneous generator but for every
element of the affine ideal generated by their dehomogenizations. -/
theorem eval_eq_zero_of_mem_dehomogenizedEquationIdeal
    {I : Type*} (equations : I → MvPolynomial (Fin (n + 1)) K)
    (degree : I → ℕ)
    (hhomogeneous : ∀ i, (equations i).IsHomogeneous (degree i))
    (q : Fin (n + 1) → K) (hq₀ : q 0 ≠ 0)
    (hvanish : ∀ i, MvPolynomial.eval q (equations i) = 0)
    (f : MvPolynomial (Fin n) K)
    (hf : f ∈ dehomogenizedEquationIdeal equations) :
    MvPolynomial.eval (dehomogenizedPoint q) f = 0 := by
  have hle : dehomogenizedEquationIdeal equations ≤
      RingHom.ker (MvPolynomial.eval (dehomogenizedPoint q)) := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    change MvPolynomial.eval (dehomogenizedPoint q)
      (projectiveDehomogenize (equations i)) = 0
    exact eval_projectiveDehomogenize_eq_zero_of_homogeneous
      (equations i) (degree i) (hhomogeneous i) q hq₀ (hvanish i)
  exact hle hf

/-- Direct formal-chart handoff.  For the affine ideal generated by the
dehomogenized homogeneous projective equations, projective vanishing supplies
the complete base-equation hypothesis required by
`FormalDivisorLaurentConormal`.  Only the exact tangent-space identification
remains as geometric input. -/
theorem laurentPhasePoint_mem_dehomogenizedEquationConormalLocus
    {k : Type*} [Field k] {I κ : Type*} [Fintype κ]
    (equations : I → MvPolynomial (Fin (n + 1)) (LaurentSeries k))
    (degree : I → ℕ)
    (hhomogeneous : ∀ i, (equations i).IsHomogeneous (degree i))
    (q ell : Fin (n + 1) → PowerSeries k)
    (Z : Matrix (Fin (n + 1)) κ (PowerSeries k))
    (tau : Fin (n + 1) → PowerSeries k)
    (hq₀ : q 0 ≠ 0)
    (hrow : rowMul ell (formalTangentMatrix q Z tau) = 0)
    (hvanish : ∀ i, MvPolynomial.eval (laurentColumn q) (equations i) = 0)
    (htangent :
      dehomogenizedTangentSpan (laurentColumn q)
          (laurentNonpositionTangentMatrix Z tau) =
        zariskiTangentSpace (dehomogenizedPoint (laurentColumn q))
          (dehomogenizedEquationIdeal equations)) :
    Sum.elim (dehomogenizedPoint (laurentColumn q))
        (fun i ↦ laurentColumn ell i.succ) ∈
      equationConormalLocus (dehomogenizedEquationIdeal equations) := by
  apply laurentPhasePoint_mem_equationConormalLocus
    (dehomogenizedEquationIdeal equations) q ell Z tau hq₀ hrow
  · intro f hf
    exact eval_eq_zero_of_mem_dehomogenizedEquationIdeal
      equations degree hhomogeneous (laurentColumn q)
        (laurentColumn_ne_zero_of_ne_zero q hq₀) hvanish f hf
  · exact htangent

#print axioms eval_projectiveDehomogenize
#print axioms eval_eq_pow_mul_eval_normalizedProjectivePoint
#print axioms normalizedProjectivePoint_eq_chartPoint
#print axioms eval_projectiveDehomogenize_eq_zero_of_homogeneous
#print axioms eval_eq_zero_of_mem_dehomogenizedEquationIdeal
#print axioms laurentPhasePoint_mem_dehomogenizedEquationConormalLocus

end

end Stafford38.Geometry.ProjectiveEquationFormalChart
