import Stafford38.Geometry.DivisorialBoundaryExtension
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic

/-!
# A relative transcendence tower containing a selected coordinate

This file supplies the field-theoretic reduction immediately upstream of
`DivisorialBoundaryExtension`.  A selected transcendental element is extended
to a transcendence basis.  Removing that element gives a relative coefficient
field `E`; adjoining the element back recovers the full basis field.  For a
finitely generated ambient field, the extension over the full basis field is
finite, and in characteristic zero it is separable.

The output is deliberately stated with actual intermediate fields in the
ambient field.  It does not pretend that the remaining identification
`Frac(E[X]_(X)) = E(x)` is definitional: that canonical fraction-field
comparison, together with transport of the finite-dimensional instance, is
the next formal interface needed by the existing divisorial-extension theorem.
-/

namespace Stafford38.Geometry.RelativeDivisorialTower

open Set

noncomputable section

universe u v

/-- A transcendental element belongs to some transcendence basis.  Unlike the
empty-seed library theorem, this version retains the prescribed element. -/
theorem exists_transcendenceBasis_containing
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (x : K) (hx : Transcendental k x) :
    ∃ s : Set K, x ∈ s ∧
      IsTranscendenceBasis k ((↑) : s → K) := by
  have hsingleton :
      AlgebraicIndependent k ((↑) : ({x} : Set K) → K) := by
    rw [algebraicIndependent_singleton_iff ⟨x, Set.mem_singleton x⟩]
    exact hx
  obtain ⟨s, hxs, hsmax⟩ :=
    exists_maximal_algebraicIndependent ({x} : Set K) Set.univ
      (Set.subset_univ _) hsingleton
  refine ⟨s, hxs (Set.mem_singleton x), hsmax.1.1, ?_⟩
  intro t ht hst
  have hrs : Set.range ((↑) : s → K) = s := Subtype.range_coe
  rw [hrs] at hst ⊢
  apply hsmax.eq_of_le ⟨ht, Set.subset_univ _⟩
  exact hst

/-- The relative coefficient field obtained by deleting `x` from a basis. -/
abbrev coefficientField
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (s : Set K) (x : K) : IntermediateField k K :=
  IntermediateField.adjoin k (s \ {x})

/-- The field generated by a set is algebraic over the ordinary algebra
generated by that set.  Concretely, field-adjoin induction adds only inverses
to the algebraic closure operations. -/
theorem intermediateAdjoin_isAlgebraic_over_algebraAdjoin
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (t : Set K) :
    let R := Algebra.adjoin k t
    let E := IntermediateField.adjoin k t
    letI : Algebra R E :=
      (Subalgebra.inclusion
        (IntermediateField.algebra_adjoin_le_adjoin k t)).toAlgebra
    Algebra.IsAlgebraic R E := by
  dsimp only
  let R := Algebra.adjoin k t
  let E := IntermediateField.adjoin k t
  let hRE : R ≤ E.toSubalgebra :=
    IntermediateField.algebra_adjoin_le_adjoin k t
  letI : Algebra R E := (Subalgebra.inclusion hRE).toAlgebra
  refine ⟨fun y ↦ ?_⟩
  apply IntermediateField.adjoin_induction k
      (p := fun z hz ↦ IsAlgebraic R (⟨z, hz⟩ : E))
  · intro z hz
    have hmem : z ∈ E := IntermediateField.subset_adjoin k t hz
    have heq : (⟨z, hmem⟩ : E) = algebraMap R E
        (⟨z, Algebra.subset_adjoin hz⟩ : R) := by
      apply Subtype.ext
      rfl
    rw [heq]
    exact isAlgebraic_algebraMap _
  · intro a
    have heq : (⟨algebraMap k K a,
        (IntermediateField.adjoin k t).algebraMap_mem a⟩ : E) =
        algebraMap R E (algebraMap k R a) := by
      apply Subtype.ext
      rfl
    rw [heq]
    exact isAlgebraic_algebraMap _
  · intro a b _ _ ha hb
    exact ha.add hb
  · intro a _ ha
    exact ha.inv
  · intro a b _ _ ha hb
    exact ha.mul hb

/-- Deleting a prescribed element from a transcendence basis leaves a
coefficient field over which that element is still transcendental.  This is
the load-bearing relative-basis lemma needed to evaluate `E[X]` at `x`. -/
theorem transcendental_over_coefficientField
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    {s : Set K} (hs : IsTranscendenceBasis k ((↑) : s → K))
    {x : K} (hx : x ∈ s) :
    Transcendental (coefficientField k s x) x := by
  let i : s := ⟨x, hx⟩
  let t : Set s := {j | (j : K) ≠ x}
  have hi : i ∉ t := by simp [i, t]
  have ht : ((fun j : s ↦ (j : K)) '' t) = s \ {x} := by
    ext y
    constructor
    · rintro ⟨j, hj, rfl⟩
      exact ⟨j.property, by simpa [t] using hj⟩
    · rintro ⟨hy, hyx⟩
      exact ⟨⟨y, hy⟩, by simpa [t] using hyx, rfl⟩
  have htr : Transcendental (Algebra.adjoin k (s \ {x})) x := by
    have h := hs.1.transcendental_adjoin (s := t) hi
    rw [ht] at h
    exact h
  let R := Algebra.adjoin k (s \ {x})
  let E := coefficientField k s x
  let hRE : R ≤ E.toSubalgebra :=
    IntermediateField.algebra_adjoin_le_adjoin k (s \ {x})
  letI : Algebra R E := (Subalgebra.inclusion hRE).toAlgebra
  letI : Algebra R K := R.val.toRingHom.toAlgebra
  letI : IsScalarTower R E K :=
    IsScalarTower.of_algebraMap_eq (fun _ ↦ rfl)
  letI : Algebra.IsAlgebraic R E :=
    intermediateAdjoin_isAlgebraic_over_algebraAdjoin k (s \ {x})
  exact htr.extendScalars E

/-- Adjoining `x` to the coefficient field obtained from `s \ {x}` recovers
the field generated by all of `s`, provided `x ∈ s`.  This is the exact
relative decomposition used by the valuation construction. -/
theorem restrictScalars_adjoin_coordinate
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (s : Set K) (x : K) (hx : x ∈ s) :
    (IntermediateField.adjoin (coefficientField k s x) ({x} : Set K)).restrictScalars k =
      IntermediateField.adjoin k s := by
  rw [IntermediateField.adjoin_adjoin_left]
  congr 1
  rw [Set.union_comm, ← Set.insert_eq, Set.insert_diff_singleton,
    Set.insert_eq_of_mem hx]

/-- A finitely generated field extension is finite over the field generated
by any transcendence basis.  Finite generation here is field-theoretic
(`IntermediateField.FG`), not finite type as an algebra (which would be
impossible for a transcendental field extension). -/
theorem finiteDimensional_over_adjoin_transcendenceBasis
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (hfg : (⊤ : IntermediateField k K).FG)
    {s : Set K} (hs : IsTranscendenceBasis k ((↑) : s → K)) :
    FiniteDimensional (IntermediateField.adjoin k s) K := by
  let B : IntermediateField k K := IntermediateField.adjoin k s
  haveI : Algebra.IsAlgebraic B K := by
    have halg := hs.isAlgebraic_field
    have hrange : Set.range ((↑) : s → K) = s := Subtype.range_coe
    rw [hrange] at halg
    exact halg
  obtain ⟨t, ht⟩ := hfg
  have hBt : IntermediateField.adjoin B (t : Set K) = ⊤ := by
    rw [eq_top_iff]
    intro y _
    have hy : y ∈ IntermediateField.adjoin k (t : Set K) := by
      rw [ht]
      trivial
    apply IntermediateField.adjoin_induction k
        (p := fun z _ ↦ z ∈ IntermediateField.adjoin B (t : Set K))
    · intro z hz
      exact IntermediateField.subset_adjoin B (t : Set K) hz
    · intro a
      exact (IntermediateField.adjoin B (t : Set K)).algebraMap_mem
        ⟨algebraMap k K a, B.algebraMap_mem a⟩
    · exact fun _ _ _ _ ha hb ↦ add_mem ha hb
    · exact fun _ _ ha ↦ inv_mem ha
    · exact fun _ _ _ _ ha hb ↦ mul_mem ha hb
    · exact hy
  have hfieldAlg := IntermediateField.adjoin_toSubalgebra_of_isAlgebraic
    (F := B) (E := K) (S := (t : Set K))
    (fun z _ ↦ Algebra.IsAlgebraic.isAlgebraic z)
  rw [hBt] at hfieldAlg
  letI : Algebra.FiniteType B K := ⟨⟨t, hfieldAlg.symm⟩⟩
  exact Algebra.IsIntegral.finite

/-- The full relative tower produced from a prescribed transcendental
coordinate.  It records actual fields `E ⊆ F ⊆ K`, the equality
`F|_k = k(s)`, membership of `x`, and finiteness of `K/F`.

This is stronger than merely postulating a convenient coefficient field: the
fields are constructed from a basis containing the supplied coordinate. -/
theorem exists_relative_finite_tower
    (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (hfg : (⊤ : IntermediateField k K).FG)
    (x : K) (hx : Transcendental k x) :
    ∃ (s : Set K) (E : IntermediateField k K)
        (F : IntermediateField E K),
      x ∈ s ∧
      IsTranscendenceBasis k ((↑) : s → K) ∧
      E = coefficientField k s x ∧
      F = IntermediateField.adjoin E ({x} : Set K) ∧
      F.restrictScalars k = IntermediateField.adjoin k s ∧
      Transcendental E x ∧
      x ∈ F ∧
      FiniteDimensional F K := by
  obtain ⟨s, hxs, hs⟩ := exists_transcendenceBasis_containing k x hx
  let E : IntermediateField k K := coefficientField k s x
  let F : IntermediateField E K := IntermediateField.adjoin E ({x} : Set K)
  have hF : F.restrictScalars k = IntermediateField.adjoin k s := by
    exact restrictScalars_adjoin_coordinate k s x hxs
  have hfinB : FiniteDimensional (IntermediateField.adjoin k s) K :=
    finiteDimensional_over_adjoin_transcendenceBasis k hfg hs
  letI : FiniteDimensional (IntermediateField.adjoin k s) K := hfinB
  -- `F` and `k(s)` have the same elements in `K`; use the induced inclusion
  -- tower to transfer algebraicity and finite type to the relative field.
  have hB_le_F : IntermediateField.adjoin k s ≤ F.restrictScalars k := hF.ge
  letI : Algebra (IntermediateField.adjoin k s) F :=
    (IntermediateField.inclusion hB_le_F).toAlgebra
  letI : IsScalarTower (IntermediateField.adjoin k s) F K :=
    IsScalarTower.of_algebraMap_eq (fun _ ↦ rfl)
  haveI : Algebra.IsAlgebraic (IntermediateField.adjoin k s) K :=
    Algebra.IsAlgebraic.of_finite (IntermediateField.adjoin k s) K
  haveI : Algebra.IsAlgebraic F K :=
    Algebra.IsAlgebraic.extendScalars
      (IntermediateField.inclusion_injective hB_le_F)
  letI : Algebra.FiniteType F K :=
    Algebra.FiniteType.of_restrictScalars_finiteType
      (IntermediateField.adjoin k s) F K
  letI : Algebra.IsIntegral F K :=
    ⟨fun y ↦ (Algebra.IsAlgebraic.isAlgebraic y).isIntegral⟩
  have hfinF : FiniteDimensional F K := Algebra.IsIntegral.finite
  have hxE : Transcendental E x :=
    transcendental_over_coefficientField k hs hxs
  refine ⟨s, E, F, hxs, hs, rfl, rfl, hF, hxE, ?_, hfinF⟩
  exact IntermediateField.subset_adjoin E ({x} : Set K) (Set.mem_singleton x)

/-- In characteristic zero, the finite relative extension just constructed is
automatically separable.  This closes the separability hypothesis required by
`DivisorialBoundaryExtension`. -/
theorem exists_relative_finite_separable_tower_of_charZero
    (k : Type u) [Field k] [CharZero k]
    {K : Type v} [Field K] [Algebra k K]
    (hfg : (⊤ : IntermediateField k K).FG)
    (x : K) (hx : Transcendental k x) :
    ∃ (s : Set K) (E : IntermediateField k K)
        (F : IntermediateField E K),
      x ∈ s ∧
      IsTranscendenceBasis k ((↑) : s → K) ∧
      E = coefficientField k s x ∧
      F = IntermediateField.adjoin E ({x} : Set K) ∧
      F.restrictScalars k = IntermediateField.adjoin k s ∧
      Transcendental E x ∧
      x ∈ F ∧
      FiniteDimensional F K ∧
      Algebra.IsSeparable F K := by
  obtain ⟨s, E, F, hxs, hs, hE, hFdef, hFrestrict, hxE, hxF, hfin⟩ :=
    exists_relative_finite_tower k hfg x hx
  letI : FiniteDimensional F K := hfin
  letI : CharZero F :=
    charZero_of_injective_algebraMap (algebraMap k F).injective
  letI : Algebra.IsIntegral F K :=
    ⟨fun y ↦ (IsAlgebraic.of_finite F y).isIntegral⟩
  let hsep : Algebra.IsSeparable F K :=
    Algebra.IsSeparable.of_integral F K
  exact ⟨s, E, F, hxs, hs, hE, hFdef, hFrestrict, hxE, hxF, hfin, hsep⟩

#print axioms exists_transcendenceBasis_containing
#print axioms intermediateAdjoin_isAlgebraic_over_algebraAdjoin
#print axioms transcendental_over_coefficientField
#print axioms restrictScalars_adjoin_coordinate
#print axioms finiteDimensional_over_adjoin_transcendenceBasis
#print axioms exists_relative_finite_tower
#print axioms exists_relative_finite_separable_tower_of_charZero

end

end Stafford38.Geometry.RelativeDivisorialTower
