import Stafford38.Geometry.RelativeDivisorialTower
import Stafford38.Geometry.DivisorialBoundaryExtension
import Mathlib.RingTheory.AlgebraicIndependent.Adjoin
import Mathlib.RingTheory.Localization.LocalizationLocalization

/-!
# Transport from a relative rational function field to the coordinate DVR

This file identifies the fraction field of the coordinate-zero local ring
`E[X]_(X)` with the concrete simple transcendental field `E(x)`.  The
equivalence is compatible with evaluation at `x`; it therefore transports the
finite separable tower constructed in `RelativeDivisorialTower` to the exact
input expected by `DivisorialBoundaryExtension`.
-/

namespace Stafford38.Geometry.RelativeFractionFieldTransport

open Set
open IsLocalRing
open Stafford38.Geometry.AsymptoticDivisorExistence
open Stafford38.Geometry.RelativeDivisorialTower
open Stafford38.Geometry.DivisorialBoundaryExtension

noncomputable section

set_option maxHeartbeats 800000

universe u v

attribute [-instance] instAlgebraAtPrimeFractionRing

/-- Evaluation at a transcendental element identifies the polynomial
fraction field with the concrete intermediate field generated by that
element. -/
def polynomialFractionEquivAdjoin
    (E : Type u) [Field E]
    {K : Type v} [Field K] [Algebra E K]
    (x : K) (hx : Transcendental E x) :
    FractionRing (Polynomial E) ≃ₐ[E]
      IntermediateField.adjoin E ({x} : Set K) := by
  let g : Polynomial E →ₐ[E] K := Polynomial.aeval x
  let i : FractionRing (Polynomial E) →ₐ[E] K :=
    IsFractionRing.liftAlgHom
      (K := FractionRing (Polynomial E))
      (transcendental_iff_injective.mp hx)
  exact (AlgEquiv.ofInjectiveField i).trans
    (IntermediateField.equivOfEq
      (IsFractionRing.liftAlgHom_fieldRange_eq_of_range_eq
        (g := g)
        (transcendental_iff_injective.mp hx)
        (Algebra.adjoin_singleton_eq_range_aeval E x).symm))

@[simp]
theorem polynomialFractionEquivAdjoin_algebraMap
    (E : Type u) [Field E]
    {K : Type v} [Field K] [Algebra E K]
    (x : K) (hx : Transcendental E x) (p : Polynomial E) :
    ((polynomialFractionEquivAdjoin E x hx
        (algebraMap (Polynomial E) (FractionRing (Polynomial E)) p) :
      IntermediateField.adjoin E ({x} : Set K)) : K) =
      Polynomial.aeval x p := by
  let g : Polynomial E →+* K := (Polynomial.aeval x).toRingHom
  change IsFractionRing.lift (K := FractionRing (Polynomial E))
      (transcendental_iff_injective.mp hx)
      (algebraMap (Polynomial E) (FractionRing (Polynomial E)) p) =
    Polynomial.aeval x p
  exact IsFractionRing.lift_algebraMap
    (transcendental_iff_injective.mp hx) p

/-- Localizing `E[X]` away from `(X)` does not change its fraction field.
Composing that canonical comparison with transcendental evaluation realizes
the result as the concrete field `E(x)`. -/
def coordinateLocalFractionEquivAdjoin
    (E : Type u) [Field E]
    {K : Type v} [Field K] [Algebra E K]
    (x : K) (hx : Transcendental E x) :
    FractionRing (CoordinateZeroLocalRing E) ≃ₐ[E]
      IntermediateField.adjoin E ({x} : Set K) := by
  letI : IsScalarTower E (CoordinateZeroLocalRing E)
      (FractionRing (Polynomial E)) :=
    IsScalarTower.of_algebraMap_eq fun a => by
      rw [IsScalarTower.algebraMap_apply E (Polynomial E)
        (CoordinateZeroLocalRing E)]
      rw [IsScalarTower.algebraMap_apply E (Polynomial E)
        (FractionRing (Polynomial E))]
      exact IsScalarTower.algebraMap_apply (Polynomial E)
        (CoordinateZeroLocalRing E) (FractionRing (Polynomial E))
        (algebraMap E (Polynomial E) a)
  let e₀ : FractionRing (CoordinateZeroLocalRing E) ≃ₐ[E]
      FractionRing (Polynomial E) :=
    (FractionRing.algEquiv (CoordinateZeroLocalRing E)
      (FractionRing (Polynomial E))).restrictScalars E
  exact e₀.trans (polynomialFractionEquivAdjoin E x hx)

/-- The fraction-field comparison sends the distinguished local coordinate
to the selected element `x`, not merely to an abstract generator. -/
@[simp]
theorem coordinateLocalFractionEquivAdjoin_X
    (E : Type u) [Field E]
    {K : Type v} [Field K] [Algebra E K]
    (x : K) (hx : Transcendental E x) :
    let R := CoordinateZeroLocalRing E
    let L := FractionRing R
    (((coordinateLocalFractionEquivAdjoin E x hx
        (algebraMap R L
          (algebraMap (Polynomial E) R Polynomial.X)) :
      IntermediateField.adjoin E ({x} : Set K)) : K)) = x := by
  dsimp only
  letI : IsScalarTower E (CoordinateZeroLocalRing E)
      (FractionRing (Polynomial E)) :=
    IsScalarTower.of_algebraMap_eq fun a => by
      rw [IsScalarTower.algebraMap_apply E (Polynomial E)
        (CoordinateZeroLocalRing E)]
      rw [IsScalarTower.algebraMap_apply E (Polynomial E)
        (FractionRing (Polynomial E))]
      exact IsScalarTower.algebraMap_apply (Polynomial E)
        (CoordinateZeroLocalRing E) (FractionRing (Polynomial E))
        (algebraMap E (Polynomial E) a)
  rw [coordinateLocalFractionEquivAdjoin, AlgEquiv.trans_apply]
  change ↑((polynomialFractionEquivAdjoin E x hx)
    ((FractionRing.algEquiv (CoordinateZeroLocalRing E)
      (FractionRing (Polynomial E)))
      ((algebraMap (CoordinateZeroLocalRing E)
        (FractionRing (CoordinateZeroLocalRing E)))
        ((algebraMap (Polynomial E) (CoordinateZeroLocalRing E))
          Polynomial.X)))) = x
  rw [AlgEquiv.commutes]
  rw [← IsScalarTower.algebraMap_apply (Polynomial E)
    (CoordinateZeroLocalRing E) (FractionRing (Polynomial E))]
  simpa only [Polynomial.aeval_X] using
    polynomialFractionEquivAdjoin_algebraMap E x hx Polynomial.X

/-- A finite separable extension of the concrete field `E(x)` gives the exact
fraction-field action needed by the coordinate DVR theorem.  Both finiteness
and separability are transported across the displayed field equivalence; the
coordinate compatibility is discharged by
`coordinateLocalFractionEquivAdjoin_X`. -/
theorem exists_discreteBoundaryRefinement_of_adjoin
    (E : Type u) [Field E]
    {K : Type v} [Field K] [Algebra E K]
    (x : K) (hx : Transcendental E x)
    (hfin : FiniteDimensional
      (IntermediateField.adjoin E ({x} : Set K)) K)
    (hsep : Algebra.IsSeparable
      (IntermediateField.adjoin E ({x} : Set K)) K) :
    ∃ V : ValuationSubring K,
      IsDiscreteValuationRing V.toSubring ∧
      ∃ xV : V.toSubring,
        (xV : K) = x ∧ xV ≠ 0 ∧ ¬IsUnit xV := by
  let R := CoordinateZeroLocalRing E
  let L := FractionRing R
  let F := IntermediateField.adjoin E ({x} : Set K)
  let e : L ≃ₐ[E] F := coordinateLocalFractionEquivAdjoin E x hx
  letI : Algebra R F :=
    (e.toRingEquiv.toRingHom.comp (algebraMap R L)).toAlgebra
  let eR : L ≃ₐ[R] F :=
    { e.toRingEquiv with
      commutes' := fun _ => rfl }
  letI : IsFractionRing R F :=
    IsLocalization.isLocalization_of_algEquiv (nonZeroDivisors R) eR
  letI : Algebra R K :=
    ((algebraMap F K).comp (algebraMap R F)).toAlgebra
  letI : IsScalarTower R F K :=
    IsScalarTower.of_algebraMap_eq fun _ => rfl
  letI : FiniteDimensional F K := hfin
  letI : Algebra.IsSeparable F K := hsep
  let q : R := algebraMap (Polynomial E) R Polynomial.X
  have hq_ne : q ≠ 0 := by
    intro hq
    apply Polynomial.X_ne_zero (R := E)
    apply IsLocalization.injective R
      (coordinateZeroPrime E).primeCompl_le_nonZeroDivisors
    simpa only [q, map_zero] using hq
  have hq_nonunit : ¬IsUnit q := by
    rw [← mem_nonunits_iff, ← mem_maximalIdeal]
    exact (IsLocalization.AtPrime.to_map_mem_maximal_iff
      R (coordinateZeroPrime E) Polynomial.X).2
        (Ideal.mem_span_singleton_self Polynomial.X)
  have hcoordinate : algebraMap R K q = x := by
    change (((e (algebraMap R L q) : F) : K)) = x
    exact coordinateLocalFractionEquivAdjoin_X E x hx
  obtain ⟨V, hV, qV, hqV, hqV_ne, hqV_nonunit⟩ :=
    exists_discreteValuationSubring_over_maximalIdeal
      (A := R) (F := F) (L := K) q hq_ne hq_nonunit
  exact ⟨V, hV, qV, hqV.trans hcoordinate, hqV_ne, hqV_nonunit⟩

/-- The relative tower constructed from a finitely generated characteristic-
zero function field therefore has an actual discrete boundary place above
the selected coordinate. -/
theorem exists_discreteBoundaryRefinement_of_fg_charZero
    (k : Type u) [Field k] [CharZero k]
    {K : Type v} [Field K] [Algebra k K]
    (hfg : (⊤ : IntermediateField k K).FG)
    (x : K) (hx : Transcendental k x) :
    ∃ V : ValuationSubring K,
      IsDiscreteValuationRing V.toSubring ∧
      ∃ xV : V.toSubring,
        (xV : K) = x ∧ xV ≠ 0 ∧ ¬IsUnit xV := by
  obtain ⟨s, E, F, hxs, hs, hE, hF, hrestrict, hxE, hxF,
      hfin, hsep⟩ :=
    exists_relative_finite_separable_tower_of_charZero k hfg x hx
  subst F
  exact exists_discreteBoundaryRefinement_of_adjoin
    E x hxE hfin hsep

/-- Structured form of the preceding theorem, ready for the downstream
projective order-gap consumer. -/
theorem exists_discreteBoundaryRefinement_of_fg_charZero_structured
    (k : Type u) [Field k] [CharZero k]
    {K : Type v} [Field K] [Algebra k K]
    (hfg : (⊤ : IntermediateField k K).FG)
    (x : K) (hx : Transcendental k x) :
    Nonempty (DiscreteBoundaryRefinement k x) := by
  obtain ⟨V, hV, xV, hxV, hxV_ne, hxV_nonunit⟩ :=
    exists_discreteBoundaryRefinement_of_fg_charZero k hfg x hx
  exact ⟨{
    valuation := V
    isDiscrete := hV
    coordinate := xV
    coordinate_eq := hxV
    coordinate_ne := hxV_ne
    coordinate_nonunit := hxV_nonunit
  }⟩

#print axioms polynomialFractionEquivAdjoin
#print axioms polynomialFractionEquivAdjoin_algebraMap
#print axioms coordinateLocalFractionEquivAdjoin
#print axioms coordinateLocalFractionEquivAdjoin_X
#print axioms exists_discreteBoundaryRefinement_of_adjoin
#print axioms exists_discreteBoundaryRefinement_of_fg_charZero
#print axioms exists_discreteBoundaryRefinement_of_fg_charZero_structured

attribute [instance] instAlgebraAtPrimeFractionRing

end

end Stafford38.Geometry.RelativeFractionFieldTransport
