module
public import Stafford38.Geometry.ResidueBasisLocalization
public import Stafford38.Geometry.ChartGenericPointFractionRing
public import Stafford38.Geometry.ResidueLiftIndependence
public import Mathlib.RingTheory.Localization.FractionRing
public import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
public import Mathlib.RingTheory.Localization.Basic
public import Mathlib.RingTheory.Valuation.ValuationSubring

@[expose] public section

noncomputable section
set_option autoImplicit false
set_option maxHeartbeats 1600000

open IsLocalRing
open scoped IntermediateField.algebraAdjoinAdjoin

namespace Stafford38.Geometry.SelectedResidueCoefficientLocalization

universe u

variable {k F : Type u} [Field k] [Field F] [Algebra k F]

/-- Restrict the retained ground map to the actual affine chart algebra. -/
def chartAlgebraToValuation
    (Q : Subalgebra k F) (V : ValuationSubring F)
    [IsLocalRing V.toSubring]
    [Algebra k V.toSubring]
    (hground : ∀ c : k,
      (algebraMap k V.toSubring c : F) = algebraMap k F c)
    (hQV : Q.toSubring ≤ V.toSubring) : Q →ₐ[k] V.toSubring := {
  toRingHom := RingHom.codRestrict Q.val.toRingHom V.toSubring (fun q => hQV q.property)
  commutes' := by
    intro c
    apply Subtype.ext
    simpa using (hground c).symm
}

/-- The coefficient subalgebra generated by the selected chart-coordinate
lifts, sent to the same retained residue field by reduction. -/
noncomputable def selectedCoefficientResidueMap
    (Q : Subalgebra k F) (V : ValuationSubring F)
    [IsLocalRing V.toSubring]
    [Algebra k V.toSubring]
    (hground : ∀ c : k,
      (algebraMap k V.toSubring c : F) = algebraMap k F c)
    [Algebra k (ResidueField V.toSubring)]
    [IsScalarTower k V.toSubring (ResidueField V.toSubring)]
    (hQV : Q.toSubring ≤ V.toSubring) (t : Set (ResidueField V.toSubring))
    (x : t → Q) :
    let A : Subalgebra k Q := Algebra.adjoin k (Set.range x)
    A →ₐ[k] ResidueField V.toSubring := by
  let A : Subalgebra k Q := Algebra.adjoin k (Set.range x)
  let ρ : V.toSubring →ₐ[k] ResidueField V.toSubring := {
    toRingHom := residue V.toSubring
    commutes' := by
      intro c
      rw [← ResidueField.algebraMap_eq]
      exact (IsScalarTower.algebraMap_apply k V.toSubring
        (ResidueField V.toSubring) c).symm
  }
  exact ρ.comp ((chartAlgebraToValuation Q V hground hQV).comp (Subalgebra.val A))

/-- Lifts of a transcendence basis remain algebraically independent in the
chart algebra, since a polynomial relation would reduce to the same residue
relation. -/
theorem selected_lifts_algebraicallyIndependent
    (Q : Subalgebra k F) (V : ValuationSubring F)
    [IsLocalRing V.toSubring]
    [Algebra k V.toSubring]
    (hground : ∀ c : k,
      (algebraMap k V.toSubring c : F) = algebraMap k F c)
    [Algebra k (ResidueField V.toSubring)]
    [IsScalarTower k V.toSubring (ResidueField V.toSubring)]
    (hQV : Q.toSubring ≤ V.toSubring)
    {t : Set (ResidueField V.toSubring)}
    (htb : IsTranscendenceBasis k ((↑) : t → ResidueField V.toSubring))
    (x : t → Q)
    (hx : ∀ z, residue V.toSubring
      ⟨(x z : F), hQV (x z).property⟩ = (z : ResidueField V.toSubring)) :
    AlgebraicIndependent k (fun z : t => x z) := by
  have hAIκ : AlgebraicIndependent k ((↑) : t → ResidueField V.toSubring) := htb.1
  let xV : t → V.toSubring := fun z => ⟨(x z : F), hQV (x z).property⟩
  have hxV : ∀ z, residue V.toSubring (xV z) = (z : ResidueField V.toSubring) := hx
  letI : Algebra V.toSubring F := V.toSubring.subtype.toAlgebra
  letI : IsScalarTower k V.toSubring F :=
    IsScalarTower.of_algebraMap_eq (fun c => (hground c).symm)
  have hinjVF : Function.Injective (algebraMap V.toSubring F) := by
    change Function.Injective (fun a : V.toSubring => (a : F))
    exact Subtype.val_injective
  have hAI_F :=
    Stafford38.Geometry.ResidueLiftIndependence.algebraicIndependent_of_residue
      (V := V.toSubring) (K := F) hinjVF
      xV (by
        convert hAIκ using 1
        funext z
        exact hxV z)
  have hAIx : AlgebraicIndependent k (fun z : t => (x z : F)) := by
    convert hAI_F using 1
    funext z
    rfl
  rw [algebraicIndependent_iff_injective_aeval]
  intro p q hpq
  have hmap (r : MvPolynomial t k) :
      algebraMap Q F (MvPolynomial.aeval x r) =
        MvPolynomial.aeval (fun z : t => (x z : F)) r := by
    rw [MvPolynomial.map_aeval, MvPolynomial.aeval_eq_eval₂Hom]
    have hcoeff : (algebraMap Q F).comp (algebraMap k Q) = algebraMap k F := by
      ext c
      rfl
    rw [hcoeff]
    rfl
  apply (algebraicIndependent_iff_injective_aeval.mp hAIx)
  calc
    MvPolynomial.aeval (fun z : t => (x z : F)) p = algebraMap Q F (MvPolynomial.aeval x p) :=
      (hmap p).symm
    _ = algebraMap Q F (MvPolynomial.aeval x q) := congrArg (algebraMap Q F) hpq
    _ = MvPolynomial.aeval (fun z : t => (x z : F)) q := hmap q

/-- Reduction is injective on the subalgebra generated by the chosen lifts. -/
theorem selectedCoefficientResidueMap_injective
    (Q : Subalgebra k F) (V : ValuationSubring F)
    [IsLocalRing V.toSubring]
    [Algebra k V.toSubring]
    [Algebra k (ResidueField V.toSubring)]
    [IsScalarTower k V.toSubring (ResidueField V.toSubring)]
    (hQV : Q.toSubring ≤ V.toSubring)
    (hground : ∀ c : k,
      (algebraMap k V.toSubring c : F) = algebraMap k F c)
    {t : Set (ResidueField V.toSubring)}
    (htb : IsTranscendenceBasis k ((↑) : t → ResidueField V.toSubring))
    (x : t → Q)
    (hx : ∀ z, residue V.toSubring
      ⟨(x z : F), hQV (x z).property⟩ = (z : ResidueField V.toSubring)) :
    let A : Subalgebra k Q := Algebra.adjoin k (Set.range x)
    Function.Injective (selectedCoefficientResidueMap Q V hground hQV t x) ∧
      (selectedCoefficientResidueMap Q V hground hQV t x).range =
        Algebra.adjoin k (Set.range (fun z : t => (z : ResidueField V.toSubring))) := by
  classical
  let A : Subalgebra k Q := Algebra.adjoin k (Set.range x)
  let ψ : A →ₐ[k] ResidueField V.toSubring :=
    selectedCoefficientResidueMap Q V hground hQV t x
  let evQ : MvPolynomial t k →ₐ[k] Q := MvPolynomial.aeval x
  have hevQ : Function.Injective evQ := by
    rw [← algebraicIndependent_iff_injective_aeval]
    exact selected_lifts_algebraicallyIndependent Q V hground hQV htb x hx
  have hrange : evQ.range = A := (Algebra.adjoin_range_eq_range_aeval k x).symm
  let eA : MvPolynomial t k ≃ₐ[k] A :=
    (AlgEquiv.ofInjective evQ hevQ).trans (Subalgebra.equivOfEq evQ.range A hrange)
  have heA (p : MvPolynomial t k) : (eA p : Q) = evQ p := by
    simp [eA]
  have hcomp : ψ.comp eA.toAlgHom =
      MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring)) := by
    ext z
    change ψ (eA (MvPolynomial.X z)) =
      MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring))
        (MvPolynomial.X z)
    rw [MvPolynomial.aeval_X]
    change residue V.toSubring
      (chartAlgebraToValuation Q V hground hQV
        ((eA (MvPolynomial.X z) : A) : Q)) =
        (z : ResidueField V.toSubring)
    have hmapx : chartAlgebraToValuation Q V hground hQV (x z) =
        (⟨(x z : F), hQV (x z).property⟩ : V.toSubring) := by
      apply Subtype.ext
      rfl
    rw [heA, MvPolynomial.aeval_X]
    change residue V.toSubring
      (chartAlgebraToValuation Q V hground hQV (x z)) =
        (z : ResidueField V.toSubring)
    rw [hmapx]
    exact hx z
  have hevalκ : Function.Injective
      (MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring)) :
        MvPolynomial t k →ₐ[k] ResidueField V.toSubring) :=
    (algebraicIndependent_iff_injective_aeval.mpr htb.1)
  constructor
  · change Function.Injective ψ
    intro a b hab
    obtain ⟨p, hp⟩ := eA.surjective a
    obtain ⟨q, hq⟩ := eA.surjective b
    have hpq : MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring)) p =
        MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring)) q := by
      calc
        _ = ψ (eA p) := (AlgHom.congr_fun hcomp p).symm
        _ = ψ a := congrArg ψ hp
        _ = ψ b := hab
        _ = ψ (eA q) := congrArg ψ hq.symm
        _ = _ := AlgHom.congr_fun hcomp q
    have hpq' : p = q := hevalκ hpq
    calc
      a = eA p := hp.symm
      _ = eA q := congrArg eA hpq'
      _ = b := hq
  · have hrangeMaps : ψ.range = (ψ.comp eA.toAlgHom).range := by
      apply Subalgebra.ext
      intro y
      constructor
      · rintro ⟨a, rfl⟩
        obtain ⟨p, rfl⟩ := eA.surjective a
        exact ⟨p, rfl⟩
      · rintro ⟨p, hp⟩
        exact ⟨eA p, hp⟩
    calc
      ψ.range = (ψ.comp eA.toAlgHom).range := hrangeMaps
      _ = (MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring))).range := by
        rw [hcomp]
      _ = Algebra.adjoin k (Set.range (fun z : t => (z : ResidueField V.toSubring))) :=
        (Algebra.adjoin_range_eq_range_aeval k _).symm

/-- The polynomial fraction field on the selected residue coordinates maps
into the retained valuation ring. Its residue is the canonical embedding of
the field generated by those coordinates. -/
theorem exists_selected_fraction_field_maps
    (Q : Subalgebra k F) (V : ValuationSubring F)
    [IsLocalRing V.toSubring]
    [Algebra k V.toSubring]
    (hground : ∀ c : k,
      (algebraMap k V.toSubring c : F) = algebraMap k F c)
    [Algebra k (ResidueField V.toSubring)]
    [IsScalarTower k V.toSubring (ResidueField V.toSubring)]
    (hQV : Q.toSubring ≤ V.toSubring)
    {t : Set (ResidueField V.toSubring)}
    (htb : IsTranscendenceBasis k ((↑) : t → ResidueField V.toSubring))
    (x : t → Q)
    (hx : ∀ z, residue V.toSubring
      ⟨(x z : F), hQV (x z).property⟩ = (z : ResidueField V.toSubring)) :
    let A : Subalgebra k Q := Algebra.adjoin k (Set.range x)
    let E := FractionRing (MvPolynomial t k)
    ∃ (eA : MvPolynomial t k ≃ₐ[k] A)
      (fA : A →ₐ[k] V.toSubring)
      (iA : A →ₐ[k] E)
      (g : E →ₐ[k] ResidueField V.toSubring)
      (fE : E →ₐ[k] V.toSubring),
      Function.Injective g ∧
      g.fieldRange = IntermediateField.adjoin k
        (Set.range (fun z : t => (z : ResidueField V.toSubring))) ∧
      (∀ z : t, ((eA (MvPolynomial.X z) : A) : Q) = x z) ∧
      (∀ z : t, fA (eA (MvPolynomial.X z)) =
        (⟨(x z : F), hQV (x z).property⟩ : V.toSubring)) ∧
      (∀ z : t, g (algebraMap (MvPolynomial t k) E (MvPolynomial.X z)) =
        (z : ResidueField V.toSubring)) ∧
      (∀ p : MvPolynomial t k,
        iA (eA p) = algebraMap (MvPolynomial t k) E p) ∧
      (residue V.toSubring).comp fE.toRingHom = g.toRingHom ∧
      fE.toRingHom.comp iA.toRingHom = fA.toRingHom := by
  classical
  let A : Subalgebra k Q := Algebra.adjoin k (Set.range x)
  let P := MvPolynomial t k
  let E := FractionRing P
  letI : IsDomain A := inferInstance
  letI : Field E := FractionRing.field P
  let qV : Q →ₐ[k] V.toSubring := chartAlgebraToValuation Q V hground hQV
  let evQ : P →ₐ[k] Q := MvPolynomial.aeval x
  have hevQ : Function.Injective evQ := by
    rw [← algebraicIndependent_iff_injective_aeval]
    exact selected_lifts_algebraicallyIndependent Q V hground hQV htb x hx
  have hrange : evQ.range = A := (Algebra.adjoin_range_eq_range_aeval k x).symm
  let eA : P ≃ₐ[k] A :=
    (AlgEquiv.ofInjective evQ hevQ).trans (Subalgebra.equivOfEq evQ.range A hrange)
  have heA (p : P) : (eA p : Q) = evQ p := by simp [eA]
  have heAvar (z : t) : ((eA (MvPolynomial.X z) : A) : Q) = x z := by
    rw [heA]
    exact MvPolynomial.aeval_X x z
  let iA : A →ₐ[k] E := (IsScalarTower.toAlgHom k P E).comp eA.symm.toAlgHom
  let fA : A →ₐ[k] V.toSubring := qV.comp (Subalgebra.val A)
  let evV : P →ₐ[k] V.toSubring := qV.comp evQ
  let evκ : P →ₐ[k] ResidueField V.toSubring :=
    MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring))
  let ρ : V.toSubring →ₐ[k] ResidueField V.toSubring := {
    toRingHom := residue V.toSubring
    commutes' := by
      intro c
      rw [← ResidueField.algebraMap_eq]
      exact (IsScalarTower.algebraMap_apply k V.toSubring
        (ResidueField V.toSubring) c).symm
  }
  have hρev : ρ.comp evV = evκ := by
    ext z
    dsimp [evV, evQ, ρ, evκ]
    simp only [AlgHom.comp_apply, MvPolynomial.aeval_X]
    change residue V.toSubring (qV (x z)) = (z : ResidueField V.toSubring)
    have hmapx : qV (x z) =
        (⟨(x z : F), hQV (x z).property⟩ : V.toSubring) := by
      apply Subtype.ext
      rfl
    rw [hmapx]
    exact hx z
  have hevκ : Function.Injective evκ :=
    (algebraicIndependent_iff_injective_aeval.mpr htb.1)
  have hevV : Function.Injective evV := by
    intro p q hpq
    apply hevκ
    calc
      evκ p = ρ (evV p) := (AlgHom.congr_fun hρev p).symm
      _ = ρ (evV q) := congrArg ρ hpq
      _ = evκ q := AlgHom.congr_fun hρev q
  have hunitV : ∀ s : nonZeroDivisors P, IsUnit (evV s.1) := by
    intro s
    apply (IsLocalRing.notMem_maximalIdeal).1
    intro hs
    have hres0 : ρ (evV s.1) = 0 :=
      (IsLocalRing.residue_eq_zero_iff (evV s.1)).2 hs
    have heval0 : evκ s.1 = 0 := by
      rw [← AlgHom.congr_fun hρev s.1]
      exact hres0
    have hp0 : s.1 = 0 := hevκ (by simpa using heval0)
    exact (nonZeroDivisors.ne_zero s.2) hp0
  have hunitκ : ∀ s : nonZeroDivisors P, IsUnit (evκ s.1) := by
    intro s
    apply isUnit_iff_ne_zero.mpr
    intro hs
    exact (nonZeroDivisors.ne_zero s.2) (hevκ (by simpa using hs))
  have hg : Function.Injective (IsFractionRing.liftAlgHom hevκ : E →ₐ[k]
      ResidueField V.toSubring) := by
    change Function.Injective (IsLocalization.lift hunitκ)
    rw [IsLocalization.lift_injective_iff hunitκ]
    intro p q
    constructor
    · intro hpq
      exact congrArg evκ ((FaithfulSMul.algebraMap_injective P E) hpq)
    · intro hpq
      exact congrArg (algebraMap P E) (hevκ hpq)
  let fE : E →ₐ[k] V.toSubring :=
    IsLocalization.liftAlgHom (A := k) (M := nonZeroDivisors P) hunitV
  let g : E →ₐ[k] ResidueField V.toSubring := IsFractionRing.liftAlgHom hevκ
  have hfieldRange : g.fieldRange = IntermediateField.adjoin k
      (Set.range (fun z : t => (z : ResidueField V.toSubring))) := by
    apply IsFractionRing.liftAlgHom_fieldRange_eq_of_range_eq hevκ
    exact (Algebra.adjoin_range_eq_range_aeval k
      (fun z : t => (z : ResidueField V.toSubring))).symm
  have hfEbase : fE.comp (IsScalarTower.toAlgHom k P E) = evV := by
    apply AlgHom.coe_ringHom_injective
    apply RingHom.ext
    intro p
    change fE (algebraMap P E p) = evV p
    change IsLocalization.lift hunitV (algebraMap P E p) = evV p
    exact IsLocalization.lift_eq hunitV p
  have hgbase : g.comp (IsScalarTower.toAlgHom k P E) = evκ := by
    apply AlgHom.coe_ringHom_injective
    apply RingHom.ext
    intro p
    change g (algebraMap P E p) = evκ p
    rw [IsFractionRing.liftAlgHom_apply, IsFractionRing.lift_algebraMap hevκ]
    rfl
  have hgvar (z : t) : g (algebraMap P E (MvPolynomial.X z)) =
      (z : ResidueField V.toSubring) := by
    have h := AlgHom.congr_fun hgbase (MvPolynomial.X z)
    change g (algebraMap P E (MvPolynomial.X z)) = evκ (MvPolynomial.X z) at h
    calc
      g (algebraMap P E (MvPolynomial.X z)) = evκ (MvPolynomial.X z) := h
      _ = (z : ResidueField V.toSubring) := by
        change MvPolynomial.aeval (fun z : t => (z : ResidueField V.toSubring))
          (MvPolynomial.X z) = _
        rw [MvPolynomial.aeval_X]
  have hfAvar (z : t) : fA (eA (MvPolynomial.X z)) =
      (⟨(x z : F), hQV (x z).property⟩ : V.toSubring) := by
    apply Subtype.ext
    simpa [fA, qV, chartAlgebraToValuation] using
      congrArg (fun y : Q => (y : F)) (heAvar z)
  have hiA : ∀ p : P, iA (eA p) = algebraMap P E p := by
    intro p
    simp [iA]
  have hred : ρ.comp fE = g := by
    apply IsLocalization.algHom_ext (W := nonZeroDivisors P)
    calc
      (ρ.comp fE).comp (IsScalarTower.toAlgHom k P E) = ρ.comp evV := by
        rw [AlgHom.comp_assoc, hfEbase]
      _ = evκ := hρev
      _ = g.comp (IsScalarTower.toAlgHom k P E) := hgbase.symm
  have hcomp : fE.comp iA = fA := by
    apply AlgHom.ext
    intro a
    dsimp [iA, fA]
    change fE (algebraMap P E (eA.symm a)) = qV ((a : A) : Q)
    change IsLocalization.lift hunitV (algebraMap P E (eA.symm a)) =
      qV ((a : A) : Q)
    rw [IsLocalization.lift_eq hunitV]
    have hback : evQ (eA.symm a) = (a : Q) := by
      calc
        evQ (eA.symm a) = (eA (eA.symm a) : Q) := (heA _).symm
        _ = (a : Q) := congrArg (fun b : A => (b : Q)) (eA.apply_symm_apply a)
    change evV (eA.symm a) = qV ((a : A) : Q)
    exact congrArg qV hback
  exact ⟨eA, fA, iA, g, fE, hg, hfieldRange, heAvar, hfAvar, hgvar, hiA,
    congrArg AlgHom.toRingHom hred, congrArg AlgHom.toRingHom hcomp⟩

end Stafford38.Geometry.SelectedResidueCoefficientLocalization
