import Stafford38.Geometry.ActualSameWitnessDivisorNumerator

#check Stafford38.Geometry.ActualSameWitnessDivisorNumerator.actualParameterOutput
#check Stafford38.Geometry.ActualSameWitnessDivisorNumerator.exists_actual_parameter_with_retained_orders
#print axioms Stafford38.Geometry.ActualSameWitnessDivisorNumerator.exists_actual_parameter_with_retained_orders
#print axioms Stafford38.Geometry.ActualSameWitnessDivisorNumerator.selected_basis_and_parameter_output
