module
public import Stafford38.Geometry.ActualWitnessCommonOpenColumnGlue

@[expose] public section

#check Stafford38.Geometry.ActualWitnessCommonOpenColumnGlue.actual_witness_commonOpen_eq_pointLocal
#print axioms Stafford38.Geometry.ActualWitnessCommonOpenColumnGlue.actual_witness_commonOpen_eq_pointLocal
