module
public import Stafford38.Geometry.ActualChartValuationImage
public import Stafford38.Geometry.ActualSmoothOpenChartNumerator
public import Stafford38.Geometry.SelectedResidueNormalizationLocalization

@[expose] public section

#check Stafford38.Geometry.ActualChartValuationImage.normalizedCoordinate_mem_chartGenericPointSubalgebra
#check Stafford38.Geometry.ActualChartValuationImage.exists_actual_normalizedProjectiveColumn
#check Stafford38.Geometry.SelectedResidueCoefficientLocalization.chartSubalgebraToIntegralClosure
#check Stafford38.Geometry.ActualSmoothOpenChartNumerator.exists_actual_normalizedProjectiveColumn_in_integralClosure
#print axioms Stafford38.Geometry.ActualChartValuationImage.normalizedCoordinate_mem_chartGenericPointSubalgebra
#print axioms Stafford38.Geometry.ActualChartValuationImage.exists_actual_normalizedProjectiveColumn
#print axioms Stafford38.Geometry.SelectedResidueCoefficientLocalization.chartSubalgebraToIntegralClosure
#print axioms Stafford38.Geometry.ActualSmoothOpenChartNumerator.exists_actual_normalizedProjectiveColumn_in_integralClosure
