import Stafford38.Geometry.ActualChartValuationImage
import Stafford38.Geometry.ActualSmoothOpenChartNumerator
import Stafford38.Geometry.SelectedResidueNormalizationLocalization

#check Stafford38.Geometry.ActualChartValuationImage.normalizedCoordinate_mem_chartGenericPointSubalgebra
#check Stafford38.Geometry.ActualChartValuationImage.exists_actual_normalizedProjectiveColumn
#check Stafford38.Geometry.SelectedResidueCoefficientLocalization.chartSubalgebraToIntegralClosure
#check Stafford38.Geometry.ActualSmoothOpenChartNumerator.exists_actual_normalizedProjectiveColumn_in_integralClosure
#print axioms Stafford38.Geometry.ActualChartValuationImage.normalizedCoordinate_mem_chartGenericPointSubalgebra
#print axioms Stafford38.Geometry.ActualChartValuationImage.exists_actual_normalizedProjectiveColumn
#print axioms Stafford38.Geometry.SelectedResidueCoefficientLocalization.chartSubalgebraToIntegralClosure
#print axioms Stafford38.Geometry.ActualSmoothOpenChartNumerator.exists_actual_normalizedProjectiveColumn_in_integralClosure
