import Stafford38.Geometry.ActualPointAxisLift

#check Stafford38.Geometry.ActualPointAxisLift.exists_actual_point_axis_lift
#print axioms Stafford38.Geometry.ActualPointAxisLift.exists_actual_point_axis_lift
