module
public import Stafford38.Geometry.ActualNormalizationCenterResidueKernel

@[expose] public section

#print axioms Stafford38.Geometry.ActualNormalizationCenterResidueKernel.residue_kernel_eq_canonical_center_comap
