module
public import Stafford38.Geometry.DVRUniformizerNumerator

@[expose] public section

#check Stafford38.Geometry.DVRUniformizerNumerator.exists_numerator_of_dvr_localization
#print axioms Stafford38.Geometry.DVRUniformizerNumerator.exists_numerator_of_dvr_localization
