module
public import Stafford38.Geometry.GeneralTangentLimitCriterion

@[expose] public section

#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.exists_axis_laurent_smooth_conormal_direction_with_fibre_closure
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.exists_axis_laurent_smooth_conormal_direction
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.tangent_limit_criterion_of_directSummand_with_fibre_closure
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.tangent_limit_criterion_of_directSummand
#check Stafford38.Geometry.GeneralTangentLimitCriterion.tangent_limit_criterion_of_directSummand_with_fibre_closure
