import Stafford38.Geometry.PaperRetainedChartWitnessColumns
import Stafford38.Geometry.PaperActualDivisorTangent
import Stafford38.Geometry.PaperActualWitnessConormalData
set_option autoImplicit false
#print axioms Stafford38.Geometry.PaperRetainedChartWitnessColumns.columns_of_visible_witness
#print axioms Stafford38.Geometry.PaperActualDivisorTangent.exists_regularizedOneRowConormalData_of_actual_columns
#print axioms Stafford38.Geometry.PaperActualWitnessConormalData.exists_regularizedOneRowConormalData_of_actual_witness
