import Stafford38.Quotient.EulerSurjectivity
import Stafford38.Ore.PairStage
import proofs.weyl_pure_power

/-!
# The Euler-nonnegative generated subring

This file isolates the formal normality argument. Given a coefficient subring
commuting with a Weyl coordinate `x`, the subring generated by the
coefficients, `x`, and `E = x*p` satisfies `x*R ⊆ R*x`.
-/

namespace Stafford38.WeylEulerSubring

noncomputable section

variable {A : Type*} [Ring A]

/-- The subring generated by transverse coefficients, the coordinate, and the
Euler element. In the concrete Weyl tower this is the Euler-nonnegative
subring used by the quotient argument. -/
def eulerSubring (C : Subring A) (x p : A) : Subring A :=
  Subring.closure ((C : Set A) ∪ {x, x * p})

/-- Elements that can cross `x` from right to left while retaining a
cofactor in `R`. -/
def normalAcross (R : Subring A) (x : A) : Subring A where
  carrier := {a | ∃ s : R, x * a = (s : A) * x}
  zero_mem' := ⟨0, by simp⟩
  one_mem' := ⟨1, by simp⟩
  add_mem' := by
    rintro a b ⟨s, hs⟩ ⟨t, ht⟩
    refine ⟨s + t, ?_⟩
    simp only [Subring.coe_add]
    rw [mul_add, hs, ht, add_mul]
  neg_mem' := by
    rintro a ⟨s, hs⟩
    refine ⟨-s, ?_⟩
    simp only [Subring.coe_neg]
    rw [mul_neg, hs, neg_mul]
  mul_mem' := by
    rintro a b ⟨s, hs⟩ ⟨t, ht⟩
    refine ⟨s * t, ?_⟩
    simp only [Subring.coe_mul]
    calc
      x * (a * b) = (x * a) * b := by rw [mul_assoc]
      _ = ((s : A) * x) * b := by rw [hs]
      _ = (s : A) * (x * b) := by rw [mul_assoc]
      _ = (s : A) * ((t : A) * x) := by rw [ht]
      _ = ((s : A) * (t : A)) * x := by rw [mul_assoc]

lemma coefficient_mem_eulerSubring (C : Subring A) (x p : A) (c : C) :
    (c : A) ∈ eulerSubring C x p := by
  apply Subring.subset_closure
  exact Or.inl c.property

lemma coordinate_mem_eulerSubring (C : Subring A) (x p : A) :
    x ∈ eulerSubring C x p := by
  apply Subring.subset_closure
  exact Or.inr (by simp)

lemma euler_mem_eulerSubring (C : Subring A) (x p : A) :
    x * p ∈ eulerSubring C x p := by
  apply Subring.subset_closure
  exact Or.inr (by simp)

/-- One-sided normality of the Euler subring. -/
theorem coordinate_normal_eulerSubring
    (C : Subring A) (x p : A)
    (hweyl : p * x = x * p + 1)
    (hcomm : ∀ c : C, x * (c : A) = (c : A) * x) :
    ∀ r : eulerSubring C x p,
      ∃ s : eulerSubring C x p, x * (r : A) = (s : A) * x := by
  intro r
  have hle : eulerSubring C x p ≤ normalAcross (eulerSubring C x p) x := by
    apply Subring.closure_le.2
    intro a ha
    rcases ha with ha | ha
    · exact ⟨⟨a, coefficient_mem_eulerSubring C x p ⟨a, ha⟩⟩,
        hcomm ⟨a, ha⟩⟩
    · simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
      rcases ha with hx | hE
      · refine ⟨⟨x, coordinate_mem_eulerSubring C x p⟩, ?_⟩
        calc
          x * a = x * x := by rw [hx]
          _ = (x : A) * x := rfl
      · refine ⟨⟨x * p - 1, ?_⟩, ?_⟩
        · exact (eulerSubring C x p).sub_mem
            (euler_mem_eulerSubring C x p)
            (eulerSubring C x p).one_mem
        · calc
            x * a = x * (x * p) := by rw [hE]
            _ = x * (p * x - 1) := by rw [hweyl]; noncomm_ring
            _ = (x * p - 1) * x := by noncomm_ring
  exact hle r.property

/-- If the ambient ring is generated by the coefficient subring and the Weyl
pair, adjoining `p` to the Euler subring still generates the ambient ring. -/
theorem closure_eulerSubring_union_momentum_eq_top
    (C : Subring A) (x p : A)
    (hgenerate : Subring.closure ((C : Set A) ∪ {x, p}) = ⊤) :
    Subring.closure (((eulerSubring C x p : Subring A) : Set A) ∪ {p}) = ⊤ := by
  apply top_unique
  rw [← hgenerate]
  apply Subring.closure_le.2
  intro a ha
  rcases ha with ha | ha
  · apply Subring.subset_closure
    show a ∈ ((eulerSubring C x p : Subring A) : Set A) ∪ {p}
    exact Or.inl (coefficient_mem_eulerSubring C x p ⟨a, ha⟩)
  · simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
    rcases ha with hx | hp
    · apply Subring.subset_closure
      show a ∈ ((eulerSubring C x p : Subring A) : Set A) ∪ {p}
      refine Or.inl ?_
      change a ∈ eulerSubring C x p
      rw [hx]
      exact coordinate_mem_eulerSubring C x p
    · apply Subring.subset_closure
      show a ∈ ((eulerSubring C x p : Subring A) : Set A) ∪ {p}
      exact Or.inr (by simpa only [Set.mem_singleton_iff] using hp)

section RationalEulerPolynomials

variable [Algebra ℚ A]

/-- Rational Euler polynomials lie in the Euler subring whenever the
coefficient subring contains the rational scalars. -/
theorem eulerPolynomialEval_mem_eulerSubring
    (C : Subring A) (x p : A)
    (hscalar : ∀ q : ℚ, algebraMap ℚ A q ∈ C)
    (f : Polynomial ℚ) :
    Stafford.eulerPolynomialEval x p f ∈ eulerSubring C x p := by
  induction f using Polynomial.induction_on' with
  | add f g hf hg =>
      rw [map_add]
      exact (eulerSubring C x p).add_mem hf hg
  | monomial n q =>
      rw [← Polynomial.C_mul_X_pow_eq_monomial, map_mul, map_pow,
        Stafford.eulerPolynomialEval_C,
        Stafford.eulerPolynomialEval_X]
      exact (eulerSubring C x p).mul_mem
        (coefficient_mem_eulerSubring C x p ⟨algebraMap ℚ A q, hscalar q⟩)
        ((eulerSubring C x p).pow_mem
          (euler_mem_eulerSubring C x p) n)

/-- Euler polynomials cross the coordinate with a cofactor that remains in
the Euler subring. -/
theorem coordinate_mul_eulerPolynomial
    (C : Subring A) (x p : A)
    (hweyl : p * x = x * p + 1)
    (hcomm : ∀ c : C, x * (c : A) = (c : A) * x)
    (hscalar : ∀ q : ℚ, algebraMap ℚ A q ∈ C)
    (f : Polynomial ℚ) :
    ∃ s : eulerSubring C x p,
      x * Stafford.eulerPolynomialEval x p f = (s : A) * x := by
  let r : eulerSubring C x p :=
    ⟨Stafford.eulerPolynomialEval x p f,
      eulerPolynomialEval_mem_eulerSubring C x p hscalar f⟩
  exact coordinate_normal_eulerSubring C x p hweyl hcomm r

end RationalEulerPolynomials

section PairStage

open Stafford38.OrePairStage

variable (B : Type*) [Ring B] [Algebra ℚ B]

local instance : Algebra ℚ (Stafford38.OreCoordinateStage.CoordinateStage (B := B)) :=
  coordinateStageAlgebra

local instance : Algebra ℚ (PairStage (B := B)) :=
  pairStageAlgebra

/-- The embedded transverse coefficient ring inside one pair stage. -/
def pairOldSubring : Subring (PairStage (B := B)) :=
  RingHom.range (pairCoefficient (B := B))

/-- The concrete Euler subring of one pair stage. -/
abbrev pairEulerSubring : Subring (PairStage (B := B)) :=
  eulerSubring (pairOldSubring B) pairCoordinate pairMomentum

omit [Algebra ℚ B] in
lemma pairOldSubring_commutes_coordinate (c : pairOldSubring B) :
    pairCoordinate * (c : PairStage (B := B)) =
      (c : PairStage (B := B)) * pairCoordinate := by
  obtain ⟨b, hb⟩ := c.property
  rw [← hb]
  exact pairCoordinate_mul_coefficient b

lemma rational_mem_pairOldSubring (q : ℚ) :
    algebraMap ℚ (PairStage (B := B)) q ∈ pairOldSubring B := by
  refine ⟨algebraMap ℚ B q, ?_⟩
  exact DFunLike.congr_fun
    (pairStageAlgebra_algebraMap (k := ℚ) (B := B)) q |>.symm

/-- Every ordered pair-stage monomial with at least as many coordinates as
momenta belongs to the Euler subring. -/
theorem pairOrderedMonomial_mem_eulerSubring
    (b : B) (a j : ℕ) (hja : j ≤ a) :
    pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ j ∈
      pairEulerSubring B := by
  obtain ⟨f, hf⟩ := Stafford.exists_eulerPolynomial_x_pow_mul_d_pow
    (A := PairStage (B := B)) pairCoordinate pairMomentum
    pairMomentum_mul_coordinate j
  have hb : pairCoefficient b ∈ pairEulerSubring B :=
    coefficient_mem_eulerSubring (pairOldSubring B) pairCoordinate pairMomentum
      ⟨pairCoefficient b, ⟨b, rfl⟩⟩
  have hx : pairCoordinate ^ (a - j) ∈ pairEulerSubring B :=
    (pairEulerSubring B).pow_mem
      (coordinate_mem_eulerSubring (pairOldSubring B)
        pairCoordinate pairMomentum) (a - j)
  have hfmem : Stafford.eulerPolynomialEval pairCoordinate pairMomentum f ∈
      pairEulerSubring B :=
    eulerPolynomialEval_mem_eulerSubring (pairOldSubring B)
      pairCoordinate pairMomentum (rational_mem_pairOldSubring B) f
  have hfactor :
      pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ j =
        pairCoefficient b * pairCoordinate ^ (a - j) *
          Stafford.eulerPolynomialEval pairCoordinate pairMomentum f := by
    rw [hf]
    conv_lhs =>
      rw [show a = (a - j) + j by omega, pow_add]
    noncomm_ring
  rw [hfactor]
  exact (pairEulerSubring B).mul_mem
    ((pairEulerSubring B).mul_mem hb hx) hfmem

set_option maxHeartbeats 800000 in
/-- Every ordered pair-stage monomial with strictly more coordinates than
momenta has a right coordinate factor whose cofactor remains in the Euler
subring. -/
theorem pairOrderedMonomial_eq_eulerSubring_mul_coordinate
    (b : B) (a j : ℕ) (hja : j < a) :
    ∃ U : pairEulerSubring B,
      pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ j =
        (U : PairStage (B := B)) * pairCoordinate := by
  obtain ⟨f, hf⟩ := Stafford.exists_eulerPolynomial_x_pow_mul_d_pow
    (A := PairStage (B := B)) pairCoordinate pairMomentum
    pairMomentum_mul_coordinate j
  obtain ⟨s, hs⟩ := coordinate_mul_eulerPolynomial
    (pairOldSubring B) pairCoordinate pairMomentum
    pairMomentum_mul_coordinate (pairOldSubring_commutes_coordinate B)
    (rational_mem_pairOldSubring B) f
  have hb : pairCoefficient b ∈ pairEulerSubring B :=
    coefficient_mem_eulerSubring (pairOldSubring B) pairCoordinate pairMomentum
      ⟨pairCoefficient b, ⟨b, rfl⟩⟩
  have hx : pairCoordinate ^ (a - j - 1) ∈ pairEulerSubring B :=
    (pairEulerSubring B).pow_mem
      (coordinate_mem_eulerSubring (pairOldSubring B)
        pairCoordinate pairMomentum) (a - j - 1)
  let U : pairEulerSubring B :=
    ⟨pairCoefficient b * pairCoordinate ^ (a - j - 1) * (s : PairStage (B := B)),
      (pairEulerSubring B).mul_mem ((pairEulerSubring B).mul_mem hb hx) s.property⟩
  refine ⟨U, ?_⟩
  change pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ j =
    (pairCoefficient b * pairCoordinate ^ (a - j - 1) *
      (s : PairStage (B := B))) * pairCoordinate
  calc
    pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ j =
        pairCoefficient b * pairCoordinate ^ (a - j - 1) *
          (pairCoordinate * (pairCoordinate ^ j * pairMomentum ^ j)) := by
      have ha : a = (a - j - 1) + 1 + j := by omega
      conv_lhs => rw [ha, pow_add, pow_add]
      simp only [pow_one]
      simp only [mul_assoc]
    _ = pairCoefficient b * pairCoordinate ^ (a - j - 1) *
          (pairCoordinate * Stafford.eulerPolynomialEval
            pairCoordinate pairMomentum f) := by rw [hf]
    _ = pairCoefficient b * pairCoordinate ^ (a - j - 1) *
          ((s : PairStage (B := B)) * pairCoordinate) := by rw [hs]
    _ = (pairCoefficient b * pairCoordinate ^ (a - j - 1) *
          (s : PairStage (B := B))) * pairCoordinate := by
      simp only [mul_assoc]

#print axioms pairOrderedMonomial_mem_eulerSubring
#print axioms pairOrderedMonomial_eq_eulerSubring_mul_coordinate

end PairStage

#print axioms coordinate_normal_eulerSubring
#print axioms closure_eulerSubring_union_momentum_eq_top
#print axioms eulerPolynomialEval_mem_eulerSubring
#print axioms coordinate_mul_eulerPolynomial

end
end Stafford38.WeylEulerSubring
