import AlgebraicAnalysis.Ore.Associativity
import proofs.weyl_pure_power

/-!
# The positive Euler residue in the canonical right ideal

This module fixes the right-ideal orientation of the Euler Bezout identity.
The remaining step for quotient surjectivity is to prove that the displayed
error term has a right factor `x` lying in the Euler-nonnegative subring.
-/

namespace Stafford38.WeylEulerResidue

open Stafford
open AlgebraicAnalysis

noncomputable section

variable {A : Type*} [Ring A]

/-- The literal right ideal generated by `d` and `x^N d`. -/
def canonicalRightIdeal (x d : A) (N : ℕ) : Submodule Aᵐᵒᵖ A :=
  Submodule.span Aᵐᵒᵖ ({d, x ^ N * d} : Set A)

lemma firstGenerator_mem (x d : A) (N : ℕ) :
    d ∈ canonicalRightIdeal x d N := by
  apply Submodule.subset_span
  simp

lemma secondGenerator_mem (x d : A) (N : ℕ) :
    x ^ N * d ∈ canonicalRightIdeal x d N := by
  apply Submodule.subset_span
  simp

/-- Expanding a monic element around the pure momentum power transports the
Euler Bezout identity to an exact positive-residue identity. -/
theorem positiveEulerResidue_identity
    (x p d sigma u v : A) (N : ℕ)
    (hd : d = p ^ N + sigma)
    (hbezout : (p ^ N * x ^ N) * u + (x ^ N * p ^ N) * v = 1) :
    d * (x ^ N * u) + (x ^ N * d) * v =
      1 + ((sigma * x ^ N) * u + (x ^ N * sigma) * v) := by
  rw [hd]
  calc
    (p ^ N + sigma) * (x ^ N * u) +
        (x ^ N * (p ^ N + sigma)) * v =
      ((p ^ N * x ^ N) * u + (x ^ N * p ^ N) * v) +
        ((sigma * x ^ N) * u + (x ^ N * sigma) * v) := by
          noncomm_ring
    _ = 1 + ((sigma * x ^ N) * u + (x ^ N * sigma) * v) := by
      rw [hbezout]

/-- For a Weyl pair and a monic decomposition `d = p^N + sigma`, the explicit
positive Euler residue belongs to the literal right ideal `dA + x^N dA`.
The cofactors come from the ordinary Bezout identity for the two disjoint
Euler products. -/
theorem positiveEulerResidue_mem
    [Algebra ℚ A] (x p d sigma : A) (N : ℕ)
    (hweyl : p * x = x * p + 1)
    (hd : d = p ^ N + sigma) :
    ∃ u v : A,
      1 + ((sigma * x ^ N) * u + (x ^ N * sigma) * v) ∈
        canonicalRightIdeal x d N := by
  obtain ⟨u, v, hbezout⟩ :=
    euler_products_right_bezout_exists x p hweyl N
  refine ⟨u, v, ?_⟩
  have hfirst : d * (x ^ N * u) ∈ canonicalRightIdeal x d N := by
    change MulOpposite.op (x ^ N * u) • d ∈ canonicalRightIdeal x d N
    exact (canonicalRightIdeal x d N).smul_mem _
      (firstGenerator_mem x d N)
  have hsecond : (x ^ N * d) * v ∈ canonicalRightIdeal x d N := by
    change MulOpposite.op v • (x ^ N * d) ∈ canonicalRightIdeal x d N
    exact (canonicalRightIdeal x d N).smul_mem _
      (secondGenerator_mem x d N)
  rw [← positiveEulerResidue_identity x p d sigma u v N hd hbezout]
  exact (canonicalRightIdeal x d N).add_mem hfirst hsecond

/-- The same residue statement with the two cofactors retained explicitly as
rational polynomials in the Euler element `x*p`. -/
theorem positiveEulerResidue_polynomial_mem
    [Algebra ℚ A] (x p d sigma : A) (N : ℕ)
    (hweyl : p * x = x * p + 1)
    (hd : d = p ^ N + sigma) :
    ∃ u v : Polynomial ℚ,
      1 +
          ((sigma * x ^ N) * eulerPolynomialEval x p u +
            (x ^ N * sigma) * eulerPolynomialEval x p v) ∈
        canonicalRightIdeal x d N := by
  obtain ⟨u, v, hbezout⟩ :=
    euler_products_polynomial_right_bezout_exists x p hweyl N
  refine ⟨u, v, ?_⟩
  have hfirst : d * (x ^ N * eulerPolynomialEval x p u) ∈
      canonicalRightIdeal x d N := by
    change MulOpposite.op (x ^ N * eulerPolynomialEval x p u) • d ∈
      canonicalRightIdeal x d N
    exact (canonicalRightIdeal x d N).smul_mem _
      (firstGenerator_mem x d N)
  have hsecond : (x ^ N * d) * eulerPolynomialEval x p v ∈
      canonicalRightIdeal x d N := by
    change MulOpposite.op (eulerPolynomialEval x p v) • (x ^ N * d) ∈
      canonicalRightIdeal x d N
    exact (canonicalRightIdeal x d N).smul_mem _
      (secondGenerator_mem x d N)
  rw [← positiveEulerResidue_identity x p d sigma
    (eulerPolynomialEval x p u) (eulerPolynomialEval x p v) N hd hbezout]
  exact (canonicalRightIdeal x d N).add_mem hfirst hsecond

#print axioms positiveEulerResidue_identity
#print axioms positiveEulerResidue_mem
#print axioms positiveEulerResidue_polynomial_mem

end
end Stafford38.WeylEulerResidue
