import Stafford38.Weyl.EulerRemainder

/-!
# The paper's Euler grading and the concrete Euler subring

The pair-stage PBW monomial `b * x^a * p^c` has Euler weight `a-c` for
`E = x*p`.  The nonnegative part is generated by the nonnegative PBW
monomials, and is exactly the subring generated by the transverse algebra,
`x`, and `E` used by the quotient argument.
-/

namespace Stafford38.PaperEulerGrading

open Stafford
open AlgebraicAnalysis
open Stafford38.OreCoordinateStage
open Stafford38.OrePairStage
open Stafford38.WeylEulerSubring
open Stafford38.WeylEulerRemainder
open Stafford38.WeylEulerResidue
open Stafford38.EulerSurjectivity

noncomputable section

variable (B : Type*) [Ring B] [Algebra ℚ B]

local instance : Algebra ℚ (CoordinateStage (B := B)) :=
  coordinateStageAlgebra

local instance : Algebra ℚ (PairStage (B := B)) :=
  pairStageAlgebra

abbrev eulerElement : PairStage (B := B) :=
  pairCoordinate * pairMomentum

/-- The commutator operator `ad_E`, with the paper's `E = x*p`. -/
def eulerAdjoint (z : PairStage (B := B)) : PairStage (B := B) :=
  eulerElement B * z - z * eulerElement B

omit [Algebra ℚ B] in
lemma eulerElement_mul_coefficient (b : B) :
    eulerElement B * pairCoefficient b = pairCoefficient b * eulerElement B := by
  dsimp [eulerElement]
  calc
    (pairCoordinate * pairMomentum) * pairCoefficient b =
        pairCoordinate * (pairMomentum * pairCoefficient b) := by rw [mul_assoc]
    _ = pairCoordinate * (pairCoefficient b * pairMomentum) := by
      rw [pairMomentum_mul_coefficient]
    _ = (pairCoordinate * pairCoefficient b) * pairMomentum := by
      rw [← mul_assoc]
    _ = (pairCoefficient b * pairCoordinate) * pairMomentum := by
      rw [pairCoordinate_mul_coefficient]
    _ = pairCoefficient b * (pairCoordinate * pairMomentum) := by
      rw [mul_assoc]

omit [Algebra ℚ B] in
lemma eulerAdjoint_coordinate :
    eulerAdjoint B (pairCoordinate (B := B)) = pairCoordinate := by
  dsimp [eulerAdjoint, eulerElement]
  rw [mul_assoc, pairMomentum_mul_coordinate]
  noncomm_ring

omit [Algebra ℚ B] in
lemma eulerAdjoint_momentum :
    eulerAdjoint B (pairMomentum (B := B)) = -pairMomentum := by
  dsimp [eulerAdjoint, eulerElement]
  rw [← mul_assoc, pairMomentum_mul_coordinate]
  noncomm_ring

omit [Algebra ℚ B] in
lemma eulerAdjoint_mul (u v : PairStage (B := B)) :
    eulerAdjoint B (u * v) = eulerAdjoint B u * v + u * eulerAdjoint B v := by
  dsimp [eulerAdjoint]
  noncomm_ring

omit [Algebra ℚ B] in
lemma eulerAdjoint_coordinate_pow (a : ℕ) :
    eulerAdjoint B (pairCoordinate (B := B) ^ a) =
      (a : ℕ) • pairCoordinate ^ a := by
  induction a with
  | zero => simp [eulerAdjoint]
  | succ a ih =>
      rw [pow_succ, eulerAdjoint_mul, ih, eulerAdjoint_coordinate]
      simp only [nsmul_eq_mul, Nat.cast_succ]
      noncomm_ring

set_option maxHeartbeats 800000 in
omit [Algebra ℚ B] in
lemma eulerAdjoint_momentum_pow (c : ℕ) :
    eulerAdjoint B (pairMomentum (B := B) ^ c) =
      -((c : ℕ) • pairMomentum ^ c) := by
  induction c with
  | zero => simp [eulerAdjoint]
  | succ c ih =>
      rw [pow_succ, eulerAdjoint_mul, ih, eulerAdjoint_momentum]
      simp only [nsmul_eq_mul, Nat.cast_succ]
      noncomm_ring

omit [Algebra ℚ B] in
lemma eulerAdjoint_coefficient (b : B) :
    eulerAdjoint B (pairCoefficient b) = 0 := by
  unfold eulerAdjoint
  rw [eulerElement_mul_coefficient]
  simp

set_option maxHeartbeats 800000 in
omit [Algebra ℚ B] in
theorem orderedPBWMonomial_eulerWeight (b : B) (a c : ℕ) :
    eulerAdjoint B
        (pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ c) =
      ((a : ℤ) - c) •
        (pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ c) := by
  rw [eulerAdjoint_mul, eulerAdjoint_mul, eulerAdjoint_coefficient,
    eulerAdjoint_coordinate_pow, eulerAdjoint_momentum_pow]
  simp only [zero_mul, zero_add]
  rw [natCast_sub_natCast_zsmul]
  simp only [mul_smul_comm, smul_mul_assoc, mul_neg]
  abel

/-! The PBW monomials with nonnegative Euler weight give a concrete generating
set for the existing transverse–Euler subring.  Keep the PBW description as a
theorem, so there is only one subring owner. -/

def nonnegativeEulerPBWMonomials : Set (PairStage (B := B)) :=
  {z | ∃ b a c, c ≤ a ∧
    z = pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ c}

/-- Canonical nonnegative Euler part: the existing transverse–Euler subring. -/
abbrev pbwNonnegativeEulerPart : Subring (PairStage (B := B)) :=
  pairEulerSubring B

lemma orderedPBWMonomial_mem_nonnegativeEulerPart
    (b : B) (a c : ℕ) (hca : c ≤ a) :
    pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ c ∈
      pbwNonnegativeEulerPart B := by
  exact pairOrderedMonomial_mem_eulerSubring B b a c hca

theorem pairEulerSubring_eq_closure_nonnegativeEulerPBWMonomials :
    pairEulerSubring B = Subring.closure (nonnegativeEulerPBWMonomials B) := by
  apply le_antisymm
  · change eulerSubring (pairOldSubring B) pairCoordinate pairMomentum ≤ _
    apply Subring.closure_le.2
    intro z hz
    change z ∈ ((pairOldSubring B : Set (PairStage (B := B))) ∪
      {pairCoordinate, pairCoordinate * pairMomentum}) at hz
    simp only [Set.mem_union, Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with hzC | hx | hE
    · obtain ⟨b, rfl⟩ := hzC
      apply Subring.subset_closure
      exact ⟨b, 0, 0, by omega, rfl⟩
    · subst z
      simpa [pairCoordinate, pairCoefficient] using
        (Subring.subset_closure
          (s := nonnegativeEulerPBWMonomials B) ⟨(1 : B), 1, 0, by omega, rfl⟩)
    · subst z
      simpa [pairCoordinate, pairCoefficient] using
        (Subring.subset_closure
          (s := nonnegativeEulerPBWMonomials B) ⟨(1 : B), 1, 1, by omega, rfl⟩)
  · apply Subring.closure_le.2
    rintro z ⟨b, a, c, hca, rfl⟩
    exact pairOrderedMonomial_mem_eulerSubring B b a c hca

omit [Algebra ℚ B] in
theorem pbwNonnegativeEulerPart_eq_transverseEulerSubring :
    pbwNonnegativeEulerPart B = pairEulerSubring B := rfl

/-- Positive PBW Euler weight gives the right-coordinate factor used in the
paper's residue argument. -/
theorem orderedPBWMonomial_positive_eulerFactor
    (b : B) (a c : ℕ) (hca : c < a) :
    ∃ U : pbwNonnegativeEulerPart B,
      pairCoefficient b * pairCoordinate ^ a * pairMomentum ^ c =
        (U : PairStage (B := B)) * pairCoordinate := by
  obtain ⟨U, hU⟩ := pairOrderedMonomial_eq_eulerSubring_mul_coordinate
    B b a c hca
  exact ⟨U, hU⟩

/-! ## The paper Euler part in the quotient-surjectivity argument -/

omit [Algebra ℚ B] in
/-- The generic quotient argument can be stated directly with the paper's
nonnegative PBW Euler part. -/
theorem rightMul_surjective_of_paperEuler_normal
    (I : RightIdeal (PairStage (B := B)))
    (hnormal : ∀ r : pbwNonnegativeEulerPart B,
      ∃ s : pbwNonnegativeEulerPart B,
        pairCoordinate * (r : PairStage (B := B)) = (s : PairStage (B := B)) * pairCoordinate)
    (hE : pairCoordinate * pairMomentum ∈ pbwNonnegativeEulerPart B)
    (hresidue : ∃ U : pbwNonnegativeEulerPart B,
      1 + (U : PairStage (B := B)) * pairCoordinate ∈ I)
    (hgenerate : Subring.closure
      (((pbwNonnegativeEulerPart B : Subring (PairStage (B := B))) :
        Set (PairStage (B := B))) ∪ {pairMomentum}) = ⊤) :
    Function.Surjective (rightMul I pairCoordinate) := by
  exact rightMul_surjective_of_euler_normal I (pbwNonnegativeEulerPart B)
    pairCoordinate pairMomentum hnormal hE hresidue hgenerate

section Presented

open Stafford38.OreIteratedPairStage
open Stafford38.WeylIteratedEquivalence
open Stafford38.WeylPBWMonicBridge

universe u

variable (k : Type u) [Field k] [Algebra ℚ k]

local instance iteratedRatAlgebra :
    (n : ℕ) → Algebra ℚ (IteratedPairStage k n)
  | 0 => by
      change Algebra ℚ k
      infer_instance
  | n + 1 => by
      letI : Algebra ℚ (IteratedPairStage k n) := iteratedRatAlgebra n
      change Algebra ℚ (PairStage (B := IteratedPairStage k n))
      exact pairStageAlgebra

local instance (n : ℕ) : Algebra k (IteratedPairStage k n) :=
  iteratedPairStageAlgebra k n

local instance (n : ℕ) :
    Algebra ℚ (CoordinateStage (B := IteratedPairStage k n)) :=
  coordinateStageAlgebra

local instance (n : ℕ) :
    Algebra ℚ (PairStage (B := IteratedPairStage k n)) :=
  pairStageAlgebra

set_option maxHeartbeats 1000000 in
/-- The original Euler quotient-surjectivity route, now using the explicit
nonnegative PBW Euler part.  The normalized remainder residue is the existing
literal residue theorem; the Euler-subring/PBW dictionary above transports it
into the paper's grading language before the generic quotient argument. -/
theorem presentedCanonicalQuotient_rightMul_coordinate_surjective
    (n N : ℕ) {d : PresentedWeyl k (n + 1)}
    (hd : IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d) :
    Function.Surjective
      (rightMul
        (canonicalRightIdeal (pairCoordinate (B := IteratedPairStage k n))
          (presentedToIterated k (n + 1) d) N)
        (pairCoordinate (B := IteratedPairStage k n))) := by
  let B' := IteratedPairStage k n
  have hR : pbwNonnegativeEulerPart B' = pairEulerSubring B' :=
    pbwNonnegativeEulerPart_eq_transverseEulerSubring B'
  apply rightMul_surjective_of_paperEuler_normal (B := B')
    (I := canonicalRightIdeal (pairCoordinate (B := B'))
      (presentedToIterated k (n + 1) d) N)
  · intro r
    let r' : pairEulerSubring B' := ⟨r.1, by rw [← hR]; exact r.2⟩
    obtain ⟨s, hs⟩ := coordinate_normal_eulerSubring
      (pairOldSubring B') pairCoordinate pairMomentum
      (stageMomentum_mul_coordinate k n)
      (pairOldSubring_commutes_coordinate B') r'
    refine ⟨⟨s.1, ?_⟩, hs⟩
    rw [hR]
    exact s.2
  · rw [hR]
    exact euler_mem_eulerSubring (pairOldSubring B') pairCoordinate pairMomentum
  · obtain ⟨U, hU⟩ := presentedPositiveEulerResidue k n N hd
    refine ⟨⟨U.1, ?_⟩, hU⟩
    change U.1 ∈ pbwNonnegativeEulerPart B'
    rw [hR]
    exact U.2
  · rw [hR]
    exact closure_eulerSubring_union_momentum_eq_top
      (pairOldSubring B') pairCoordinate pairMomentum
      (closure_pairOldSubring_union_coordinate_momentum_eq_top B')

end Presented
end
end Stafford38.PaperEulerGrading
