module
public import AlgebraicAnalysis.DifferentialOperators.Basic
public import AlgebraicAnalysis.Module.BaseLocalizationModuleComparison
public import AlgebraicAnalysis.Module.BaseLocalizedKoszulPositivity
public import AlgebraicAnalysis.Module.EndomorphismKernelSupportOverBase
public import AlgebraicAnalysis.Module.FilteredTwoTermBoundaryExhaustion
public import AlgebraicAnalysis.Module.HyperplaneRestriction
public import AlgebraicAnalysis.Module.LocalizedMinimalSupportAvoidance
public import AlgebraicAnalysis.Module.MinimalSupportExistence
public import AlgebraicAnalysis.Module.MinimalSupportKernelCokernelLengths
public import AlgebraicAnalysis.Module.MonicAnnihilatorFinite
public import AlgebraicAnalysis.Module.PrincipalKoszulFiniteTorsion
public import AlgebraicAnalysis.Module.PrincipalKoszulMinimalSupportPositivity
public import AlgebraicAnalysis.Module.PrincipalKoszulPositivity
public import AlgebraicAnalysis.Module.PrincipalKoszulSupportOverBase
public import AlgebraicAnalysis.Module.SplitLatticePresentation
public import AlgebraicAnalysis.Module.StableTorsionResidualSupport
public import AlgebraicAnalysis.Module.TwoTermPageLength
public import AlgebraicAnalysis.Module.UniformBoundaryVanishing
public import AlgebraicAnalysis.Ore.Associativity
public import AlgebraicAnalysis.Ore.RightPBW
public import AlgebraicAnalysis.RingTheory.TwoGeneratorIdentity
public import Mathlib.RingTheory.FiniteLength
public import Mathlib.RingTheory.Length
public import Solution
public import Stafford38.CanonicalSupportVanishingReduction
public import Stafford38.Characteristic.ArtinianAdaptedBasisExistence
public import Stafford38.Characteristic.ArtinianCoefficientField
public import Stafford38.Characteristic.ArtinianTriangularTrace
public import Stafford38.Characteristic.AssociatedGradedModule
public import Stafford38.Characteristic.BGab001CoefficientFieldTrace
public import Stafford38.Characteristic.BaseRelativePoisson
public import Stafford38.Characteristic.CanonicalCertificate
public import Stafford38.Characteristic.CanonicalFilteredTwoTerm
public import Stafford38.Characteristic.CanonicalGabberInvolutivityInterface
public import Stafford38.Characteristic.CanonicalGradedTangentialEquivalences
public import Stafford38.Characteristic.CanonicalKoszulContradiction
public import Stafford38.Characteristic.CanonicalNormalAxisSupport
public import Stafford38.Characteristic.CanonicalNormalSymbolFiniteness
public import Stafford38.Characteristic.CanonicalOldTangentialFiniteness
public import Stafford38.Characteristic.CanonicalPageEulerInequality
public import Stafford38.Characteristic.CanonicalSupportAvoidanceFromCokernel
public import Stafford38.Characteristic.CanonicalTangentialBoundaryMaps
public import Stafford38.Characteristic.CanonicalTangentialSuccessors
public import Stafford38.Characteristic.CanonicalTangentialSymbolFiniteness
public import Stafford38.Characteristic.CanonicalTangentialTotalAction
public import Stafford38.Characteristic.CanonicalUnitCoordinatePreimage
public import Stafford38.Characteristic.ConcreteSquareZeroTraceData
public import Stafford38.Characteristic.EmptySupportVanishing
public import Stafford38.Characteristic.GabberGlobalAssembly
public import Stafford38.Characteristic.GeometricSupportDescent
public import Stafford38.Characteristic.HomogeneousChart
public import Stafford38.Characteristic.InitialIdeal
public import Stafford38.Characteristic.LinearAction
public import Stafford38.Characteristic.NoncharacteristicMinimalPrime
public import Stafford38.Characteristic.NormalSymbolPolynomial
public import Stafford38.Characteristic.OrderReesTwoJet
public import Stafford38.Characteristic.Polynomial
public import Stafford38.Characteristic.PostScalarExtensionPoisson
public import Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity
public import Stafford38.Characteristic.RightReesArtinianAdapter
public import Stafford38.Characteristic.SpecializedNoncharacteristicEquality
public import Stafford38.Characteristic.SquareZeroTraceData
public import Stafford38.Characteristic.SymplecticCompletion
public import Stafford38.Characteristic.TransposedFilteredModuleSupport
public import Stafford38.EvolutionaryCorollary
public import Stafford38.FixedSourceAssembly
public import Stafford38.FixedSourceChallengeTransport
public import Stafford38.FixedSourceStatement
public import Stafford38.FoundationClosure
public import Stafford38.Geometry.AffineConormalClosure
public import Stafford38.Geometry.AffineConormalSpan
public import Stafford38.Geometry.CanonicalVisibleDivisorFrameProduction
public import Stafford38.Geometry.CoisotropicTranslation
public import Stafford38.Geometry.ComponentProjectiveOrder
public import Stafford38.Geometry.ConormalAxisContradiction
public import Stafford38.Geometry.ConormalPrincipalOpenDensity
public import Stafford38.Geometry.ConormalScalarExtensionVanishing
public import Stafford38.Geometry.DivisorTangentLattice
public import Stafford38.Geometry.DivisorialVisibleFrameCore
public import Stafford38.Geometry.DivisorialVisibleFrameStage2
public import Stafford38.Geometry.DivisorialVisibleFrameStageAssembly
public import Stafford38.Geometry.ExactVisibleDivisorFrameInterface
public import Stafford38.Geometry.FibreConicalVanishingIdeal
public import Stafford38.Geometry.FiniteGradientResidueExtension
public import Stafford38.Geometry.GeneralAsymptoticConormal
public import Stafford38.Geometry.GeneralAsymptoticLaurentAxis
public import Stafford38.Geometry.GeneralCoisotropicCanonicalAdapter
public import Stafford38.Geometry.GeneralCoisotropicExclusion
public import Stafford38.Geometry.GeneralCoisotropicSets
public import Stafford38.Geometry.GeneralCoisotropicSetsTest
public import Stafford38.Geometry.GeneralComponentConormalContainment
public import Stafford38.Geometry.GeneralConormalAxis
public import Stafford38.Geometry.GeneralConormalContainment
public import Stafford38.Geometry.GeneralConstantCoordinateAxis
public import Stafford38.Geometry.GeneralDivisorialVisibleFrame
public import Stafford38.Geometry.GeneralTangentLimitCriterion
public import Stafford38.Geometry.GeneralTangentLimitCriterionTest
public import Stafford38.Geometry.KaehlerDVRVisibility
public import Stafford38.Geometry.LaurentConormalDirection
public import Stafford38.Geometry.LaurentConormalResidueExtension
public import Stafford38.Geometry.NormalizationHeightOne
public import Stafford38.Geometry.PointwiseConormalContainment
public import Stafford38.Geometry.ProjectiveConormalDehomogenization
public import Stafford38.Geometry.ProjectiveConormalDirections
public import Stafford38.Geometry.ProjectiveDivisorOrderGap
public import Stafford38.Geometry.SmoothAffineConormal
public import Stafford38.Geometry.SmoothConormalFibreVanishing
public import Stafford38.LeftHandedCorollary
public import Stafford38.LocalizationCorollaries
public import Stafford38.LocalizedDifferentialCorollaries
public import Stafford38.NoncharacteristicHyperplane
public import Stafford38.NoncharacteristicHypersurface
public import Stafford38.Ore.CoordinateStage
public import Stafford38.PaperInputs
public import Stafford38.Quotient.EulerSurjectivity
public import Stafford38.Statement
public import Stafford38.TorsionCyclicity
public import Stafford38.UniversalAssembly
public import Stafford38.Weyl.Domain
public import Stafford38.Weyl.EulerProductIdentities
public import Stafford38.Weyl.EulerRemainder
public import Stafford38.Weyl.EulerResidue
public import Stafford38.Weyl.EulerSubring
public import Stafford38.Weyl.FilteredScalarLifting
public import Stafford38.Weyl.Filtration
public import Stafford38.Weyl.GradedAlgebra
public import Stafford38.Weyl.IteratedEquivalence
public import Stafford38.Weyl.MonicNormalization
public import Stafford38.Weyl.OuterOreMonic
public import Stafford38.Weyl.PBWMonicBridge
public import Stafford38.Weyl.PresentedScalarExtension
public import Stafford38.Weyl.QuotientTransport
public import Stafford38.Weyl.SymbolCompatibility
public import Stafford38.Weyl.Symplectic
public import proofs.weyl_pure_power
public import tests.TorsionCyclicityConsumer

@[expose] public section

#check AlgebraicAnalysis.BaseLocalizationModuleComparison.localizedModuleComparison
#print axioms AlgebraicAnalysis.BaseLocalizationModuleComparison.localizedModuleComparison
#check AlgebraicAnalysis.BaseLocalizedKoszulPositivity.localized_length_cokernel_gt_kernel
#print axioms AlgebraicAnalysis.BaseLocalizedKoszulPositivity.localized_length_cokernel_gt_kernel
#check AlgebraicAnalysis.DifferentialOperators.algebra
#print axioms AlgebraicAnalysis.DifferentialOperators.algebra
#check AlgebraicAnalysis.FilteredTwoTermPages.FilteredTwoTerm.totalBoundaryMap_eventually_zero
#print axioms AlgebraicAnalysis.FilteredTwoTermPages.FilteredTwoTerm.totalBoundaryMap_eventually_zero
#check AlgebraicAnalysis.HyperplaneRestriction.support_disjoint_zeroLocus_of_restriction_subsingleton
#print axioms AlgebraicAnalysis.HyperplaneRestriction.support_disjoint_zeroLocus_of_restriction_subsingleton
#check AlgebraicAnalysis.LocalizedMinimalSupportAvoidance.localized_minimalPrime_avoids
#print axioms AlgebraicAnalysis.LocalizedMinimalSupportAvoidance.localized_minimalPrime_avoids
#check AlgebraicAnalysis.MinimalSupportExistence.exists_minimal_support_prime
#print axioms AlgebraicAnalysis.MinimalSupportExistence.exists_minimal_support_prime
#check AlgebraicAnalysis.MonicAnnihilatorFinite.finite_of_monic_annihilator
#print axioms AlgebraicAnalysis.MonicAnnihilatorFinite.finite_of_monic_annihilator
#check AlgebraicAnalysis.OreAssociativity.normalFormAddEquiv
#print axioms AlgebraicAnalysis.OreAssociativity.normalFormAddEquiv
#check AlgebraicAnalysis.OreAssociativity.normalForm_monomial
#print axioms AlgebraicAnalysis.OreAssociativity.normalForm_monomial
#check AlgebraicAnalysis.OreRightPBW.rightOrePBWBasis
#print axioms AlgebraicAnalysis.OreRightPBW.rightOrePBWBasis
#check AlgebraicAnalysis.PrincipalKoszulFiniteTorsion.length_cokernel_gt_kernel_of_stable_power_and_nonzero
#print axioms AlgebraicAnalysis.PrincipalKoszulFiniteTorsion.length_cokernel_gt_kernel_of_stable_power_and_nonzero
#check AlgebraicAnalysis.PrincipalKoszulMinimalSupportPositivity.length_cokernel_gt_kernel_of_minimal_support
#print axioms AlgebraicAnalysis.PrincipalKoszulMinimalSupportPositivity.length_cokernel_gt_kernel_of_minimal_support
#check AlgebraicAnalysis.PrincipalKoszulPositivity.length_cokernel_eq_kernel_add_regular_quotient
#print axioms AlgebraicAnalysis.PrincipalKoszulPositivity.length_cokernel_eq_kernel_add_regular_quotient
#check AlgebraicAnalysis.PrincipalKoszulSupportOverBase.length_cokernel_gt_kernel_of_support_over_base
#print axioms AlgebraicAnalysis.PrincipalKoszulSupportOverBase.length_cokernel_gt_kernel_of_support_over_base
#check AlgebraicAnalysis.SplitLatticePresentation.exists_splitMatrixPresentation_of_isComplemented
#print axioms AlgebraicAnalysis.SplitLatticePresentation.exists_splitMatrixPresentation_of_isComplemented
#check AlgebraicAnalysis.StableTorsionResidualSupport.residual_nontrivial_of_support
#print axioms AlgebraicAnalysis.StableTorsionResidualSupport.residual_nontrivial_of_support
#check AlgebraicAnalysis.TwoGeneratorIdentity
#print axioms AlgebraicAnalysis.TwoGeneratorIdentity
#check AlgebraicAnalysis.TwoTermPageLength.twoTermPage_length_target_le_source
#print axioms AlgebraicAnalysis.TwoTermPageLength.twoTermPage_length_target_le_source
#check AlgebraicAnalysis.endomorphism_kernel_support_subset_cokernel_support_over_base
#print axioms AlgebraicAnalysis.endomorphism_kernel_support_subset_cokernel_support_over_base
#check AlgebraicAnalysis.exists_uniform_subsingleton_localized
#print axioms AlgebraicAnalysis.exists_uniform_subsingleton_localized
#check AlgebraicAnalysis.localized_kernel_and_cokernel_isFiniteLength
#print axioms AlgebraicAnalysis.localized_kernel_and_cokernel_isFiniteLength
#check IsFiniteLength
#print axioms IsFiniteLength
#check Module.length
#print axioms Module.length
#check Stafford.eulerPolynomialEval
#print axioms Stafford.eulerPolynomialEval
#check Stafford.euler_products_polynomial_right_bezout_exists
#print axioms Stafford.euler_products_polynomial_right_bezout_exists
#check Stafford.euler_products_right_bezout_exists
#print axioms Stafford.euler_products_right_bezout_exists
#check Stafford.exists_eulerPolynomial_x_pow_mul_d_pow
#print axioms Stafford.exists_eulerPolynomial_x_pow_mul_d_pow
#check Stafford38.CanonicalSupportVanishingReduction.AlgebraicallyClosedCanonicalSupportVanishing
#print axioms Stafford38.CanonicalSupportVanishingReduction.AlgebraicallyClosedCanonicalSupportVanishing
#check Stafford38.CanonicalSupportVanishingReduction.CanonicalSupportDescent
#print axioms Stafford38.CanonicalSupportVanishingReduction.CanonicalSupportDescent
#check Stafford38.CanonicalUnitCoordinatePreimage.StrictUnitCoordinatePreimage
#print axioms Stafford38.CanonicalUnitCoordinatePreimage.StrictUnitCoordinatePreimage
#check Stafford38.Characteristic.ArtinianAdaptedBasisExistence.exists_maximalIdealFiltrationAdaptedBasis
#print axioms Stafford38.Characteristic.ArtinianAdaptedBasisExistence.exists_maximalIdealFiltrationAdaptedBasis
#check Stafford38.Characteristic.ArtinianCoefficientField.exists_residue_section
#print axioms Stafford38.Characteristic.ArtinianCoefficientField.exists_residue_section
#check Stafford38.Characteristic.ArtinianTriangularTrace.scalar_eq_zero_of_trace_identity
#print axioms Stafford38.Characteristic.ArtinianTriangularTrace.scalar_eq_zero_of_trace_identity
#check Stafford38.Characteristic.BGab001CoefficientFieldTrace.actual_commutator_cofactor_trace_eq_zero
#print axioms Stafford38.Characteristic.BGab001CoefficientFieldTrace.actual_commutator_cofactor_trace_eq_zero
#check Stafford38.Characteristic.BGab001CoefficientFieldTrace.artinian_local_cofactor_mem_maximalIdeal
#print axioms Stafford38.Characteristic.BGab001CoefficientFieldTrace.artinian_local_cofactor_mem_maximalIdeal
#check Stafford38.Characteristic.BaseRelativePoisson.IsBaseRelativePoisson
#print axioms Stafford38.Characteristic.BaseRelativePoisson.IsBaseRelativePoisson
#check Stafford38.Characteristic.BaseRelativePoisson.zeroSection_stable_under_differential_translation_of_isBaseRelativePoisson
#print axioms Stafford38.Characteristic.BaseRelativePoisson.zeroSection_stable_under_differential_translation_of_isBaseRelativePoisson
#check Stafford38.Characteristic.CanonicalFilteredTwoTerm.canonicalFilteredTwoTerm
#print axioms Stafford38.Characteristic.CanonicalFilteredTwoTerm.canonicalFilteredTwoTerm
#check Stafford38.Characteristic.CanonicalFilteredTwoTerm.canonicalFilteredTwoTerm_f_surjective
#print axioms Stafford38.Characteristic.CanonicalFilteredTwoTerm.canonicalFilteredTwoTerm_f_surjective
#check Stafford38.Characteristic.CanonicalGabberInvolutivityInterface.WeylAssociatedGradedRadicalInvolutivity
#print axioms Stafford38.Characteristic.CanonicalGabberInvolutivityInterface.WeylAssociatedGradedRadicalInvolutivity
#check Stafford38.Characteristic.CanonicalGabberInvolutivityInterface.rightWeylMinimalPrimeInvolutivity_of_radical
#print axioms Stafford38.Characteristic.CanonicalGabberInvolutivityInterface.rightWeylMinimalPrimeInvolutivity_of_radical
#check Stafford38.Characteristic.CanonicalGabberInvolutivityInterface.weylOrderInitialRadicalInvolutivity_iff_associatedGraded
#print axioms Stafford38.Characteristic.CanonicalGabberInvolutivityInterface.weylOrderInitialRadicalInvolutivity_iff_associatedGraded
#check Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.Graded
#print axioms Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.Graded
#check Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.T
#print axioms Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.T
#check Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.firstSourceGradedKernelEquiv
#print axioms Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.firstSourceGradedKernelEquiv
#check Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.firstTargetGradedCokernelEquiv
#print axioms Stafford38.Characteristic.CanonicalGradedTangentialEquivalences.firstTargetGradedCokernelEquiv
#check Stafford38.Characteristic.CanonicalKoszulContradiction.canonical_support_avoidance
#print axioms Stafford38.Characteristic.CanonicalKoszulContradiction.canonical_support_avoidance
#check Stafford38.Characteristic.CanonicalKoszulContradiction.coordinate_cokernel_subsingleton
#print axioms Stafford38.Characteristic.CanonicalKoszulContradiction.coordinate_cokernel_subsingleton
#check Stafford38.Characteristic.CanonicalKoszulContradiction.coordinate_quotSMulTop_subsingleton
#print axioms Stafford38.Characteristic.CanonicalKoszulContradiction.coordinate_quotSMulTop_subsingleton
#check Stafford38.Characteristic.CanonicalKoszulContradiction.no_minimal_coordinate_cokernel_support
#print axioms Stafford38.Characteristic.CanonicalKoszulContradiction.no_minimal_coordinate_cokernel_support
#check Stafford38.Characteristic.CanonicalNormalAxisSupport.no_canonicalSupport_prime_on_punctured_normal_axis
#print axioms Stafford38.Characteristic.CanonicalNormalAxisSupport.no_canonicalSupport_prime_on_punctured_normal_axis
#check Stafford38.Characteristic.CanonicalNormalSymbolFiniteness.canonical_orderAssociatedGradedModule_finite_normalCoeffRing
#print axioms Stafford38.Characteristic.CanonicalNormalSymbolFiniteness.canonical_orderAssociatedGradedModule_finite_normalCoeffRing
#check Stafford38.Characteristic.CanonicalOldTangentialFiniteness.canonical_finite_old_coordinate_kernel_cokernel
#print axioms Stafford38.Characteristic.CanonicalOldTangentialFiniteness.canonical_finite_old_coordinate_kernel_cokernel
#check Stafford38.Characteristic.CanonicalOldTangentialFiniteness.oldCoordinateMap
#print axioms Stafford38.Characteristic.CanonicalOldTangentialFiniteness.oldCoordinateMap
#check Stafford38.Characteristic.CanonicalPageEulerInequality.canonicalPage_length_target_le_source
#print axioms Stafford38.Characteristic.CanonicalPageEulerInequality.canonicalPage_length_target_le_source
#check Stafford38.Characteristic.CanonicalSupportAvoidanceFromCokernel.canonical_support_avoidance_of_coordinate_cokernel_subsingleton
#print axioms Stafford38.Characteristic.CanonicalSupportAvoidanceFromCokernel.canonical_support_avoidance_of_coordinate_cokernel_subsingleton
#check Stafford38.Characteristic.CanonicalTangentialSymbolFiniteness.canonical_orderAssociatedGradedModule_finite_tangential_coordinate
#print axioms Stafford38.Characteristic.CanonicalTangentialSymbolFiniteness.canonical_orderAssociatedGradedModule_finite_tangential_coordinate
#check Stafford38.Characteristic.CanonicalTangentialTotalAction.generator_commutator_lowers
#print axioms Stafford38.Characteristic.CanonicalTangentialTotalAction.generator_commutator_lowers
#check Stafford38.Characteristic.CanonicalTangentialTotalAction.tangentialBoundaryMap_eventually_zero
#print axioms Stafford38.Characteristic.CanonicalTangentialTotalAction.tangentialBoundaryMap_eventually_zero
#check Stafford38.Characteristic.CanonicalTangentialTotalAction.tangentialSourceSuccEquiv
#print axioms Stafford38.Characteristic.CanonicalTangentialTotalAction.tangentialSourceSuccEquiv
#check Stafford38.Characteristic.GabberGlobalAssembly.associatedGraded_radical_isInvolutive
#print axioms Stafford38.Characteristic.GabberGlobalAssembly.associatedGraded_radical_isInvolutive
#check Stafford38.Characteristic.GabberGlobalAssembly.localized_cofactor_mem
#print axioms Stafford38.Characteristic.GabberGlobalAssembly.localized_cofactor_mem
#check Stafford38.Characteristic.GabberGlobalAssembly.minimalPrime_isInvolutive
#print axioms Stafford38.Characteristic.GabberGlobalAssembly.minimalPrime_isInvolutive
#check Stafford38.Characteristic.GabberGlobalAssembly.weylAssociatedGradedRadicalInvolutivity
#print axioms Stafford38.Characteristic.GabberGlobalAssembly.weylAssociatedGradedRadicalInvolutivity
#check Stafford38.Characteristic.GeometricSupportDescent.map_scalarPolynomialMap_eq_top_iff
#print axioms Stafford38.Characteristic.GeometricSupportDescent.map_scalarPolynomialMap_eq_top_iff
#check Stafford38.Characteristic.IsPoisson
#print axioms Stafford38.Characteristic.IsPoisson
#check Stafford38.Characteristic.NoncharacteristicMinimalPrime.canonical_minimalPrime_mem_of_normalCoordinate_false
#print axioms Stafford38.Characteristic.NoncharacteristicMinimalPrime.canonical_minimalPrime_mem_of_normalCoordinate_false
#check Stafford38.Characteristic.NormalSymbolPolynomial.canonicalNormalPolynomial_monic
#print axioms Stafford38.Characteristic.NormalSymbolPolynomial.canonicalNormalPolynomial_monic
#check Stafford38.Characteristic.NormalSymbolPolynomial.normalSymbolAlgEquiv
#print axioms Stafford38.Characteristic.NormalSymbolPolynomial.normalSymbolAlgEquiv
#check Stafford38.Characteristic.PostScalarExtensionPoisson.IsInvolutive
#print axioms Stafford38.Characteristic.PostScalarExtensionPoisson.IsInvolutive
#check Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity.exists_notMem_mul_mem_radical
#print axioms Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity.exists_notMem_mul_mem_radical
#check Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity.minimalPrimes_isInvolutive_of_radical_isInvolutive
#print axioms Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity.minimalPrimes_isInvolutive_of_radical_isInvolutive
#check Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity.sq_mul_poissonBracket_eq
#print axioms Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity.sq_mul_poissonBracket_eq
#check Stafford38.Characteristic.RightReesArtinianAdapter.LocalizedPreArtinianCore
#print axioms Stafford38.Characteristic.RightReesArtinianAdapter.LocalizedPreArtinianCore
#check Stafford38.Characteristic.RightReesArtinianAdapter.exists_concrete_localizedPreArtinianCore
#print axioms Stafford38.Characteristic.RightReesArtinianAdapter.exists_concrete_localizedPreArtinianCore
#check Stafford38.Characteristic.SquareZeroTraceData.RightSquareZeroTraceData.exists_lifts_commutator_factor
#print axioms Stafford38.Characteristic.SquareZeroTraceData.RightSquareZeroTraceData.exists_lifts_commutator_factor
#check Stafford38.Characteristic.SymbolRing
#print axioms Stafford38.Characteristic.SymbolRing
#check Stafford38.Characteristic.fibreWeight
#print axioms Stafford38.Characteristic.fibreWeight
#check Stafford38.Characteristic.poissonBracket
#print axioms Stafford38.Characteristic.poissonBracket
#check Stafford38.CharacteristicAssociatedGradedModule.OrderAssociatedGradedModule
#print axioms Stafford38.CharacteristicAssociatedGradedModule.OrderAssociatedGradedModule
#check Stafford38.CharacteristicAssociatedGradedModule.annihilator_orderAssociatedGradedModule
#print axioms Stafford38.CharacteristicAssociatedGradedModule.annihilator_orderAssociatedGradedModule
#check Stafford38.CharacteristicCanonicalCertificate.exists_fixedSource_certificate_of_orderCharacteristicSupport_eq_empty
#print axioms Stafford38.CharacteristicCanonicalCertificate.exists_fixedSource_certificate_of_orderCharacteristicSupport_eq_empty
#check Stafford38.CharacteristicConcreteSquareZeroTraceData.filteredQuotientTwoJetTraceData_bracket
#print axioms Stafford38.CharacteristicConcreteSquareZeroTraceData.filteredQuotientTwoJetTraceData_bracket
#check Stafford38.CharacteristicEmptySupportVanishing.orderInitialIdeal_eq_top_iff_rightQuotient_subsingleton
#print axioms Stafford38.CharacteristicEmptySupportVanishing.orderInitialIdeal_eq_top_iff_rightQuotient_subsingleton
#check Stafford38.CharacteristicEmptySupportVanishing.rightQuotient_subsingleton_of_orderCharacteristicSupport_eq_empty
#print axioms Stafford38.CharacteristicEmptySupportVanishing.rightQuotient_subsingleton_of_orderCharacteristicSupport_eq_empty
#check Stafford38.CharacteristicHomogeneousChart.eval_symbolLinearAlgHom
#print axioms Stafford38.CharacteristicHomogeneousChart.eval_symbolLinearAlgHom
#check Stafford38.CharacteristicHomogeneousChart.exists_eval_ne_zero_of_homogeneous
#print axioms Stafford38.CharacteristicHomogeneousChart.exists_eval_ne_zero_of_homogeneous
#check Stafford38.CharacteristicHomogeneousChart.pureCoefficient_symbolLinearAlgHom
#print axioms Stafford38.CharacteristicHomogeneousChart.pureCoefficient_symbolLinearAlgHom
#check Stafford38.CharacteristicInitialIdeal.canonical_orderCharacteristicSupport_subset_principal_zeroLocus
#print axioms Stafford38.CharacteristicInitialIdeal.canonical_orderCharacteristicSupport_subset_principal_zeroLocus
#check Stafford38.CharacteristicInitialIdeal.canonical_orderPrincipalComponent_isFibreOnly
#print axioms Stafford38.CharacteristicInitialIdeal.canonical_orderPrincipalComponent_isFibreOnly
#check Stafford38.CharacteristicInitialIdeal.canonical_orderPrincipalComponent_mem_initialIdeal
#print axioms Stafford38.CharacteristicInitialIdeal.canonical_orderPrincipalComponent_mem_initialIdeal
#check Stafford38.CharacteristicInitialIdeal.canonical_orderPrincipalComponent_pureMomentumCoefficient
#print axioms Stafford38.CharacteristicInitialIdeal.canonical_orderPrincipalComponent_pureMomentumCoefficient
#check Stafford38.CharacteristicInitialIdeal.orderCharacteristicSupport
#print axioms Stafford38.CharacteristicInitialIdeal.orderCharacteristicSupport
#check Stafford38.CharacteristicInitialIdeal.orderCharacteristicSupport_eq_zeroLocus
#print axioms Stafford38.CharacteristicInitialIdeal.orderCharacteristicSupport_eq_zeroLocus
#check Stafford38.CharacteristicInitialIdeal.orderInitialIdeal
#print axioms Stafford38.CharacteristicInitialIdeal.orderInitialIdeal
#check Stafford38.CharacteristicLinearAction.symbolLinearAlgEquivOfInverse
#print axioms Stafford38.CharacteristicLinearAction.symbolLinearAlgEquivOfInverse
#check Stafford38.CharacteristicLinearAction.symbolLinearAlgHom
#print axioms Stafford38.CharacteristicLinearAction.symbolLinearAlgHom
#check Stafford38.CharacteristicOrderReesTwoJet.OrderReesTwoJet
#print axioms Stafford38.CharacteristicOrderReesTwoJet.OrderReesTwoJet
#check Stafford38.CharacteristicSymplecticCompletion.exists_symplectic_chart_matrices
#print axioms Stafford38.CharacteristicSymplecticCompletion.exists_symplectic_chart_matrices
#check Stafford38.CharacteristicSymplecticCompletion.exists_symplectic_column_eq
#print axioms Stafford38.CharacteristicSymplecticCompletion.exists_symplectic_column_eq
#check Stafford38.CharacteristicSymplecticCompletion.exists_symplectic_mulVec_eq
#print axioms Stafford38.CharacteristicSymplecticCompletion.exists_symplectic_mulVec_eq
#check Stafford38.CharacteristicSymplecticCompletion.phasePairing
#print axioms Stafford38.CharacteristicSymplecticCompletion.phasePairing
#check Stafford38.CharacteristicSymplecticCompletion.symplecticTransvection_mem
#print axioms Stafford38.CharacteristicSymplecticCompletion.symplecticTransvection_mem
#check Stafford38.CharacteristicTransposedFilteredModuleSupport.transposedOrderAssociatedGradedSupport
#print axioms Stafford38.CharacteristicTransposedFilteredModuleSupport.transposedOrderAssociatedGradedSupport
#check Stafford38.CharacteristicTransposedFilteredModuleSupport.transposedOrderAssociatedGradedSupport_eq_preimage
#print axioms Stafford38.CharacteristicTransposedFilteredModuleSupport.transposedOrderAssociatedGradedSupport_eq_preimage
#check Stafford38.EulerSurjectivity.preservers
#print axioms Stafford38.EulerSurjectivity.preservers
#check Stafford38.EulerSurjectivity.rightMul
#print axioms Stafford38.EulerSurjectivity.rightMul
#check Stafford38.EulerSurjectivity.rightMul_surjective_of_euler_normal
#print axioms Stafford38.EulerSurjectivity.rightMul_surjective_of_euler_normal
#check Stafford38.Evolution.evolutionaryCorollary
#print axioms Stafford38.Evolution.evolutionaryCorollary
#check Stafford38.Evolution.tensorEvolutionaryCorollary
#print axioms Stafford38.Evolution.tensorEvolutionaryCorollary
#check Stafford38.FixedSource.IsLinearWeylCoordinate
#print axioms Stafford38.FixedSource.IsLinearWeylCoordinate
#check Stafford38.FixedSource.UniversalFixedSourceStatement
#print axioms Stafford38.FixedSource.UniversalFixedSourceStatement
#check Stafford38.FixedSource.bernsteinDegree
#print axioms Stafford38.FixedSource.bernsteinDegree
#check Stafford38.FixedSource.universalFixedSourceStatement_of_canonicalSupportVanishing
#print axioms Stafford38.FixedSource.universalFixedSourceStatement_of_canonicalSupportVanishing
#check Stafford38.FoundationClosure.canonicalSupportVanishingViaGeneralCoisotropic
#print axioms Stafford38.FoundationClosure.canonicalSupportVanishingViaGeneralCoisotropic
#check Stafford38.Geometry.AffineConormalClosure.equationConormalClosure
#print axioms Stafford38.Geometry.AffineConormalClosure.equationConormalClosure
#check Stafford38.Geometry.AffineConormalSpan.affineConormalSpace
#print axioms Stafford38.Geometry.AffineConormalSpan.affineConormalSpace
#check Stafford38.Geometry.AffineConormalSpan.affineConormal_coordinatePoint_isCommonZero
#print axioms Stafford38.Geometry.AffineConormalSpan.affineConormal_coordinatePoint_isCommonZero
#check Stafford38.Geometry.CanonicalVisibleDivisorFrameProduction.component_kaehler_bridge
#print axioms Stafford38.Geometry.CanonicalVisibleDivisorFrameProduction.component_kaehler_bridge
#check Stafford38.Geometry.CanonicalVisibleDivisorFrameProduction.exists_finiteGradientBoundaryCertificateOver_of_hasVisibleDivisorFrame
#print axioms Stafford38.Geometry.CanonicalVisibleDivisorFrameProduction.exists_finiteGradientBoundaryCertificateOver_of_hasVisibleDivisorFrame
#check Stafford38.Geometry.CoisotropicTranslation.hamiltonIter
#print axioms Stafford38.Geometry.CoisotropicTranslation.hamiltonIter
#check Stafford38.Geometry.CoisotropicTranslation.zeroSection_stable_under_differential_translation
#print axioms Stafford38.Geometry.CoisotropicTranslation.zeroSection_stable_under_differential_translation
#check Stafford38.Geometry.ComponentProjectiveOrder.normalized_denominator_nonunit_of_polynomial_inverse
#print axioms Stafford38.Geometry.ComponentProjectiveOrder.normalized_denominator_nonunit_of_polynomial_inverse
#check Stafford38.Geometry.ConormalAxisContradiction.canonical_orderPrincipalComponent_eval_pureMomentumAxis
#print axioms Stafford38.Geometry.ConormalAxisContradiction.canonical_orderPrincipalComponent_eval_pureMomentumAxis
#check Stafford38.Geometry.ConormalAxisContradiction.canonical_orderPrincipalComponent_isHomogeneous
#print axioms Stafford38.Geometry.ConormalAxisContradiction.canonical_orderPrincipalComponent_isHomogeneous
#check Stafford38.Geometry.ConormalPrincipalOpenDensity.equationConormalClosure_restricted_eq
#print axioms Stafford38.Geometry.ConormalPrincipalOpenDensity.equationConormalClosure_restricted_eq
#check Stafford38.Geometry.ConormalScalarExtensionVanishing.scalarExtension_vanishing
#print axioms Stafford38.Geometry.ConormalScalarExtensionVanishing.scalarExtension_vanishing
#check Stafford38.Geometry.DivisorTangentLattice.VisibleDivisorFrame.exists_maximalIdeal_coefficients
#print axioms Stafford38.Geometry.DivisorTangentLattice.VisibleDivisorFrame.exists_maximalIdeal_coefficients
#check Stafford38.Geometry.DivisorialVisibleFrameStage2.stage2_exists_chart_normalization
#print axioms Stafford38.Geometry.DivisorialVisibleFrameStage2.stage2_exists_chart_normalization
#check Stafford38.Geometry.ExactVisibleDivisorFrameInterface.HasNormalizedCompatibleVisibleFrame
#print axioms Stafford38.Geometry.ExactVisibleDivisorFrameInterface.HasNormalizedCompatibleVisibleFrame
#check Stafford38.Geometry.FibreConicalVanishingIdeal.IsFibreConical
#print axioms Stafford38.Geometry.FibreConicalVanishingIdeal.IsFibreConical
#check Stafford38.Geometry.FibreConicalVanishingIdeal.vanishingIdeal_isHomogeneous_of_isFibreConical
#print axioms Stafford38.Geometry.FibreConicalVanishingIdeal.vanishingIdeal_isHomogeneous_of_isFibreConical
#check Stafford38.Geometry.FiniteGradientResidueExtension.exists_groundConormalAxis_of_finiteGradientBoundaryCertificateOver
#print axioms Stafford38.Geometry.FiniteGradientResidueExtension.exists_groundConormalAxis_of_finiteGradientBoundaryCertificateOver
#check Stafford38.Geometry.GeneralAsymptoticConormal.coordinate_axis_mem_projective_conormal_directions
#print axioms Stafford38.Geometry.GeneralAsymptoticConormal.coordinate_axis_mem_projective_conormal_directions
#check Stafford38.Geometry.GeneralAsymptoticConormal.coordinate_axis_mem_smooth_fibre_closure
#print axioms Stafford38.Geometry.GeneralAsymptoticConormal.coordinate_axis_mem_smooth_fibre_closure
#check Stafford38.Geometry.GeneralAsymptoticLaurentAxis.exists_groundConormalAxis_of_prime_coordinate_avoidance
#print axioms Stafford38.Geometry.GeneralAsymptoticLaurentAxis.exists_groundConormalAxis_of_prime_coordinate_avoidance
#check Stafford38.Geometry.GeneralCoisotropicCanonicalAdapter.algebraicallyClosedCanonicalSupportVanishing_of_generalCoisotropic
#print axioms Stafford38.Geometry.GeneralCoisotropicCanonicalAdapter.algebraicallyClosedCanonicalSupportVanishing_of_generalCoisotropic
#check Stafford38.Geometry.GeneralCoisotropicExclusion.exists_zero_base_coordinate
#print axioms Stafford38.Geometry.GeneralCoisotropicExclusion.exists_zero_base_coordinate
#check Stafford38.Geometry.GeneralCoisotropicSets.baseProjection_eq_zeroLocus_comap
#print axioms Stafford38.Geometry.GeneralCoisotropicSets.baseProjection_eq_zeroLocus_comap
#check Stafford38.Geometry.GeneralCoisotropicSets.exists_zero_base_coordinate_of_isFibreConical
#print axioms Stafford38.Geometry.GeneralCoisotropicSets.exists_zero_base_coordinate_of_isFibreConical
#check Stafford38.Geometry.GeneralCoisotropicSets.smoothConormalClosure_minimalPrime_subset_of_isFibreConical
#print axioms Stafford38.Geometry.GeneralCoisotropicSets.smoothConormalClosure_minimalPrime_subset_of_isFibreConical
#check Stafford38.Geometry.GeneralCoisotropicSetsTest.exact_complex_manuscript_coisotropic_consumer
#print axioms Stafford38.Geometry.GeneralCoisotropicSetsTest.exact_complex_manuscript_coisotropic_consumer
#check Stafford38.Geometry.GeneralCoisotropicSetsTest.zeroSectionIdealOne_not_isPoisson
#print axioms Stafford38.Geometry.GeneralCoisotropicSetsTest.zeroSectionIdealOne_not_isPoisson
#check Stafford38.Geometry.GeneralComponentConormalContainment.equationConormalClosure_minimalPrime_subset_zeroLocus
#print axioms Stafford38.Geometry.GeneralComponentConormalContainment.equationConormalClosure_minimalPrime_subset_zeroLocus
#check Stafford38.Geometry.GeneralComponentConormalContainment.smoothConormalClosure_minimalPrime_subset_zeroLocus
#print axioms Stafford38.Geometry.GeneralComponentConormalContainment.smoothConormalClosure_minimalPrime_subset_zeroLocus
#check Stafford38.Geometry.GeneralConormalAxis.exists_groundConormalAxis_of_minimalPrime_unit_transcendental
#print axioms Stafford38.Geometry.GeneralConormalAxis.exists_groundConormalAxis_of_minimalPrime_unit_transcendental
#check Stafford38.Geometry.GeneralConormalContainment.equationConormalLocus_subset_zeroLocus
#print axioms Stafford38.Geometry.GeneralConormalContainment.equationConormalLocus_subset_zeroLocus
#check Stafford38.Geometry.GeneralConormalContainment.zeroSection_commonZero_of_isHomogeneous
#print axioms Stafford38.Geometry.GeneralConormalContainment.zeroSection_commonZero_of_isHomogeneous
#check Stafford38.Geometry.GeneralConstantCoordinateAxis.exists_constant_coordinate_equation_and_pure_axis
#print axioms Stafford38.Geometry.GeneralConstantCoordinateAxis.exists_constant_coordinate_equation_and_pure_axis
#check Stafford38.Geometry.GeneralDivisorialVisibleFrame.generalDivisorialVisibleFrameExistence
#print axioms Stafford38.Geometry.GeneralDivisorialVisibleFrame.generalDivisorialVisibleFrameExistence
#check Stafford38.Geometry.GeneralTangentLimitCriterion.DirectSummandInput
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.DirectSummandInput
#check Stafford38.Geometry.GeneralTangentLimitCriterion.exists_axis_laurent_smooth_conormal_direction
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.exists_axis_laurent_smooth_conormal_direction
#check Stafford38.Geometry.GeneralTangentLimitCriterion.tangent_limit_criterion_of_directSummand
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.tangent_limit_criterion_of_directSummand
#check Stafford38.Geometry.GeneralTangentLimitCriterionTest.paper_shape_consumer
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterionTest.paper_shape_consumer
#check Stafford38.Geometry.KaehlerDVRVisibility.exists_visibleDivisorFrame_of_kaehler_image
#print axioms Stafford38.Geometry.KaehlerDVRVisibility.exists_visibleDivisorFrame_of_kaehler_image
#check Stafford38.Geometry.KaehlerDVRVisibility.kaehler_span_of_isAlgebraic_adjoin
#print axioms Stafford38.Geometry.KaehlerDVRVisibility.kaehler_span_of_isAlgebraic_adjoin
#check Stafford38.Geometry.LaneC.divisorialVisibleFrameExistence
#print axioms Stafford38.Geometry.LaneC.divisorialVisibleFrameExistence
#check Stafford38.Geometry.LaneC.stage3_exists_height_one_prime_valuation
#print axioms Stafford38.Geometry.LaneC.stage3_exists_height_one_prime_valuation
#check Stafford38.Geometry.LaurentConormalDirection.residue_mem_extensionFibreClosure_of_laurent_generic
#print axioms Stafford38.Geometry.LaurentConormalDirection.residue_mem_extensionFibreClosure_of_laurent_generic
#check Stafford38.Geometry.LaurentConormalResidueExtension.residue_mem_residueExtensionFibreClosure_of_laurent_generic
#print axioms Stafford38.Geometry.LaurentConormalResidueExtension.residue_mem_residueExtensionFibreClosure_of_laurent_generic
#check Stafford38.Geometry.NormalizationHeightOne.exists_height_one_minimal_prime
#print axioms Stafford38.Geometry.NormalizationHeightOne.exists_height_one_minimal_prime
#check Stafford38.Geometry.PointwiseConormalContainment.differentialCombinationPoint_isCommonZero
#print axioms Stafford38.Geometry.PointwiseConormalContainment.differentialCombinationPoint_isCommonZero
#check Stafford38.Geometry.ProjectiveConormalDehomogenization.phasePoint_mem_equationConormalLocus_of_projective_row
#print axioms Stafford38.Geometry.ProjectiveConormalDehomogenization.phasePoint_mem_equationConormalLocus_of_projective_row
#check Stafford38.Geometry.ProjectiveConormalDirections.mk_mem_projectiveHomogeneousClosure_of_fibre_zeroLocus
#print axioms Stafford38.Geometry.ProjectiveConormalDirections.mk_mem_projectiveHomogeneousClosure_of_fibre_zeroLocus
#check Stafford38.Geometry.ProjectiveConormalDirections.projectiveHomogeneousClosure
#print axioms Stafford38.Geometry.ProjectiveConormalDirections.projectiveHomogeneousClosure
#check Stafford38.Geometry.ProjectiveConormalDirections.projectivizedDirectionSet
#print axioms Stafford38.Geometry.ProjectiveConormalDirections.projectivizedDirectionSet
#check Stafford38.Geometry.ProjectiveConormalDirections.smoothConormalDirectionSet
#print axioms Stafford38.Geometry.ProjectiveConormalDirections.smoothConormalDirectionSet
#check Stafford38.Geometry.ProjectiveConormalDirections.smoothConormalFibreProjection
#print axioms Stafford38.Geometry.ProjectiveConormalDirections.smoothConormalFibreProjection
#check Stafford38.Geometry.ProjectiveDivisorOrderGap.exists_uniformizer_strict_orderGap
#print axioms Stafford38.Geometry.ProjectiveDivisorOrderGap.exists_uniformizer_strict_orderGap
#check Stafford38.Geometry.SmoothAffineConormal.SmoothAffinePoint
#print axioms Stafford38.Geometry.SmoothAffineConormal.SmoothAffinePoint
#check Stafford38.Geometry.SmoothAffineConormal.equationConormalClosure_smoothAffine_eq
#print axioms Stafford38.Geometry.SmoothAffineConormal.equationConormalClosure_smoothAffine_eq
#check Stafford38.Geometry.SmoothConormalFibreVanishing.fibreLift_mem_vanishingIdeal_equationConormal
#print axioms Stafford38.Geometry.SmoothConormalFibreVanishing.fibreLift_mem_vanishingIdeal_equationConormal
#check Stafford38.LeftHandedCorollary.leftHanded_of_universalStatement
#print axioms Stafford38.LeftHandedCorollary.leftHanded_of_universalStatement
#check Stafford38.LocalizationCorollaries.s38_rightOreLocalization
#print axioms Stafford38.LocalizationCorollaries.s38_rightOreLocalization
#check Stafford38.LocalizedDifferentialCorollaries.s38_fraction_ring_differential
#print axioms Stafford38.LocalizedDifferentialCorollaries.s38_fraction_ring_differential
#check Stafford38.LocalizedDifferentialCorollaries.s38_laurent_differential
#print axioms Stafford38.LocalizedDifferentialCorollaries.s38_laurent_differential
#check Stafford38.LocalizedDifferentialCorollaries.s38_partial_laurent_differential
#print axioms Stafford38.LocalizedDifferentialCorollaries.s38_partial_laurent_differential
#check Stafford38.LocalizedDifferentialCorollaries.s38_unconditional_localized_differential
#print axioms Stafford38.LocalizedDifferentialCorollaries.s38_unconditional_localized_differential
#check Stafford38.NoncharacteristicHyperplane.IsNoncharacteristic
#print axioms Stafford38.NoncharacteristicHyperplane.IsNoncharacteristic
#check Stafford38.NoncharacteristicHyperplane.canonicalSupport_conormal_subset_zeroSection
#print axioms Stafford38.NoncharacteristicHyperplane.canonicalSupport_conormal_subset_zeroSection
#check Stafford38.NoncharacteristicHyperplane.canonical_finite_restrictedCoordinateQuotient
#print axioms Stafford38.NoncharacteristicHyperplane.canonical_finite_restrictedCoordinateQuotient
#check Stafford38.NoncharacteristicHyperplane.canonical_isNoncharacteristic_annihilator
#print axioms Stafford38.NoncharacteristicHyperplane.canonical_isNoncharacteristic_annihilator
#check Stafford38.NoncharacteristicHyperplane.isNoncharacteristic_iff_finite_restrictedCoordinateQuotient
#print axioms Stafford38.NoncharacteristicHyperplane.isNoncharacteristic_iff_finite_restrictedCoordinateQuotient
#check Stafford38.NoncharacteristicHypersurface.canonicalPrincipalHypersurfaceIdeal
#print axioms Stafford38.NoncharacteristicHypersurface.canonicalPrincipalHypersurfaceIdeal
#check Stafford38.NoncharacteristicHypersurface.canonical_principal_hypersurface_finite
#print axioms Stafford38.NoncharacteristicHypersurface.canonical_principal_hypersurface_finite
#check Stafford38.NoncharacteristicHypersurface.normalMomentumPolynomialEquiv_tangentialMap
#print axioms Stafford38.NoncharacteristicHypersurface.normalMomentumPolynomialEquiv_tangentialMap
#check Stafford38.OreCoordinateStage.coordinateDerivation
#print axioms Stafford38.OreCoordinateStage.coordinateDerivation
#check Stafford38.PaperInputs.CanonicalNoncharacteristicSupportAvoidance
#print axioms Stafford38.PaperInputs.CanonicalNoncharacteristicSupportAvoidance
#check Stafford38.SpecializedNoncharacteristicEquality.strictUnitCoordinatePreimage_of_transposedSupport_disjoint_axis
#print axioms Stafford38.SpecializedNoncharacteristicEquality.strictUnitCoordinatePreimage_of_transposedSupport_disjoint_axis
#check Stafford38.SpecializedNoncharacteristicEquality.transposedSupport_disjoint_axis_iff
#print axioms Stafford38.SpecializedNoncharacteristicEquality.transposedSupport_disjoint_axis_iff
#check Stafford38.TorsionCyclicity.IsRightTorsion
#print axioms Stafford38.TorsionCyclicity.IsRightTorsion
#check Stafford38.TorsionCyclicity.exists_span_singleton_eq_span_pair
#print axioms Stafford38.TorsionCyclicity.exists_span_singleton_eq_span_pair
#check Stafford38.TorsionCyclicity.weyl_isCyclic_of_isRightTorsion
#print axioms Stafford38.TorsionCyclicity.weyl_isCyclic_of_isRightTorsion
#check Stafford38.UniversalAssembly.CanonicalSupportVanishing
#print axioms Stafford38.UniversalAssembly.CanonicalSupportVanishing
#check Stafford38.UniversalAssembly.universalStatement_of_canonicalSupportVanishing
#print axioms Stafford38.UniversalAssembly.universalStatement_of_canonicalSupportVanishing
#check Stafford38.UniversalStatement
#print axioms Stafford38.UniversalStatement
#check Stafford38.Weyl.EulerProductIdentities.eval_fallingEulerProduct
#print axioms Stafford38.Weyl.EulerProductIdentities.eval_fallingEulerProduct
#check Stafford38.Weyl.EulerProductIdentities.eval_risingEulerProduct
#print axioms Stafford38.Weyl.EulerProductIdentities.eval_risingEulerProduct
#check Stafford38.Weyl.FilteredScalarLifting.canonicalSupportDescent
#print axioms Stafford38.Weyl.FilteredScalarLifting.canonicalSupportDescent
#check Stafford38.Weyl.FilteredScalarLifting.filteredInitialLifting
#print axioms Stafford38.Weyl.FilteredScalarLifting.filteredInitialLifting
#check Stafford38.Weyl.FilteredScalarLifting.target_orderInitialIdeal_le_map_source_orderInitialIdeal
#print axioms Stafford38.Weyl.FilteredScalarLifting.target_orderInitialIdeal_le_map_source_orderInitialIdeal
#check Stafford38.Weyl.PresentedScalarExtension.FilteredInitialLifting
#print axioms Stafford38.Weyl.PresentedScalarExtension.FilteredInitialLifting
#check Stafford38.Weyl.PresentedScalarExtension.canonicalSupportDescent_of_filteredInitialLifting
#print axioms Stafford38.Weyl.PresentedScalarExtension.canonicalSupportDescent_of_filteredInitialLifting
#check Stafford38.Weyl.PresentedScalarExtension.presentedWeylScalarExtension_isPBWMonicAt
#print axioms Stafford38.Weyl.PresentedScalarExtension.presentedWeylScalarExtension_isPBWMonicAt
#check Stafford38.Weyl.PresentedScalarExtension.presentedWeylScalarExtension_map_orderInitialIdeal_le
#print axioms Stafford38.Weyl.PresentedScalarExtension.presentedWeylScalarExtension_map_orderInitialIdeal_le
#check Stafford38.WeylAlg
#print axioms Stafford38.WeylAlg
#check Stafford38.WeylAssociatedGraded.presentedAssociatedGradedAlgEquiv
#print axioms Stafford38.WeylAssociatedGraded.presentedAssociatedGradedAlgEquiv
#check Stafford38.WeylAssociatedGraded.presentedAssociatedGradedMk_mul_bernstein
#print axioms Stafford38.WeylAssociatedGraded.presentedAssociatedGradedMk_mul_bernstein
#check Stafford38.WeylAssociatedGraded.presentedAssociatedGradedMk_mul_order
#print axioms Stafford38.WeylAssociatedGraded.presentedAssociatedGradedMk_mul_order
#check Stafford38.WeylDomain.mul_ne_zero
#print axioms Stafford38.WeylDomain.mul_ne_zero
#check Stafford38.WeylEulerRemainder.HasPositiveCoordinateFactor
#print axioms Stafford38.WeylEulerRemainder.HasPositiveCoordinateFactor
#check Stafford38.WeylEulerRemainder.closure_pairOldSubring_union_coordinate_momentum_eq_top
#print axioms Stafford38.WeylEulerRemainder.closure_pairOldSubring_union_coordinate_momentum_eq_top
#check Stafford38.WeylEulerRemainder.pairOrderedMonomial_hasPositiveCoordinateFactor
#print axioms Stafford38.WeylEulerRemainder.pairOrderedMonomial_hasPositiveCoordinateFactor
#check Stafford38.WeylEulerRemainder.positiveEulerResidue_eq_eulerSubring_mul_coordinate
#print axioms Stafford38.WeylEulerRemainder.positiveEulerResidue_eq_eulerSubring_mul_coordinate
#check Stafford38.WeylEulerRemainder.presentedCanonicalQuotient_rightMul_coordinate_surjective
#print axioms Stafford38.WeylEulerRemainder.presentedCanonicalQuotient_rightMul_coordinate_surjective
#check Stafford38.WeylEulerRemainder.presentedPositiveEulerResidue
#print axioms Stafford38.WeylEulerRemainder.presentedPositiveEulerResidue
#check Stafford38.WeylEulerResidue.canonicalRightIdeal
#print axioms Stafford38.WeylEulerResidue.canonicalRightIdeal
#check Stafford38.WeylEulerResidue.positiveEulerResidue_identity
#print axioms Stafford38.WeylEulerResidue.positiveEulerResidue_identity
#check Stafford38.WeylEulerResidue.positiveEulerResidue_polynomial_mem
#print axioms Stafford38.WeylEulerResidue.positiveEulerResidue_polynomial_mem
#check Stafford38.WeylEulerSubring.closure_eulerSubring_union_momentum_eq_top
#print axioms Stafford38.WeylEulerSubring.closure_eulerSubring_union_momentum_eq_top
#check Stafford38.WeylEulerSubring.coordinate_normal_eulerSubring
#print axioms Stafford38.WeylEulerSubring.coordinate_normal_eulerSubring
#check Stafford38.WeylEulerSubring.eulerSubring
#print axioms Stafford38.WeylEulerSubring.eulerSubring
#check Stafford38.WeylEulerSubring.normalAcross
#print axioms Stafford38.WeylEulerSubring.normalAcross
#check Stafford38.WeylEulerSubring.pairEulerSubring
#print axioms Stafford38.WeylEulerSubring.pairEulerSubring
#check Stafford38.WeylEulerSubring.pairOrderedMonomial_eq_eulerSubring_mul_coordinate
#print axioms Stafford38.WeylEulerSubring.pairOrderedMonomial_eq_eulerSubring_mul_coordinate
#check Stafford38.WeylEulerSubring.pairOrderedMonomial_mem_eulerSubring
#print axioms Stafford38.WeylEulerSubring.pairOrderedMonomial_mem_eulerSubring
#check Stafford38.WeylFiltration.bernsteinPiece
#print axioms Stafford38.WeylFiltration.bernsteinPiece
#check Stafford38.WeylFiltration.orderPiece
#print axioms Stafford38.WeylFiltration.orderPiece
#check Stafford38.WeylFiltration.presentedWeightPiece
#print axioms Stafford38.WeylFiltration.presentedWeightPiece
#check Stafford38.WeylIteratedEquivalence.presentedIteratedEquiv
#print axioms Stafford38.WeylIteratedEquivalence.presentedIteratedEquiv
#check Stafford38.WeylMonicNormalization.HasNormalizedSymplecticChart
#print axioms Stafford38.WeylMonicNormalization.HasNormalizedSymplecticChart
#check Stafford38.WeylMonicNormalization.eq_algebraMap_of_mem_bernsteinPiece_zero
#print axioms Stafford38.WeylMonicNormalization.eq_algebraMap_of_mem_bernsteinPiece_zero
#check Stafford38.WeylMonicNormalization.exists_normalized_symplectic_image
#print axioms Stafford38.WeylMonicNormalization.exists_normalized_symplectic_image
#check Stafford38.WeylMonicNormalization.scalar_or_normalized_symplectic_image
#print axioms Stafford38.WeylMonicNormalization.scalar_or_normalized_symplectic_image
#check Stafford38.WeylOuterOreMonic.presentedOuterPolynomial
#print axioms Stafford38.WeylOuterOreMonic.presentedOuterPolynomial
#check Stafford38.WeylOuterOreMonic.presentedOuterPolynomial_monic
#print axioms Stafford38.WeylOuterOreMonic.presentedOuterPolynomial_monic
#check Stafford38.WeylPBWMonicBridge.IsPBWMonicAt
#print axioms Stafford38.WeylPBWMonicBridge.IsPBWMonicAt
#check Stafford38.WeylPBWMonicBridge.coeff_principal_pure_eq_normalForm
#print axioms Stafford38.WeylPBWMonicBridge.coeff_principal_pure_eq_normalForm
#check Stafford38.WeylQuotientTransport.presentedCanonicalRightIdeal
#print axioms Stafford38.WeylQuotientTransport.presentedCanonicalRightIdeal
#check Stafford38.WeylQuotientTransport.presentedCanonicalRightQuotient_rightMul_coordinate_surjective
#print axioms Stafford38.WeylQuotientTransport.presentedCanonicalRightQuotient_rightMul_coordinate_surjective
#check Stafford38.WeylSymbolCompatibility.standardSymplecticAlgHom_preserves_bernsteinPiece
#print axioms Stafford38.WeylSymbolCompatibility.standardSymplecticAlgHom_preserves_bernsteinPiece
#check Stafford38.WeylSymbolCompatibility.standardSymplecticAlgHom_principal_compatibility
#print axioms Stafford38.WeylSymbolCompatibility.standardSymplecticAlgHom_principal_compatibility
#check Stafford38.WeylSymplectic.standardSymplecticAlgEquivOfInverse
#print axioms Stafford38.WeylSymplectic.standardSymplecticAlgEquivOfInverse
#check Stafford38.WeylSymplectic.standardSymplecticAlgEquivOfInverse_symm_generator
#print axioms Stafford38.WeylSymplectic.standardSymplecticAlgEquivOfInverse_symm_generator
#check Stafford38.WeylSymplectic.standardSymplecticAlgHom
#print axioms Stafford38.WeylSymplectic.standardSymplecticAlgHom
#check Stafford38.WeylSymplectic.standardSymplecticAlgHom_generator
#print axioms Stafford38.WeylSymplectic.standardSymplecticAlgHom_generator
#check Stafford38.universalFixedSourceStatement
#print axioms Stafford38.universalFixedSourceStatement
#check Stafford38.universalStatement
#print axioms Stafford38.universalStatement
#check Stafford38Challenge.universalStatement
#print axioms Stafford38Challenge.universalStatement
#check Stafford38CorollaryChallenge.torsionCyclicStatement_consumer
#print axioms Stafford38CorollaryChallenge.torsionCyclicStatement_consumer
#check Stafford38FixedSourceChallengeTransport.bernsteinDegree_eq
#print axioms Stafford38FixedSourceChallengeTransport.bernsteinDegree_eq
