module
public import CorollaryChallenge

@[expose] public section

#check Stafford38CorollaryChallenge.IsRightTorsion
#print axioms Stafford38CorollaryChallenge.IsRightTorsion
#check Stafford38CorollaryChallenge.torsionCyclicStatement
#print axioms Stafford38CorollaryChallenge.torsionCyclicStatement
