module
public import FixedSourceChallenge

@[expose] public section

#check Stafford38FixedSourceChallenge.UniversalFixedSourceStatement
#print axioms Stafford38FixedSourceChallenge.UniversalFixedSourceStatement
#check Stafford38FixedSourceChallenge.bernsteinDegree
#print axioms Stafford38FixedSourceChallenge.bernsteinDegree
