module
public import AlgebraicAnalysis.Module.BaseLocalizedKoszulPositivity
public import Stafford38.Characteristic.BaseLocalizationModuleComparison
public import Stafford38.Characteristic.LocalizedKernelCokernelEquivalences
public import Stafford38.Characteristic.MinimalSupportKernelCokernelLengths
public import Stafford38.Characteristic.LocalizedMinimalSupportAvoidance
public import Stafford38.Characteristic.PrincipalKoszulMinimalSupportPositivity

@[expose] public section

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.BaseLocalizedKoszulPositivity

export AlgebraicAnalysis.BaseLocalizedKoszulPositivity (localized_length_cokernel_gt_kernel)

end Stafford38.Characteristic.BaseLocalizedKoszulPositivity
