module
public import AlgebraicAnalysis.Module.BaseLocalizationModuleComparison

@[expose] public section

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.BaseLocalizationModuleComparison

export AlgebraicAnalysis.BaseLocalizationModuleComparison (coefficientDenominator localizedModule_isLocalizedOverBase localizedModule_isLocalizedOverCoefficient localizedModuleComparison localizedModuleComparison_mkLinearMap localizedModuleComparison_mk localizedModuleComparison_natural)

end Stafford38.Characteristic.BaseLocalizationModuleComparison
