import Stafford38.CanonicalSupportVanishingReduction
import Stafford38.Geometry.ScalarExtensionPoints

/-!
# Concrete inputs for canonical Laurent symbol control

The terminal Laurent contradiction asks for a fibre polynomial whose lift is
the canonical order symbol and which vanishes on the scalar-extended equation
conormal locus.  The only remaining input for that statement is base-relative
Poisson closure of the geometric reduced support.  In particular, this file
proves directly that conormals generated by the scalar extension of the
*ground* base contraction lie in geometric support; no unproved equality with
the post-extension base contraction is needed.
-/

namespace Stafford38.Characteristic.CanonicalLaurentSymbolControl

open Stafford38
open Stafford38.CanonicalSupportVanishingReduction
open Stafford38.Characteristic
open Stafford38.Characteristic.BaseRelativePoisson
open Stafford38.Characteristic.BaseZeroSection
open Stafford38.Characteristic.ReducedSupportIdeal
open Stafford38.CharacteristicFilteredQuotient
open Stafford38.CharacteristicInitialIdeal
open Stafford38.CharacteristicInitialIdealHomogeneous
open Stafford38.EulerSurjectivity
open Stafford38.Geometry.AffineConormalClosure
open Stafford38.Geometry.AffineConormalSpan
open Stafford38.Geometry.CoisotropicTranslation
open Stafford38.Geometry.LaurentConormalDirection
open Stafford38.Geometry.ScalarExtensionPoints
open Stafford38.WeylEulerResidue
open Stafford38.WeylIteratedEquivalence
open Stafford38.WeylLeadingSymbol
open Stafford38.WeylPBWMonicBridge

noncomputable section

universe u

variable {k : Type u} [Field k] {n : ℕ}

/-- A phase polynomial supported only on fibre variables comes from a fibre
polynomial by the canonical fibre inclusion. -/
theorem exists_fibreLift_eq_of_isFibreOnly
    (Q : SymbolRing k n) (hQ : IsFibreOnly k Q) :
    ∃ P : MvPolynomial (Fin n) k, fibreLift P = Q := by
  apply MvPolynomial.exists_rename_eq_of_vars_subset_range Q Sum.inr
    Sum.inr_injective
  intro i hi
  change i ∈ Q.vars at hi
  rw [MvPolynomial.mem_vars] at hi
  rcases hi with ⟨m, hm, him⟩
  have hcoeff : MvPolynomial.coeff m Q ≠ 0 :=
    MvPolynomial.mem_support_iff.mp hm
  rcases i with i | i
  · have hzero := hQ m hcoeff i
    exact (Finsupp.mem_support_iff.mp him hzero).elim
  · exact ⟨i, rfl⟩

/-- The canonical order symbol has a literal fibre-polynomial preimage. -/
theorem exists_canonical_fibrePolynomial
    (n N : ℕ) {d : PresentedWeyl k (n + 1)}
    (hd : IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d) :
    ∃ P : MvPolynomial (Fin (n + 1)) k,
      fibreLift P =
        presentedPrincipalComponent k
          (@Stafford38.WeylFiltration.orderWeight (n + 1)) N d :=
  exists_fibreLift_eq_of_isFibreOnly
    (presentedPrincipalComponent k
      (@Stafford38.WeylFiltration.orderWeight (n + 1)) N d)
    (canonical_orderPrincipalComponent_isFibreOnly k n N hd)

private abbrev orderDecompositionGroundExtension :=
  MvPolynomial.weightedHomogeneousSubmodule k
    (@Stafford38.WeylFiltration.orderWeight n)

local instance orderGradedAlgebraGroundExtensionInstance :
    GradedAlgebra (orderDecompositionGroundExtension (k := k) (n := n)) :=
  MvPolynomial.weightedGradedAlgebra k
    (@Stafford38.WeylFiltration.orderWeight n)

/-- A geometric zero of the scalar extension of the ground base contraction
lifts to the zero section of the geometric reduced support.  This avoids any
claim that scalar extension commutes with the whole base contraction. -/
theorem zeroSection_mem_geometricReducedSupport_of_groundBaseZero
    {K : Type*} [Field K] [Algebra k K]
    (W : RightIdeal (PresentedWeyl k n)) (y : Fin n → K)
    (hy : ∀ f ∈ reducedOrderBaseIdeal k W,
      MvPolynomial.eval₂ (algebraMap k K) y f = 0) :
    zeroSectionPoint y ∈ MvPolynomial.zeroLocus K
      (geometricReducedOrderSupportIdeal (k := k) (K := K) W) := by
  rw [mem_zeroLocus_geometricReducedOrderSupportIdeal_iff]
  intro P hP
  obtain ⟨m, hm⟩ := (mem_reducedOrderSupportIdeal_iff k W P).mp hP
  let f := fibreZeroSpecialization k (P ^ m)
  have hcomponent :
      (DirectSum.decompose
          (orderDecompositionGroundExtension (k := k) (n := n)) (P ^ m) 0 :
        SymbolRing k n) ∈ orderInitialIdeal k W :=
    coe_mem_orderInitialIdeal_of_mem_orderSymbolRelation k W 0
      (DirectSum.decompose
        (orderDecompositionGroundExtension (k := k) (n := n)) (P ^ m) 0)
      (decompose_mem_orderSymbolRelation_of_mem_orderInitialIdeal
        k W (P ^ m) hm 0)
  have hbaseLift : baseLift f ∈ reducedOrderSupportIdeal k W := by
    rw [← zeroComponent_eq_baseLift_fibreZeroSpecialization]
    exact orderInitialIdeal_le_reducedOrderSupportIdeal k W hcomponent
  have hfbase : f ∈ reducedOrderBaseIdeal k W :=
    (mem_reducedOrderBaseIdeal_iff k W f).mpr hbaseLift
  have hfy := hy f hfbase
  have heval :
      MvPolynomial.eval (zeroSectionPoint y)
        ((scalarPolynomialMap (k := k) (K := K) (PhaseVar n) P) ^ m) = 0 := by
    rw [← map_pow,
      ← eval_fibreZeroSpecialization K y
        (scalarPolynomialMap (k := k) (K := K) (PhaseVar n) (P ^ m)),
      ← scalarPolynomialMap_fibreZeroSpecialization]
    simpa only [eval_scalarPolynomialMap] using hfy
  have hp0 :
      MvPolynomial.eval (zeroSectionPoint y)
        (scalarPolynomialMap (k := k) (K := K) (PhaseVar n) P) = 0 := by
    exact (pow_eq_zero_iff'.mp (by simpa only [map_pow] using heval)).1
  simpa [eval_scalarPolynomialMap] using hp0

/-- Under post-extension base-relative Poisson closure, the conormal locus of
the scalar-extended *ground* base contraction already lies in geometric
support.  Equality with the post-extension base contraction is unnecessary. -/
theorem equationConormalLocus_groundMap_subset_geometricReducedSupport
    {K : Type*} [Field K] [Algebra k K] [CharZero K]
    (W : RightIdeal (PresentedWeyl k n))
    (hJ : IsBaseRelativePoisson
      (geometricReducedOrderSupportIdeal (k := k) (K := K) W)) :
    equationConormalLocus
        ((reducedOrderBaseIdeal k W).map
          (scalarPolynomialMap (k := k) (K := K) (Fin n))) ⊆
      MvPolynomial.zeroLocus K
        (geometricReducedOrderSupportIdeal (k := k) (K := K) W) := by
  intro q hq
  let y : Fin n → K := fun i => q (Sum.inl i)
  let xi : Fin n → K := fun i => q (Sum.inr i)
  have hy : ∀ f ∈ reducedOrderBaseIdeal k W,
      MvPolynomial.eval₂ (algebraMap k K) y f = 0 :=
    (mem_equationConormalLocus_map_iff
      (reducedOrderBaseIdeal k W) q).mp hq |>.1
  have hzero :=
    zeroSection_mem_geometricReducedSupport_of_groundBaseZero W y hy
  have hpoint := affineConormal_coordinatePoint_isCommonZero
    (geometricReducedOrderSupportIdeal (k := k) (K := K) W) hJ y hzero
    ((reducedOrderBaseIdeal k W).map
      (scalarPolynomialMap (k := k) (K := K) (Fin n)))
    (fun f ↦ map_baseContraction_le_geometricBaseContraction
      (reducedOrderSupportIdeal k W) f.2)
    xi hq.2
  have hsplit : Sum.elim y xi = q := by
    funext i
    rcases i with i | i <;> rfl
  rw [← hsplit]
  exact hpoint

/-- The precise post-extension base-relative Gabber input used by the Laurent
symbol argument. -/
def CanonicalGeometricBaseRelativePoisson : Prop :=
  ∀ (k : Type u) [Field k] [CharZero k] [IsAlgClosed k] (n N : ℕ)
    (d : PresentedWeyl k (n + 1)),
    0 < N → IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d →
      IsBaseRelativePoisson
        (geometricReducedOrderSupportIdeal
          (K := LaurentSeries k)
          (canonicalRightIdeal (presentedCoordinate k n) d N))

/-- Post-extension Gabber closure produces the packaged Laurent symbol control
consumed by the terminal proof. -/
theorem canonicalLaurentSymbolControl_of_geometric_inputs
    (hgabber : CanonicalGeometricBaseRelativePoisson.{u}) :
    CanonicalLaurentSymbolControl.{u} := by
  intro k _ _ _ n N d hN hd
  letI : CharZero (LaurentSeries k) :=
    charZero_of_injective_algebraMap
      (algebraMap k (LaurentSeries k)).injective
  let W := canonicalRightIdeal (presentedCoordinate k n) d N
  rcases exists_canonical_fibrePolynomial n N hd with ⟨P, hP⟩
  refine ⟨P, hP, ?_⟩
  intro q hq
  have hqSupport : q ∈ MvPolynomial.zeroLocus (LaurentSeries k)
      (geometricReducedOrderSupportIdeal
        (K := LaurentSeries k) W) :=
    equationConormalLocus_groundMap_subset_geometricReducedSupport
      W (hgabber k n N d hN hd) hq
  have hprincipal : presentedPrincipalComponent k
        (@Stafford38.WeylFiltration.orderWeight (n + 1)) N d ∈
      reducedOrderSupportIdeal k W :=
    orderInitialIdeal_le_reducedOrderSupportIdeal k W
      (canonical_orderPrincipalComponent_mem_initialIdeal k n N hd)
  have hmapped : scalarPolynomialMap
        (k := k) (K := LaurentSeries k) (PhaseVar (n + 1))
        (presentedPrincipalComponent k
          (@Stafford38.WeylFiltration.orderWeight (n + 1)) N d) ∈
      geometricReducedOrderSupportIdeal
        (K := LaurentSeries k) W :=
    Ideal.le_radical (Ideal.mem_map_of_mem
      (scalarPolynomialMap
        (k := k) (K := LaurentSeries k) (PhaseVar (n + 1))) hprincipal)
  have hzero := hqSupport _ hmapped
  rw [← hP] at hzero
  simpa only [MvPolynomial.aeval_eq_eval, eval_scalarPolynomialMap] using hzero

#print axioms exists_fibreLift_eq_of_isFibreOnly
#print axioms exists_canonical_fibrePolynomial
#print axioms zeroSection_mem_geometricReducedSupport_of_groundBaseZero
#print axioms equationConormalLocus_groundMap_subset_geometricReducedSupport
#print axioms canonicalLaurentSymbolControl_of_geometric_inputs

end

end Stafford38.Characteristic.CanonicalLaurentSymbolControl
