import AlgebraicAnalysis.Module.CommutingPolynomialAction

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic

export AlgebraicAnalysis.CommutingPolynomialAction (commutingPolynomialAction commutingPolynomialAction_apply_X commutingPolynomialAction_apply_C commutingPolynomialAction_intertwines commutingPolynomialModule)

end Stafford38.Characteristic
