import Stafford38.Characteristic.LocalizedOrderReesTwoJetSpecializationKernel
import Stafford38.Characteristic.LocalizedTwoBlockPrincipalKernelDescent

/-!
# The concrete localized two-block special fibre

For the localized opposite order-Rees two-jet, the principal specialization
kernel theorem applies to the actual `RightReesArtinianAdapter` data.  After
the two-block quotient, the kernel is therefore the two-sided ideal generated
by the parameter class.  Quotienting by that ideal gives a ring equivalence
with the commutative doubled-power quotient.

No Artinianness, module action, adapted basis, or equation-(3.3) input is used.
-/

namespace Stafford38.Characteristic.ConcreteLocalizedTwoBlockSpecialFibre

open Stafford38.Characteristic
open Stafford38.Characteristic.LocalizedTwoBlockPrincipalKernelDescent
open Stafford38.Characteristic.LocalizedTwoBlockQuotient
open Stafford38.Characteristic.RightReesArtinianAdapter
open Stafford38.Characteristic.SquareZeroLocalizedExactness
open Stafford38.Characteristic.SquareZeroLocalizedRing
open Stafford38.CharacteristicConcreteSquareZeroTraceData
open Stafford38.CharacteristicLocalizedOrderReesTwoJetSpecializationKernel
open Stafford38.CharacteristicOrderReesTwoJet
open Stafford38.EulerSurjectivity
open Stafford38.WeylIteratedEquivalence

noncomputable section

set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 1000000

universe u

variable (k : Type u) [Field k]
variable {n : ℕ}
variable (I : RightIdeal (PresentedWeyl k n))
variable (S : Submonoid (SymbolRing k n))
variable [OreLocalization.OreSet
  (OppositeDenominators (filteredQuotientTwoJetTraceData k I) S)]
variable [IsLocalRing (Localization S)]

private abbrev concreteData := filteredQuotientTwoJetTraceData k I

local notation "D" => concreteData k I
local notation "Cₗ" =>
  OreLocalization (OppositeDenominators D S)
    ((OrderReesTwoJet (n := n) k)ᵐᵒᵖ)
local notation "A₀" => Localization S

/-- The concrete localized two-block parameter class. -/
def concreteLocalizedTwoBlockParameter (q : ℕ) :
    LocalizedTwoBlockRing D S q :=
  (localizedTwoBlockIdeal D S q).ringCon.mk'
    (OreLocalization.numeratorRingHom
      (MulOpposite.op (orderReesTwoJetParameter (n := n) k)))

/-- The two-sided ideal generated by the parameter class. -/
def concreteLocalizedTwoBlockParameterIdeal (q : ℕ) :
    TwoSidedIdeal (LocalizedTwoBlockRing D S q) :=
  TwoSidedIdeal.span {concreteLocalizedTwoBlockParameter k I S q}

/-- The actual order-Rees localized principal-kernel theorem, instantiated in
the notation consumed by the abstract two-block descent. -/
theorem concreteLocalizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
    (q : ℕ) (z : LocalizedTwoBlockRing D S q) :
    localizedTwoBlockSpecialization D S q z = 0 ↔
      ∃ y : LocalizedTwoBlockRing D S q,
        concreteLocalizedTwoBlockParameter k I S q * y = z := by
  exact localizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
    D S q
      (localizedOrderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
        k I S) z

/-- In the concrete two-jet, the specialization kernel is exactly the
two-sided ideal generated by the quotient parameter. -/
theorem concreteLocalizedTwoBlockParameterIdeal_eq_ker (q : ℕ) :
    concreteLocalizedTwoBlockParameterIdeal k I S q =
      TwoSidedIdeal.ker (localizedTwoBlockSpecialization D S q) := by
  apply le_antisymm
  · intro z hz
    change z ∈ TwoSidedIdeal.span
      {concreteLocalizedTwoBlockParameter k I S q} at hz
    rw [TwoSidedIdeal.mem_span_iff] at hz
    exact hz (TwoSidedIdeal.ker (localizedTwoBlockSpecialization D S q)) (by
      intro c hc
      rcases hc with rfl
      apply (TwoSidedIdeal.mem_ker
        (localizedTwoBlockSpecialization D S q)).2
      change localizedTwoBlockSpecialization D S q
        (concreteLocalizedTwoBlockParameter k I S q) = 0
      exact
        (concreteLocalizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
          k I S q (concreteLocalizedTwoBlockParameter k I S q)).2
            ⟨1, mul_one _⟩)
  · intro z hz
    have hz0 : localizedTwoBlockSpecialization D S q z = 0 :=
      (TwoSidedIdeal.mem_ker
        (localizedTwoBlockSpecialization D S q)).1 hz
    obtain ⟨y, rfl⟩ :=
      (concreteLocalizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
        k I S q z).mp hz0
    exact (concreteLocalizedTwoBlockParameterIdeal k I S q).mul_mem_right
      _ _ (TwoSidedIdeal.subset_span (Set.mem_singleton _))

/-- The literal quotient of the localized two-block ring by its parameter
class. -/
abbrev ConcreteLocalizedTwoBlockSpecialFibreRing (q : ℕ) :=
  (concreteLocalizedTwoBlockParameterIdeal k I S q).ringCon.Quotient

/-- Specialization descended to the quotient by the parameter class. -/
def concreteLocalizedTwoBlockSpecialFibreHom (q : ℕ) :
    ConcreteLocalizedTwoBlockSpecialFibreRing k I S q →+*
      (Localization S) ⧸ localizedDoubledPower S q :=
  quotientRingHom (concreteLocalizedTwoBlockParameterIdeal k I S q)
    (localizedTwoBlockSpecialization D S q) (by
      intro z hz
      exact (TwoSidedIdeal.mem_ker
        (localizedTwoBlockSpecialization D S q)).1
          ((concreteLocalizedTwoBlockParameterIdeal_eq_ker k I S q) ▸ hz))

@[simp]
theorem concreteLocalizedTwoBlockSpecialFibreHom_mk
    (q : ℕ) (z : LocalizedTwoBlockRing D S q) :
    concreteLocalizedTwoBlockSpecialFibreHom k I S q
        ((concreteLocalizedTwoBlockParameterIdeal k I S q).ringCon.mk' z) =
      localizedTwoBlockSpecialization D S q z := by
  rfl

theorem concreteLocalizedTwoBlockSpecialFibreHom_injective (q : ℕ) :
    Function.Injective (concreteLocalizedTwoBlockSpecialFibreHom k I S q) := by
  intro x y hxy
  induction x using Quotient.inductionOn' with
  | _ a =>
    induction y using Quotient.inductionOn' with
    | _ b =>
      apply Quotient.sound'
      apply (concreteLocalizedTwoBlockParameterIdeal k I S q).rel_iff a b |>.2
      rw [concreteLocalizedTwoBlockParameterIdeal_eq_ker]
      apply (TwoSidedIdeal.mem_ker
        (localizedTwoBlockSpecialization D S q)).2
      rw [map_sub, sub_eq_zero]
      exact hxy

theorem concreteLocalizedTwoBlockSpecialFibreHom_surjective (q : ℕ) :
    Function.Surjective
      (concreteLocalizedTwoBlockSpecialFibreHom k I S q) := by
  intro z
  obtain ⟨y, hy⟩ := localizedTwoBlockSpecialization_surjective D S q z
  exact ⟨(concreteLocalizedTwoBlockParameterIdeal k I S q).ringCon.mk' y, hy⟩

/-- The quotient ring modulo the concrete quotient parameter is exactly the
doubled-power commutative quotient. -/
def concreteLocalizedTwoBlockSpecialFibreRingEquiv (q : ℕ) :
    ConcreteLocalizedTwoBlockSpecialFibreRing k I S q ≃+*
      (Localization S) ⧸ localizedDoubledPower S q :=
  RingEquiv.ofBijective (concreteLocalizedTwoBlockSpecialFibreHom k I S q)
    ⟨concreteLocalizedTwoBlockSpecialFibreHom_injective k I S q,
      concreteLocalizedTwoBlockSpecialFibreHom_surjective k I S q⟩

@[simp]
theorem concreteLocalizedTwoBlockSpecialFibreRingEquiv_mk
    (q : ℕ) (z : LocalizedTwoBlockRing D S q) :
    concreteLocalizedTwoBlockSpecialFibreRingEquiv k I S q
        ((concreteLocalizedTwoBlockParameterIdeal k I S q).ringCon.mk' z) =
      localizedTwoBlockSpecialization D S q z := by
  rfl

#print axioms concreteLocalizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
#print axioms concreteLocalizedTwoBlockParameterIdeal_eq_ker
#print axioms concreteLocalizedTwoBlockSpecialFibreRingEquiv
#print axioms concreteLocalizedTwoBlockSpecialFibreRingEquiv_mk

end

end Stafford38.Characteristic.ConcreteLocalizedTwoBlockSpecialFibre
