import Stafford38.Characteristic.FilteredQuotient

/-!
# The graded bridge for a filtered right-ideal quotient

The degreewise equivalences of `FilteredQuotient` assemble into an external
direct-sum equivalence.  The exact symbol relation in degree `N` is stable
under multiplication by a homogeneous symbol of degree `M`; transporting this
operator gives the actual quotient graded pieces homogeneous multiplication
maps compatible with Weyl multiplication.

This file does not identify the direct sum with
`SymbolRing / orderInitialIdeal`.  That final identification requires proving
that the degree-`N` part of the ideal generated by all initial symbols is
exactly `orderSymbolRelation k I N`.
-/

namespace Stafford38.CharacteristicFilteredQuotientGraded

open Stafford38.Characteristic
open Stafford38.CharacteristicFilteredQuotient
open Stafford38.CharacteristicInitialIdeal
open Stafford38.EulerSurjectivity
open Stafford38.WeylIteratedEquivalence
open Stafford38.WeylFiltration
open Stafford38.WeylAssociatedGraded
open Stafford38.WeylLeadingSymbol

noncomputable section

universe u

variable (k : Type u) [Field k]
variable {n : ℕ}

/-- The external direct sum of the actual associated-graded pieces of `A/I`. -/
abbrev QuotientOrderAssociatedGraded (I : RightIdeal (PresentedWeyl k n)) :=
  DirectSum ℕ (fun N => QuotientOrderGradedPiece k I N)

/-- The external direct sum of homogeneous symbols modulo the exact relation
piece coming from the filtered quotient. -/
abbrev OrderSymbolRelationGraded (I : RightIdeal (PresentedWeyl k n)) :=
  DirectSum ℕ (fun N =>
    MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N ⧸
      orderSymbolRelation k I N)

/-- The degreewise filtered-quotient equivalences assemble without adding any
unproved multiplication or support assertion. -/
def quotientOrderAssociatedGradedEquivSymbols
    (I : RightIdeal (PresentedWeyl k n)) :
    QuotientOrderAssociatedGraded k I ≃ₗ[k] OrderSymbolRelationGraded k I :=
  DFinsupp.mapRange.linearEquiv fun N =>
    quotientOrderGradedPieceEquivSymbols k I N

/-- Right multiplication by a homogeneous symbol, with the resulting degree
recorded in the codomain. -/
def homogeneousRightMul {N M : ℕ}
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M) :
    MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N →ₗ[k]
      MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) (N + M) where
  toFun Q := ⟨(Q : SymbolRing k n) * P, Q.property.mul P.property⟩
  map_add' Q R := by
    apply Subtype.ext
    exact add_mul (Q : SymbolRing k n) R P
  map_smul' c Q := by
    apply Subtype.ext
    exact Algebra.smul_mul_assoc c (Q : SymbolRing k n) P

@[simp] theorem coe_homogeneousRightMul {N M : ℕ}
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M)
    (Q : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N) :
    (homogeneousRightMul k P Q : SymbolRing k n) = Q * P :=
  rfl

/-- The exact degree-`N` relation is closed under multiplication by every
degree-`M` homogeneous symbol.  This is the load-bearing multiplication
compatibility: it uses right-ideal closure before passing to principal
symbols. -/
theorem homogeneousRightMul_mem_orderSymbolRelation {N M : ℕ}
    (I : RightIdeal (PresentedWeyl k n))
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M)
    (Q : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N)
    (hQ : Q ∈ orderSymbolRelation k I N) :
    homogeneousRightMul k P Q ∈ orderSymbolRelation k I (N + M) := by
  obtain ⟨z, hzN, hzI, hQz⟩ :=
    (mem_orderSymbolRelation_iff k I N Q).mp hQ
  obtain ⟨y, hy⟩ :=
    principalComponentOnPiece_surjective k (@orderWeight n) P
  let zy : PresentedWeyl k n := z * (y : PresentedWeyl k n)
  have hzyPiece : zy ∈ orderPiece k n (N + M) :=
    mul_mem_orderPiece k hzN y.property
  have hzyI : zy ∈ I := by
    exact I.smul_mem (MulOpposite.op (y : PresentedWeyl k n)) hzI
  apply (mem_orderSymbolRelation_iff k I (N + M)
    (homogeneousRightMul k P Q)).mpr
  refine ⟨zy, hzyPiece, hzyI, ?_⟩
  apply Subtype.ext
  change (Q : SymbolRing k n) * P =
    presentedPrincipalComponent k (@orderWeight n) (N + M) zy
  rw [presentedPrincipalComponent_mul_order k hzN y.property]
  change (Q : SymbolRing k n) * P =
    presentedPrincipalComponent k (@orderWeight n) N z *
      (principalComponentOnPiece k (@orderWeight n) M y : SymbolRing k n)
  have hQz' : (Q : SymbolRing k n) =
      presentedPrincipalComponent k (@orderWeight n) N z :=
    congrArg Subtype.val hQz
  have hy' :
      (principalComponentOnPiece k (@orderWeight n) M y : SymbolRing k n) = P :=
    congrArg Subtype.val hy
  rw [hQz', hy']

/-- A homogeneous symbol acts on the corresponding quotient of homogeneous
symbols because exact relation pieces are multiplicatively stable. -/
def homogeneousSymbolAction {N M : ℕ}
    (I : RightIdeal (PresentedWeyl k n))
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M) :
    (MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N ⧸
        orderSymbolRelation k I N) →ₗ[k]
      (MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) (N + M) ⧸
        orderSymbolRelation k I (N + M)) :=
  (orderSymbolRelation k I N).mapQ (orderSymbolRelation k I (N + M))
    (homogeneousRightMul k P)
    (homogeneousRightMul_mem_orderSymbolRelation k I P)

@[simp] theorem homogeneousSymbolAction_mk {N M : ℕ}
    (I : RightIdeal (PresentedWeyl k n))
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M)
    (Q : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N) :
    homogeneousSymbolAction k I P (Submodule.Quotient.mk Q) =
      Submodule.Quotient.mk (homogeneousRightMul k P Q) :=
  rfl

/-- Transport of homogeneous symbol multiplication to the actual
associated-graded pieces of the filtered quotient. -/
def quotientOrderHomogeneousAction {N M : ℕ}
    (I : RightIdeal (PresentedWeyl k n))
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M) :
    QuotientOrderGradedPiece k I N →ₗ[k]
      QuotientOrderGradedPiece k I (N + M) :=
  (quotientOrderGradedPieceEquivSymbols k I (N + M)).symm.toLinearMap.comp
    ((homogeneousSymbolAction k I P).comp
      (quotientOrderGradedPieceEquivSymbols k I N).toLinearMap)

/-- The transported action commutes exactly with the degreewise symbol
equivalences. -/
theorem quotientOrderHomogeneousAction_compatibility {N M : ℕ}
    (I : RightIdeal (PresentedWeyl k n))
    (P : MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M)
    (q : QuotientOrderGradedPiece k I N) :
    quotientOrderGradedPieceEquivSymbols k I (N + M)
        (quotientOrderHomogeneousAction k I P q) =
      homogeneousSymbolAction k I P
        (quotientOrderGradedPieceEquivSymbols k I N q) := by
  simp [quotientOrderHomogeneousAction]

@[simp] theorem quotientOrderGradedPieceEquivSymbols_mk {N : ℕ}
    (I : RightIdeal (PresentedWeyl k n)) (z : orderPiece k n N) :
    quotientOrderGradedPieceEquivSymbols k I N
        (orderPieceToQuotientGraded k I N z) =
      Submodule.Quotient.mk
        (principalComponentOnPiece k (@orderWeight n) N z) := by
  rw [quotientOrderGradedPieceEquivSymbols, LinearEquiv.trans_apply]
  rw [← show quotientOrderGradedPieceEquivRelation k I N
      (Submodule.Quotient.mk z) = orderPieceToQuotientGraded k I N z from rfl]
  rw [LinearEquiv.symm_apply_apply]
  rfl

/-- On classes of filtered representatives, the transported homogeneous
operator is exactly multiplication in the Weyl algebra followed by passage to
the associated graded quotient. -/
theorem quotientOrderHomogeneousAction_mk_mul {N M : ℕ}
    (I : RightIdeal (PresentedWeyl k n))
    (z : orderPiece k n N) (y : orderPiece k n M) :
    quotientOrderHomogeneousAction k I
        (principalComponentOnPiece k (@orderWeight n) M y)
        (orderPieceToQuotientGraded k I N z) =
      orderPieceToQuotientGraded k I (N + M)
        ⟨(z : PresentedWeyl k n) * y,
          mul_mem_orderPiece k z.property y.property⟩ := by
  apply (quotientOrderGradedPieceEquivSymbols k I (N + M)).injective
  rw [quotientOrderHomogeneousAction_compatibility]
  rw [quotientOrderGradedPieceEquivSymbols_mk,
    quotientOrderGradedPieceEquivSymbols_mk,
    homogeneousSymbolAction_mk]
  congr 1
  apply Subtype.ext
  exact (presentedPrincipalComponent_mul_order k z.property y.property).symm

/-!
The remaining prerequisite for a global `SymbolRing`-module equivalence is
the homogeneous-piece equality

`P ∈ orderSymbolRelation k I N ↔
  (P : SymbolRing k n) ∈ orderInitialIdeal k I`.

The forward implication is already proved in `FilteredQuotient`.  The reverse
implication requires decomposing arbitrary ideal multipliers into weighted
homogeneous components and combining the action above degree by degree.  No
support or annihilator statement is made before that equality is available.
-/

#print axioms quotientOrderAssociatedGradedEquivSymbols
#print axioms homogeneousRightMul_mem_orderSymbolRelation
#print axioms homogeneousSymbolAction
#print axioms quotientOrderHomogeneousAction
#print axioms quotientOrderHomogeneousAction_compatibility
#print axioms quotientOrderGradedPieceEquivSymbols_mk
#print axioms quotientOrderHomogeneousAction_mk_mul

end

end Stafford38.CharacteristicFilteredQuotientGraded
