import AlgebraicAnalysis.Module.FilteredTwoTermBoundaryExhaustion
import Stafford38.Characteristic.FilteredTwoTermTotalPages

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.FilteredTwoTermPages

export AlgebraicAnalysis.FilteredTwoTermPages (FilteredTwoTerm.targetBoundaryMap FilteredTwoTerm.targetBoundaryMap_mk FilteredTwoTerm.targetBoundaryMap_surjective FilteredTwoTerm.targetBoundaryMap_ker_mono FilteredTwoTerm.totalBoundaryMap FilteredTwoTerm.totalBoundaryMap_lof FilteredTwoTerm.totalBoundaryMap_surjective FilteredTwoTerm.totalBoundaryMap_ker_mono FilteredTwoTerm.totalBoundaryMap_eventually_zero)

end Stafford38.Characteristic.FilteredTwoTermPages
