module
public import AlgebraicAnalysis.Module.FilteredTwoTermTotalActions
public import Stafford38.Characteristic.FilteredTwoTermTotalPages

@[expose] public section

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.FilteredTwoTermPages

export AlgebraicAnalysis.FilteredTwoTermPages (FilteredTwoTerm.PageOperator.sourceTotalMap FilteredTwoTerm.PageOperator.targetTotalMap FilteredTwoTerm.PageOperator.sourceTotalMap_lof FilteredTwoTerm.PageOperator.targetTotalMap_lof FilteredTwoTerm.PageOperator.totalDrop_intertwines FilteredTwoTerm.PageOperator.sourceTotalMap_commute_of_commutator_lowers FilteredTwoTerm.PageOperator.targetTotalMap_commute_of_commutator_lowers)

end Stafford38.Characteristic.FilteredTwoTermPages
