import AlgebraicAnalysis.Module.FilteredTwoTermTotalPages
import Stafford38.Characteristic.FilteredTwoTermPageEquivalences
import Stafford38.Characteristic.FilteredTwoTermPageActions

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.FilteredTwoTermPages

export AlgebraicAnalysis.FilteredTwoTermPages (FilteredTwoTerm.SourceTotal FilteredTwoTerm.TargetTotal FilteredTwoTerm.totalDrop FilteredTwoTerm.totalDrop_lof FilteredTwoTerm.totalDrop_lof_mk FilteredTwoTerm.sourceTotalSuccMap FilteredTwoTerm.totalSourceSuccMap_injective FilteredTwoTerm.range_totalSourceSuccMap FilteredTwoTerm.sourceTotalSuccEquivKerDrop FilteredTwoTerm.targetTotalSuccMap FilteredTwoTerm.ker_totalTargetSuccMap FilteredTwoTerm.targetTotalSuccEquivCokerDrop)

end Stafford38.Characteristic.FilteredTwoTermPages
