import AlgebraicAnalysis.Module.FilteredTwoTermPageActions
import Stafford38.Characteristic.FilteredTwoTermPages

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.FilteredTwoTermPages

export AlgebraicAnalysis.FilteredTwoTermPages (FilteredTwoTerm.PageOperator FilteredTwoTerm.PageOperator.comp FilteredTwoTerm.PageOperator.reverseComp FilteredTwoTerm.PageOperator.commute_apply FilteredTwoTerm.PageOperator.sourceRestricted FilteredTwoTerm.PageOperator.sourceMap FilteredTwoTerm.PageOperator.sourceMap_mk FilteredTwoTerm.PageOperator.sourcePageCast FilteredTwoTerm.PageOperator.sourcePageCast_mk FilteredTwoTerm.PageOperator.targetRestricted FilteredTwoTerm.PageOperator.targetMap FilteredTwoTerm.PageOperator.targetMap_mk FilteredTwoTerm.PageOperator.targetPageCast FilteredTwoTerm.PageOperator.targetPageCast_mk FilteredTwoTerm.PageOperator.targetMapAtDrop FilteredTwoTerm.PageOperator.targetMapAtDrop_mk FilteredTwoTerm.PageOperator.targetMapAtDrop_eq_cast_targetMap FilteredTwoTerm.PageOperator.targetMapAtDrop_drop FilteredTwoTerm.PageOperator.targetMap_drop FilteredTwoTerm.PageOperator.SameSymbol FilteredTwoTerm.PageOperator.sourceMap_eq_of_sameSymbol FilteredTwoTerm.PageOperator.targetMap_eq_of_sameSymbol FilteredTwoTerm.PageOperator.targetMapAtDrop_eq_of_sameSymbol)

end Stafford38.Characteristic.FilteredTwoTermPages
