import Stafford38.Characteristic.LocalizedTwoBlockQuotient

/-!
# Principal specialization kernels after the localized two-block quotient

Suppose that the kernel of the localized opposite specialization is exactly
the left principal ideal generated by the localized square-zero parameter.
The kernel of the descended two-block specialization is then exactly the
left principal ideal generated by the parameter class in the quotient.

The proof retains multiplication order.  An element of the doubled power is
lifted as an ordered sum of products `a * b`; those products lie in the
two-block ideal.  Only the remaining element of the original specialization
kernel is factored by the parameter.

No Artinianness, module-action statement, adapted basis, or matrix identity is
used here.
-/

namespace Stafford38.Characteristic.LocalizedTwoBlockPrincipalKernelDescent

open Stafford38.Characteristic.LocalizedTwoBlockQuotient
open Stafford38.Characteristic.RightReesArtinianAdapter
open Stafford38.Characteristic.SquareZeroLocalizedExactness
open Stafford38.Characteristic.SquareZeroLocalizedRing
open Stafford38.Characteristic.SquareZeroTraceData

noncomputable section

universe u_R u_k u_B u_N u_G

variable {k : Type u_k} {R : Type u_R} {B : Type u_B}
variable {N : Type u_N} {G : Type u_G}
variable [Field k] [CommRing R] [Algebra k R]
variable [Ring B] [Algebra k B]
variable [AddCommGroup N] [Module k N] [Module Bᵐᵒᵖ N]
variable [SMulCommClass k Bᵐᵒᵖ N]
variable [AddCommGroup G] [Module k G] [Module R G]

variable (D : RightSquareZeroTraceData k R B N G)
variable (S : Submonoid R)
variable [OreLocalization.OreSet (OppositeDenominators D S)]
variable [IsLocalRing (Localization S)]

local notation "Cₗ" =>
  OreLocalization (OppositeDenominators D S) (Bᵐᵒᵖ)
local notation "A₀" => Localization S
local notation "𝔪" => IsLocalRing.maximalIdeal A₀

/-- Every element of the doubled power has an ordered lift in the two-block
ideal.  Surjectivity is applied separately to the left and right factors, so
no commutation in the noncommutative source is used. -/
theorem exists_mem_localizedTwoBlockIdeal_map_eq_of_mem_doubledPower
    (q : ℕ) {r : A₀}
    (hr : r ∈ localizedDoubledPower S q) :
    ∃ z : Cₗ,
      z ∈ localizedTwoBlockIdeal D S q ∧
        localizedOppositeSpecialization D S z = r := by
  change r ∈ (𝔪 ^ q) • (𝔪 ^ q) at hr
  refine Submodule.smul_induction_on hr ?_ ?_
  · intro a ha b hb
    obtain ⟨x, hx⟩ :=
      localizedOppositeSpecialization_surjective D S a
    obtain ⟨y, hy⟩ :=
      localizedOppositeSpecialization_surjective D S b
    refine ⟨x * y, ?_, ?_⟩
    · apply TwoSidedIdeal.subset_span
      exact ⟨x,
        (mem_localizedHighPowerPullback_iff D S q x).2 (hx ▸ ha),
        y, (mem_localizedHighPowerPullback_iff D S q y).2 (hy ▸ hb), rfl⟩
    · rw [map_mul, hx, hy]
      rfl
  · rintro r₁ r₂ ⟨z₁, hz₁, hmap₁⟩ ⟨z₂, hz₂, hmap₂⟩
    refine ⟨z₁ + z₂,
      (localizedTwoBlockIdeal D S q).add_mem hz₁ hz₂, ?_⟩
    rw [map_add, hmap₁, hmap₂]

/-- Written-order left multiplication by the parameter class in the
localized two-block quotient. -/
def localizedTwoBlockParameterMul (q : ℕ) :
    LocalizedTwoBlockRing D S q →+
      LocalizedTwoBlockRing D S q where
  toFun y :=
    (localizedTwoBlockIdeal D S q).ringCon.mk'
        (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) * y
  map_zero' := mul_zero _
  map_add' := mul_add _

@[simp]
theorem localizedTwoBlockParameterMul_apply
    (q : ℕ) (y : LocalizedTwoBlockRing D S q) :
    localizedTwoBlockParameterMul D S q y =
      (localizedTwoBlockIdeal D S q).ringCon.mk'
          (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) * y :=
  rfl

/-- Descent of an exact left-principal specialization kernel through the
two-block quotient.  The principal-kernel hypothesis is stated on `Cₗ` in
the same written multiplication order as the conclusion. -/
theorem localizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
    (q : ℕ)
    (hprincipal : ∀ x : Cₗ,
      localizedOppositeSpecialization D S x = 0 ↔
        ∃ y : Cₗ,
          OreLocalization.numeratorRingHom (MulOpposite.op D.c) * y = x)
    (z : LocalizedTwoBlockRing D S q) :
    localizedTwoBlockSpecialization D S q z = 0 ↔
      ∃ y : LocalizedTwoBlockRing D S q,
        (localizedTwoBlockIdeal D S q).ringCon.mk'
            (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) * y = z := by
  induction z using Quotient.inductionOn' with
  | _ x =>
    constructor
    · intro hx
      change Ideal.Quotient.mk (localizedDoubledPower S q)
          (localizedOppositeSpecialization D S x) = 0 at hx
      rw [Ideal.Quotient.eq_zero_iff_mem] at hx
      obtain ⟨j, hj, hmapj⟩ :=
        exists_mem_localizedTwoBlockIdeal_map_eq_of_mem_doubledPower
          D S q hx
      have hzero :
          localizedOppositeSpecialization D S (x - j) = 0 := by
        rw [map_sub, hmapj, sub_self]
      obtain ⟨y, hy⟩ := (hprincipal (x - j)).mp hzero
      refine ⟨(localizedTwoBlockIdeal D S q).ringCon.mk' y, ?_⟩
      have hj0 :
          (localizedTwoBlockIdeal D S q).ringCon.mk' j = 0 := by
        apply (TwoSidedIdeal.mem_ker
          ((localizedTwoBlockIdeal D S q).ringCon.mk')).1
        simpa using hj
      calc
        (localizedTwoBlockIdeal D S q).ringCon.mk'
              (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) *
            (localizedTwoBlockIdeal D S q).ringCon.mk' y =
          (localizedTwoBlockIdeal D S q).ringCon.mk'
            (OreLocalization.numeratorRingHom (MulOpposite.op D.c) * y) := by
              exact ((localizedTwoBlockIdeal D S q).ringCon.mk').map_mul _ _ |>.symm
        _ = (localizedTwoBlockIdeal D S q).ringCon.mk' (x - j) :=
          congrArg ((localizedTwoBlockIdeal D S q).ringCon.mk') hy
        _ = (localizedTwoBlockIdeal D S q).ringCon.mk' x -
            (localizedTwoBlockIdeal D S q).ringCon.mk' j :=
          ((localizedTwoBlockIdeal D S q).ringCon.mk').map_sub x j
        _ = (localizedTwoBlockIdeal D S q).ringCon.mk' x := by
          rw [hj0, sub_zero]
    · rintro ⟨y, hy⟩
      rw [← hy, map_mul]
      have hc0 :
          localizedOppositeSpecialization D S
            (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) = 0 :=
        (hprincipal
          (OreLocalization.numeratorRingHom (MulOpposite.op D.c))).2
            ⟨1, mul_one _⟩
      rw [localizedTwoBlockSpecialization_mk, hc0, map_zero, zero_mul]

/-- Kernel/range form of the descended left-principal kernel theorem. -/
theorem localizedTwoBlockSpecialization_ker_eq_range_parameterMul
    (q : ℕ)
    (hprincipal : ∀ x : Cₗ,
      localizedOppositeSpecialization D S x = 0 ↔
        ∃ y : Cₗ,
          OreLocalization.numeratorRingHom (MulOpposite.op D.c) * y = x) :
    AddMonoidHom.ker
        (localizedTwoBlockSpecialization D S q).toAddMonoidHom =
      AddMonoidHom.range (localizedTwoBlockParameterMul D S q) := by
  ext z
  rw [AddMonoidHom.mem_ker, AddMonoidHom.mem_range]
  exact localizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
    D S q hprincipal z

#print axioms exists_mem_localizedTwoBlockIdeal_map_eq_of_mem_doubledPower
#print axioms localizedTwoBlockSpecialization_eq_zero_iff_exists_parameter_mul
#print axioms localizedTwoBlockSpecialization_ker_eq_range_parameterMul

end

end Stafford38.Characteristic.LocalizedTwoBlockPrincipalKernelDescent
