import Stafford38.Characteristic.LocalizedHighPowerTwoBlockVanishing
import Mathlib.Algebra.Module.RingHom
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# The localized two-block quotient

The localized opposite deformation ring is noncommutative, so the candidate
truncation must be formed with a two-sided ideal rather than `Ideal.Quotient`.
For an annihilating power in the commutative special fibre, this file pulls
the power back to a two-sided ideal `H`, lets `J` be the two-sided span of the
products `a * b` with `a,b in H`, and proves that `J` annihilates the actual
localized deformation module.  Consequently the action descends to the ring
congruence quotient by `J`.

No source matrices, adapted basis, or trace identity is assumed here.
-/

namespace Stafford38.Characteristic.LocalizedTwoBlockQuotient

open Stafford38.Characteristic.LocalizedHighPowerTwoBlockVanishing
open Stafford38.Characteristic.RightReesArtinianAdapter
open Stafford38.Characteristic.SquareZeroLocalizedExactness
open Stafford38.Characteristic.SquareZeroLocalizedRing
open Stafford38.Characteristic.SquareZeroTraceData

noncomputable section

universe u_C u_W u_R u_k u_B u_N u_G

section AbstractQuotientAction

variable {C : Type u_C} {W : Type u_W}
variable [Ring C] [AddCommGroup W] [Module C W]

/-- The two-sided ideal of scalars acting by zero on every module vector. -/
def actionAnnihilator : TwoSidedIdeal C :=
  TwoSidedIdeal.mk'
    {a : C | ∀ w : W, a • w = 0}
    (by intro w; exact zero_smul C w)
    (by
      intro a b ha hb w
      rw [add_smul, ha w, hb w, add_zero])
    (by
      intro a ha w
      rw [neg_smul, ha w, neg_zero])
    (by
      intro a b hb w
      rw [mul_smul, hb w, smul_zero])
    (by
      intro a b ha w
      rw [mul_smul, ha (b • w)])

@[simp]
theorem mem_actionAnnihilator_iff {a : C} :
    a ∈ actionAnnihilator (C := C) (W := W) ↔ ∀ w : W, a • w = 0 := by
  simp [actionAnnihilator, TwoSidedIdeal.mem_mk']

/-- The two-sided ideal generated by products of two elements of `H`. -/
def twoBlockIdeal (H : TwoSidedIdeal C) : TwoSidedIdeal C :=
  TwoSidedIdeal.span
    {z : C | ∃ a ∈ H, ∃ b ∈ H, a * b = z}

/-- Killing every displayed two-block product kills its full two-sided span. -/
theorem twoBlockIdeal_le_actionAnnihilator
    (H : TwoSidedIdeal C)
    (hprod : ∀ a ∈ H, ∀ b ∈ H, ∀ w : W, (a * b) • w = 0) :
    twoBlockIdeal H ≤ actionAnnihilator (C := C) (W := W) := by
  intro z hz
  change z ∈ TwoSidedIdeal.span
      {z : C | ∃ a ∈ H, ∃ b ∈ H, a * b = z} at hz
  rw [TwoSidedIdeal.mem_span_iff] at hz
  exact hz (actionAnnihilator (C := C) (W := W)) (by
    rintro z ⟨a, ha, b, hb, rfl⟩
    exact (mem_actionAnnihilator_iff (C := C) (W := W)).2 (hprod a ha b hb))

/-- Scalar multiplication by the quotient ring, when the quotient ideal acts
trivially. -/
def quotientSMul (J : TwoSidedIdeal C)
    (hJ : J ≤ actionAnnihilator (C := C) (W := W)) :
    SMul J.ringCon.Quotient W where
  smul q w := q.liftOn (fun a : C => a • w) (by
    intro a b hab
    have hsub : (a - b) • w = 0 :=
      (mem_actionAnnihilator_iff (C := C) (W := W)).1
        (hJ ((J.rel_iff a b).1 hab)) w
    rw [sub_smul] at hsub
    exact sub_eq_zero.mp hsub)

/-- The original module action descended through a noncommutative two-sided
quotient. -/
def quotientModule (J : TwoSidedIdeal C)
    (hJ : J ≤ actionAnnihilator (C := C) (W := W)) :
    Module J.ringCon.Quotient W := by
  letI : SMul J.ringCon.Quotient W := quotientSMul J hJ
  exact Function.Surjective.moduleLeft J.ringCon.mk'
      Quotient.mk''_surjective (by
    intro a w
    rfl)

@[simp]
theorem quotient_mk_smul (J : TwoSidedIdeal C)
    (hJ : J ≤ actionAnnihilator (C := C) (W := W))
    (a : C) (w : W) :
    letI := quotientModule J hJ
    J.ringCon.mk' a • w = a • w := by
  change (quotientSMul J hJ).smul (J.ringCon.mk' a) w = a • w
  rfl

variable {T : Type*} [Ring T]

/-- A ring homomorphism that kills a two-sided ideal descends through its
ring-congruence quotient. -/
def quotientRingHom (J : TwoSidedIdeal C) (f : C →+* T)
    (hf : ∀ a ∈ J, f a = 0) : J.ringCon.Quotient →+* T where
  toFun q := q.liftOn f (by
    intro a b hab
    have hz : f (a - b) = 0 := hf (a - b) ((J.rel_iff a b).1 hab)
    rw [map_sub] at hz
    exact sub_eq_zero.mp hz)
  map_zero' := f.map_zero
  map_one' := f.map_one
  map_add' x y := Quotient.inductionOn₂' x y fun a b => f.map_add a b
  map_mul' x y := Quotient.inductionOn₂' x y fun a b => f.map_mul a b

@[simp]
theorem quotientRingHom_mk (J : TwoSidedIdeal C) (f : C →+* T)
    (hf : ∀ a ∈ J, f a = 0) (a : C) :
    quotientRingHom J f hf (J.ringCon.mk' a) = f a := by
  unfold quotientRingHom
  rfl

end AbstractQuotientAction

variable {k : Type u_k} {R : Type u_R} {B : Type u_B}
variable {N : Type u_N} {G : Type u_G}
variable [Field k] [CommRing R] [Algebra k R]
variable [Ring B] [Algebra k B]
variable [AddCommGroup N] [Module k N] [Module Bᵐᵒᵖ N]
variable [SMulCommClass k Bᵐᵒᵖ N]
variable [AddCommGroup G] [Module k G] [Module R G]

variable (D : RightSquareZeroTraceData k R B N G)
variable (S : Submonoid R)
variable [OreLocalization.OreSet (OppositeDenominators D S)]
variable [IsLocalRing (Localization S)]

local notation "Cₗ" =>
  OreLocalization (OppositeDenominators D S) (Bᵐᵒᵖ)
local notation "Wₗ" => LocalizedDeformationModule D S
local notation "A₀" => Localization S
local notation "𝔪" => IsLocalRing.maximalIdeal A₀

/-- The pullback `H` of the annihilating maximal-ideal power.  It is a
two-sided ideal because it is formed by comapping the corresponding
two-sided ideal of the commutative special fibre. -/
def localizedHighPowerPullback (q : ℕ) : TwoSidedIdeal Cₗ :=
  TwoSidedIdeal.comap (localizedOppositeSpecialization D S)
    (TwoSidedIdeal.fromIdeal (𝔪 ^ q))

theorem mem_localizedHighPowerPullback_iff (q : ℕ) (a : Cₗ) :
    a ∈ localizedHighPowerPullback D S q ↔
      localizedOppositeSpecialization D S a ∈ 𝔪 ^ q := by
  rw [localizedHighPowerPullback, TwoSidedIdeal.mem_comap]
  have h := (TwoSidedIdeal.orderIsoIdeal (R := A₀)).right_inv (𝔪 ^ q)
  change localizedOppositeSpecialization D S a ∈
      TwoSidedIdeal.asIdeal (TwoSidedIdeal.fromIdeal (𝔪 ^ q)) ↔ _
  exact SetLike.ext_iff.mp h (localizedOppositeSpecialization D S a)

/-- The genuine noncommutative two-block ideal `J`. -/
def localizedTwoBlockIdeal (q : ℕ) : TwoSidedIdeal Cₗ :=
  twoBlockIdeal (localizedHighPowerPullback D S q)

/-- The doubled commutative power used as the specialization target. -/
def localizedDoubledPower (q : ℕ) : Ideal A₀ :=
  (𝔪 ^ q) * (𝔪 ^ q)

/-- Specialization followed by the commutative doubled-power quotient. -/
def localizedDoubledPowerSpecialization (q : ℕ) :
    Cₗ →+* A₀ ⧸ localizedDoubledPower S q :=
  (Ideal.Quotient.mk (localizedDoubledPower S q)).comp
    (localizedOppositeSpecialization D S)

/-- The two-block ideal lies in the kernel of doubled-power specialization. -/
theorem localizedTwoBlockIdeal_le_doubledPowerSpecializationKernel
    (q : ℕ) :
    ∀ z ∈ localizedTwoBlockIdeal D S q,
      localizedDoubledPowerSpecialization D S q z = 0 := by
  intro z hz
  change z ∈ TwoSidedIdeal.span
      {z : Cₗ | ∃ a ∈ localizedHighPowerPullback D S q,
        ∃ b ∈ localizedHighPowerPullback D S q, a * b = z} at hz
  rw [TwoSidedIdeal.mem_span_iff] at hz
  have hker := hz
    (TwoSidedIdeal.ker (localizedDoubledPowerSpecialization D S q)) (by
      rintro z ⟨a, ha, b, hb, rfl⟩
      apply (TwoSidedIdeal.mem_ker
        (localizedDoubledPowerSpecialization D S q)).2
      rw [map_mul]
      change Ideal.Quotient.mk (localizedDoubledPower S q)
          (localizedOppositeSpecialization D S a) *
        Ideal.Quotient.mk (localizedDoubledPower S q)
          (localizedOppositeSpecialization D S b) = 0
      rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.mul_mem_mul
        ((mem_localizedHighPowerPullback_iff D S q a).1 ha)
        ((mem_localizedHighPowerPullback_iff D S q b).1 hb))
  exact (TwoSidedIdeal.mem_ker
    (localizedDoubledPowerSpecialization D S q)).1 hker

/-- The first load-bearing quotient statement: `J` acts trivially on the
localized deformation module. -/
theorem localizedTwoBlockIdeal_le_actionAnnihilator
    (q : ℕ)
    (hpow : 𝔪 ^ q ≤
      Module.annihilator A₀ (LocalizedModule S G)) :
    localizedTwoBlockIdeal D S q ≤
      actionAnnihilator (C := Cₗ) (W := Wₗ) := by
  apply twoBlockIdeal_le_actionAnnihilator
  intro a ha b hb w
  apply product_smul_eq_zero_of_specializations_mem_annihilator D S a b
  · exact hpow ((mem_localizedHighPowerPullback_iff D S q a).1 ha)
  · exact hpow ((mem_localizedHighPowerPullback_iff D S q b).1 hb)

/-- The localized two-block quotient ring. Artinianness is not asserted. -/
abbrev LocalizedTwoBlockRing (q : ℕ) :=
  (localizedTwoBlockIdeal D S q).ringCon.Quotient

/-- The honestly descended ring specialization.  Its target is the
commutative doubled-power quotient; no identification of module special
fibres is claimed. -/
def localizedTwoBlockSpecialization (q : ℕ) :
    LocalizedTwoBlockRing D S q →+*
      A₀ ⧸ localizedDoubledPower S q :=
  quotientRingHom (localizedTwoBlockIdeal D S q)
    (localizedDoubledPowerSpecialization D S q)
    (localizedTwoBlockIdeal_le_doubledPowerSpecializationKernel D S q)

@[simp]
theorem localizedTwoBlockSpecialization_mk
    (q : ℕ) (a : Cₗ) :
    localizedTwoBlockSpecialization D S q
        ((localizedTwoBlockIdeal D S q).ringCon.mk' a) =
      Ideal.Quotient.mk (localizedDoubledPower S q)
        (localizedOppositeSpecialization D S a) := by
  rfl

/-- The descended specialization is surjective. -/
theorem localizedTwoBlockSpecialization_surjective (q : ℕ) :
    Function.Surjective (localizedTwoBlockSpecialization D S q) := by
  intro y
  obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective y
  obtain ⟨a, ha⟩ := localizedOppositeSpecialization_surjective D S r
  refine ⟨(localizedTwoBlockIdeal D S q).ringCon.mk' a, ?_⟩
  rw [localizedTwoBlockSpecialization_mk, ha]

/-- The descended action of the two-block quotient ring on the unchanged
localized deformation module. -/
def localizedTwoBlockModule
    (q : ℕ)
    (hpow : 𝔪 ^ q ≤
      Module.annihilator A₀ (LocalizedModule S G)) :
    Module (LocalizedTwoBlockRing D S q) Wₗ :=
  quotientModule (localizedTwoBlockIdeal D S q)
    (localizedTwoBlockIdeal_le_actionAnnihilator D S q hpow)

/-- The descended scalar action, exposed without installing a global instance. -/
def localizedTwoBlockAction
    (q : ℕ)
    (hpow : 𝔪 ^ q ≤
      Module.annihilator A₀ (LocalizedModule S G))
    (a : LocalizedTwoBlockRing D S q) (w : Wₗ) : Wₗ :=
  (quotientSMul (localizedTwoBlockIdeal D S q)
    (localizedTwoBlockIdeal_le_actionAnnihilator D S q hpow)).smul a w

@[simp]
theorem localizedTwoBlockAction_mk
    (q : ℕ)
    (hpow : 𝔪 ^ q ≤
      Module.annihilator A₀ (LocalizedModule S G))
    (a : Cₗ) (w : Wₗ) :
    localizedTwoBlockAction D S q hpow
      ((localizedTwoBlockIdeal D S q).ringCon.mk' a) w = a • w := by
  rfl

/-- The descended parameter still acts by the concrete localized parameter
operator. -/
theorem localizedTwoBlock_parameter_smul
    (q : ℕ)
    (hpow : 𝔪 ^ q ≤
      Module.annihilator A₀ (LocalizedModule S G))
    (w : Wₗ) :
    localizedTwoBlockAction D S q hpow
      ((localizedTwoBlockIdeal D S q).ringCon.mk'
        (OreLocalization.numeratorRingHom (MulOpposite.op D.c))) w =
      localizedCAct D S w := by
  rw [localizedTwoBlockAction_mk]
  rw [localizedCAct_apply]
  exact OreLocalization.oreDiv_one_smul _ _

/-- The parameter remains square-zero in the two-block quotient. -/
theorem localizedTwoBlock_parameter_sq
    (q : ℕ) :
    ((localizedTwoBlockIdeal D S q).ringCon.mk'
        (OreLocalization.numeratorRingHom (MulOpposite.op D.c))) ^ 2 = 0 := by
  rw [pow_two]
  calc
    (localizedTwoBlockIdeal D S q).ringCon.mk'
          (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) *
        (localizedTwoBlockIdeal D S q).ringCon.mk'
          (OreLocalization.numeratorRingHom (MulOpposite.op D.c)) =
      (localizedTwoBlockIdeal D S q).ringCon.mk'
        (OreLocalization.numeratorRingHom (MulOpposite.op D.c) *
          OreLocalization.numeratorRingHom (MulOpposite.op D.c)) := by
            exact ((localizedTwoBlockIdeal D S q).ringCon.mk').map_mul _ _ |>.symm
    _ = (localizedTwoBlockIdeal D S q).ringCon.mk'
        (OreLocalization.numeratorRingHom
          (MulOpposite.op D.c * MulOpposite.op D.c)) := by
            exact congrArg ((localizedTwoBlockIdeal D S q).ringCon.mk')
              ((OreLocalization.numeratorRingHom
                (S := OppositeDenominators D S) (R := Bᵐᵒᵖ)).map_mul _ _).symm
    _ = 0 := by
      have hc : D.c * D.c = 0 := by
        simpa [pow_two] using D.c_sq
      rw [show MulOpposite.op D.c * MulOpposite.op D.c =
        MulOpposite.op (D.c * D.c) by rfl, hc]
      calc
        (localizedTwoBlockIdeal D S q).ringCon.mk'
            (OreLocalization.numeratorRingHom (MulOpposite.op 0)) =
          (localizedTwoBlockIdeal D S q).ringCon.mk' 0 := by
            exact congrArg ((localizedTwoBlockIdeal D S q).ringCon.mk')
              ((OreLocalization.numeratorRingHom
                (S := OppositeDenominators D S) (R := Bᵐᵒᵖ)).map_zero)
        _ = 0 := (localizedTwoBlockIdeal D S q).ringCon.mk'.map_zero

#print axioms twoBlockIdeal_le_actionAnnihilator
#print axioms quotientModule
#print axioms quotientRingHom
#print axioms localizedTwoBlockIdeal_le_actionAnnihilator
#print axioms localizedTwoBlockIdeal_le_doubledPowerSpecializationKernel
#print axioms localizedTwoBlockSpecialization_surjective
#print axioms localizedTwoBlockAction_mk
#print axioms localizedTwoBlock_parameter_smul
#print axioms localizedTwoBlock_parameter_sq

end

end Stafford38.Characteristic.LocalizedTwoBlockQuotient
