import Stafford38.Characteristic.OrderReesTwoJetSpecializationKernel
import Stafford38.Characteristic.SquareZeroLocalizedRing

/-!
# The localized order-Rees two-jet specialization kernel

For the concrete order-Rees two-jet, localization of the opposite ring does
not enlarge the specialization kernel beyond the localized central parameter.
The proof is direct on Ore fractions.  A denominator that kills the
specialized numerator is lifted through the surjective two-jet
specialization, the numerator is enlarged in the opposite ring, and the exact
unlocalized kernel theorem factors it by the Rees parameter.

Products remain in the opposite/right-module orientation throughout.  In
particular, the localized parameter is written on the left; centrality is used
explicitly before applying the unlocalized factorization.
-/

namespace Stafford38.CharacteristicLocalizedOrderReesTwoJetSpecializationKernel

open Stafford38.Characteristic
open Stafford38.Characteristic.SquareZeroLocalizedExactness
open Stafford38.Characteristic.SquareZeroLocalizedRing
open Stafford38.CharacteristicConcreteSquareZeroTraceData
open Stafford38.CharacteristicOrderReesTwoJet
open Stafford38.CharacteristicOrderReesTwoJetSpecializationKernel
open Stafford38.EulerSurjectivity
open Stafford38.WeylIteratedEquivalence

noncomputable section

set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 1000000

universe u

variable (k : Type u) [Field k]
variable {n : ℕ}

private abbrev concreteData
    (I : RightIdeal (PresentedWeyl k n)) :=
  filteredQuotientTwoJetTraceData k I

variable (I : RightIdeal (PresentedWeyl k n))
variable (S : Submonoid (SymbolRing k n))
variable [OreLocalization.OreSet
  (OppositeDenominators (concreteData k I) S)]

/-- Written-order left multiplication by the localized central Rees
parameter. -/
def localizedOrderReesTwoJetParameterMul :
    OreLocalization (OppositeDenominators (concreteData k I) S)
        ((OrderReesTwoJet (n := n) k)ᵐᵒᵖ) →+
      OreLocalization (OppositeDenominators (concreteData k I) S)
        ((OrderReesTwoJet (n := n) k)ᵐᵒᵖ) where
  toFun y := OreLocalization.numeratorHom
    (MulOpposite.op (orderReesTwoJetParameter (n := n) k)) * y
  map_zero' := mul_zero _
  map_add' := mul_add _

@[simp] theorem localizedOrderReesTwoJetParameterMul_apply
    (y : OreLocalization (OppositeDenominators (concreteData k I) S)
      ((OrderReesTwoJet (n := n) k)ᵐᵒᵖ)) :
    localizedOrderReesTwoJetParameterMul k I S y =
      OreLocalization.numeratorHom
        (MulOpposite.op (orderReesTwoJetParameter (n := n) k)) * y :=
  rfl

private theorem localized_parameter_mul_oreDiv
    (b : (OrderReesTwoJet (n := n) k)ᵐᵒᵖ)
    (s : OppositeDenominators (concreteData k I) S) :
    OreLocalization.numeratorHom
          (MulOpposite.op (orderReesTwoJetParameter (n := n) k)) *
        (b /ₒ s) =
      (MulOpposite.op (orderReesTwoJetParameter (n := n) k) * b) /ₒ s := by
  change
    (MulOpposite.op (orderReesTwoJetParameter (n := n) k) /ₒ
        (1 : OppositeDenominators (concreteData k I) S)) *
        (b /ₒ s) = _
  simpa using OreLocalization.oreDiv_mul_char
    (MulOpposite.op (orderReesTwoJetParameter (n := n) k)) b
    (1 : OppositeDenominators (concreteData k I) S) s
    (MulOpposite.op (orderReesTwoJetParameter (n := n) k)) s
    (show (s : (OrderReesTwoJet (n := n) k)ᵐᵒᵖ) *
          MulOpposite.op (orderReesTwoJetParameter (n := n) k) =
        MulOpposite.op (orderReesTwoJetParameter (n := n) k) * s from by
      apply MulOpposite.unop_injective
      exact (orderReesTwoJetParameter_mem_center (n := n) k).comm s.val.unop)

/-- The concrete localized opposite order-Rees two-jet specialization has
exactly the left-principal kernel generated by the localized central
parameter, stated elementwise in written multiplication order. -/
theorem localizedOrderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
    (x : OreLocalization (OppositeDenominators (concreteData k I) S)
      ((OrderReesTwoJet (n := n) k)ᵐᵒᵖ)) :
    localizedOppositeSpecialization (concreteData k I) S x = 0 ↔
      ∃ y : OreLocalization (OppositeDenominators (concreteData k I) S)
          ((OrderReesTwoJet (n := n) k)ᵐᵒᵖ),
        OreLocalization.numeratorHom
            (MulOpposite.op (orderReesTwoJetParameter (n := n) k)) * y = x := by
  constructor
  · intro hx
    induction x using OreLocalization.ind with
    | _ b s =>
      rw [localizedOppositeSpecialization_oreDiv] at hx
      have hbase :
          algebraMap (SymbolRing k n) (Localization S)
            (orderReesTwoJetSpecialization (n := n) k b.unop) = 0 := by
        exact (Units.isUnit
          ((localizedDenominatorUnits (concreteData k I) S s)⁻¹)).mul_left_cancel
            (by rw [mul_zero]; exact hx)
      obtain ⟨u, hu⟩ :=
        (IsLocalization.map_eq_zero_iff S (Localization S)
          (orderReesTwoJetSpecialization (n := n) k b.unop)).mp hbase
      obtain ⟨a, ha⟩ :=
        orderReesTwoJetSpecialization_surjective (n := n) k (u : SymbolRing k n)
      let v : (OrderReesTwoJet (n := n) k)ᵐᵒᵖ := MulOpposite.op a
      have hvS : v ∈ OppositeDenominators (concreteData k I) S := by
        change orderReesTwoJetSpecialization (n := n) k a ∈ S
        rw [ha]
        exact u.property
      have hvb_zero :
          orderReesTwoJetSpecialization (n := n) k (v * b).unop = 0 := by
        change orderReesTwoJetSpecialization (n := n) k (b.unop * a) = 0
        rw [map_mul, ha]
        simpa [mul_comm] using hu
      obtain ⟨q, hq⟩ :=
        (orderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
          (n := n) k (v * b).unop).mp hvb_zero
      have hfactor :
          MulOpposite.op (orderReesTwoJetParameter (n := n) k) *
              MulOpposite.op q = v * b := by
        apply MulOpposite.unop_injective
        change q * orderReesTwoJetParameter (n := n) k = b.unop * a
        rw [← (orderReesTwoJetParameter_mem_center (n := n) k).comm q]
        exact hq
      have hvs : v * (s : (OrderReesTwoJet (n := n) k)ᵐᵒᵖ) ∈
          OppositeDenominators (concreteData k I) S :=
        mul_mem hvS s.property
      let t : OppositeDenominators (concreteData k I) S :=
        ⟨v * s, hvs⟩
      refine ⟨(MulOpposite.op q) /ₒ t, ?_⟩
      rw [localized_parameter_mul_oreDiv]
      rw [hfactor]
      symm
      exact OreLocalization.expand b s v hvs
  · rintro ⟨y, rfl⟩
    rw [map_mul]
    change
      localizedOppositeSpecialization (concreteData k I) S
          (OreLocalization.numeratorHom
            (MulOpposite.op (concreteData k I).c)) *
        localizedOppositeSpecialization (concreteData k I) S y = 0
    rw [localizedOppositeSpecialization_parameter, zero_mul]

/-- Kernel/range form of the concrete localized principal-kernel theorem. -/
theorem localizedOrderReesTwoJetSpecialization_ker_eq_range_parameterMul :
    AddMonoidHom.ker
        (localizedOppositeSpecialization (concreteData k I) S).toAddMonoidHom =
      AddMonoidHom.range (localizedOrderReesTwoJetParameterMul k I S) := by
  ext x
  rw [AddMonoidHom.mem_ker, AddMonoidHom.mem_range]
  exact
    localizedOrderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
      k I S x

#print axioms localizedOrderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
#print axioms localizedOrderReesTwoJetSpecialization_ker_eq_range_parameterMul

end

end Stafford38.CharacteristicLocalizedOrderReesTwoJetSpecializationKernel
