import Stafford38.Characteristic.OrderReesTwoJet
import Mathlib.Algebra.Polynomial.Inductions

/-!
# The specialization kernel of the order-Rees two-jet

The kernel is computed before localization.  First, degreewise weighted
homogeneity shows that an order-Rees polynomial with zero principal-symbol
sum has every coefficient one filtration step below its declared degree.
Dividing the polynomial by the central variable `T` therefore stays inside
the order-Rees ring.  Passing through the quotient by `T²` gives the exact
elementwise principal-kernel statement for the two-jet.

The factor is always written on the left.  Centrality of `T` is not used to
reverse any noncommutative product.
-/

namespace Stafford38.CharacteristicOrderReesTwoJetSpecializationKernel

open Stafford38.Characteristic
open Stafford38.CharacteristicOrderReesTwoJet
open Stafford38.WeylAssociatedGraded
open Stafford38.WeylFiltration
open Stafford38.WeylIteratedEquivalence
open Stafford38.WeylLeadingSymbol
open Stafford38.WeylOrderRees
open Stafford38.WeylPBW

noncomputable section

set_option maxHeartbeats 1200000
set_option synthInstance.maxHeartbeats 200000

universe u

variable (k : Type u) [Field k]
variable {n : ℕ}

/-- Weighted homogeneity prevents cancellation between distinct declared
Rees degrees in the principal-symbol sum. -/
private theorem principal_component_eq_zero_of_sum_eq_zero
    (r : OrderReesRing (n := n) k)
    (hr : orderReesSpecialization (n := n) k r = 0)
    (N : ℕ) :
    presentedPrincipalComponent k (@orderWeight n) N
        ((r : Polynomial (PresentedWeyl k n)).coeff N) = 0 := by
  classical
  change orderPrincipalSum (n := n) k
      (r : Polynomial (PresentedWeyl k n)) = 0 at hr
  change (r : Polynomial (PresentedWeyl k n)).sum
      (fun M z => presentedPrincipalComponent k (@orderWeight n) M z) = 0 at hr
  have hcomponent := congrArg
    (MvPolynomial.weightedHomogeneousComponent (@orderWeight n) N) hr
  rw [map_zero] at hcomponent
  simp only [Polynomial.sum, map_sum] at hcomponent
  by_cases hN : N ∈ (r : Polynomial (PresentedWeyl k n)).support
  · rw [Finset.sum_eq_single N] at hcomponent
    · have hhom :
          presentedPrincipalComponent k (@orderWeight n) N
              ((r : Polynomial (PresentedWeyl k n)).coeff N) ∈
            MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) N :=
        MvPolynomial.weightedHomogeneousComponent_mem
          (@orderWeight n)
          (presentedNormalFormLinearEquiv k n
            ((r : Polynomial (PresentedWeyl k n)).coeff N)) N
      rw [MvPolynomial.weightedHomogeneousComponent_of_mem hhom] at hcomponent
      simpa using hcomponent
    · intro M hM hMN
      have hhom :
          presentedPrincipalComponent k (@orderWeight n) M
              ((r : Polynomial (PresentedWeyl k n)).coeff M) ∈
            MvPolynomial.weightedHomogeneousSubmodule k (@orderWeight n) M :=
        MvPolynomial.weightedHomogeneousComponent_mem
          (@orderWeight n)
          (presentedNormalFormLinearEquiv k n
            ((r : Polynomial (PresentedWeyl k n)).coeff M)) M
      rw [MvPolynomial.weightedHomogeneousComponent_of_mem hhom]
      simp [Ne.symm hMN]
    · intro hnot
      exact (hnot hN).elim
  · have hcoeff : (r : Polynomial (PresentedWeyl k n)).coeff N = 0 :=
      Polynomial.notMem_support_iff.mp hN
    rw [hcoeff, map_zero]

/-- The kernel of the unquotiented order-Rees specialization is the left
principal ideal generated by the central Rees parameter, stated
elementwise. -/
theorem orderReesSpecialization_eq_zero_iff_exists_parameter_mul
    (r : OrderReesRing (n := n) k) :
    orderReesSpecialization (n := n) k r = 0 ↔
      ∃ s : OrderReesRing (n := n) k,
        orderReesParameter (n := n) k * s = r := by
  constructor
  · intro hr
    have hlower : ∀ N,
        (r : Polynomial (PresentedWeyl k n)).coeff (N + 1) ∈
          orderPiece k n N := by
      intro N
      have hprincipal := principal_component_eq_zero_of_sum_eq_zero
        (n := n) k r hr (N + 1)
      have hmem := r.property (N + 1)
      exact (presentedPrincipalComponent_eq_zero_iff_mem_strictLower
        k (@orderWeight n) ((r : Polynomial (PresentedWeyl k n)).coeff (N + 1))
          hmem).mp hprincipal
    let s : OrderReesRing (n := n) k :=
      ⟨Polynomial.divX (r : Polynomial (PresentedWeyl k n)), by
        intro N
        rw [Polynomial.coeff_divX]
        exact hlower N⟩
    refine ⟨s, ?_⟩
    apply Subtype.ext
    change Polynomial.X * Polynomial.divX
        (r : Polynomial (PresentedWeyl k n)) =
      (r : Polynomial (PresentedWeyl k n))
    have hconstant : (r : Polynomial (PresentedWeyl k n)).coeff 0 = 0 := by
      have hprincipal := principal_component_eq_zero_of_sum_eq_zero
        (n := n) k r hr 0
      have hmem := r.property 0
      have hlower0 := (presentedPrincipalComponent_eq_zero_iff_mem_strictLower
        k (@orderWeight n) ((r : Polynomial (PresentedWeyl k n)).coeff 0)
          hmem).mp hprincipal
      simpa [presentedStrictLowerPiece, Submodule.mem_bot] using hlower0
    simpa [hconstant] using
      (Polynomial.X_mul_divX_add (r : Polynomial (PresentedWeyl k n)))
  · rintro ⟨s, rfl⟩
    rw [map_mul, orderReesSpecialization_parameter, zero_mul]

/-- Exact unlocalized specialization kernel for the concrete order-Rees
two-jet: every killed class is a left multiple of the square-zero parameter,
and every such multiple is killed. -/
theorem orderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
    (q : OrderReesTwoJet (n := n) k) :
    orderReesTwoJetSpecialization (n := n) k q = 0 ↔
      ∃ b : OrderReesTwoJet (n := n) k,
        orderReesTwoJetParameter (n := n) k * b = q := by
  constructor
  · intro hq
    obtain ⟨r, rfl⟩ := Quotient.mk''_surjective q
    change orderReesSpecialization (n := n) k r = 0 at hq
    obtain ⟨s, hs⟩ :=
      (orderReesSpecialization_eq_zero_iff_exists_parameter_mul
        (n := n) k r).mp hq
    refine ⟨orderReesTwoJetQuotient (n := n) k s, ?_⟩
    rw [orderReesTwoJetParameter, ← map_mul, hs]
    rfl
  · rintro ⟨b, rfl⟩
    rw [map_mul, orderReesTwoJetSpecialization_parameter, zero_mul]

/-- The same exactness statement in linear-kernel/range form. -/
theorem orderReesTwoJetSpecialization_ker_eq_range_parameterMul :
    LinearMap.ker (orderReesTwoJetSpecialization (n := n) k).toLinearMap =
      LinearMap.range
        (LinearMap.mulLeft k (orderReesTwoJetParameter (n := n) k)) := by
  ext q
  rw [LinearMap.mem_ker, LinearMap.mem_range]
  exact orderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
    (n := n) k q

#print axioms orderReesSpecialization_eq_zero_iff_exists_parameter_mul
#print axioms orderReesTwoJetSpecialization_eq_zero_iff_exists_parameter_mul
#print axioms orderReesTwoJetSpecialization_ker_eq_range_parameterMul

end

end Stafford38.CharacteristicOrderReesTwoJetSpecializationKernel
