import AlgebraicAnalysis.Module.PrincipalKoszulSupportOverBase
import Stafford38.Characteristic.StableTorsionResidualSupport
import Stafford38.Characteristic.PrincipalKoszulFiniteTorsion

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.PrincipalKoszulSupportOverBase

export AlgebraicAnalysis.PrincipalKoszulSupportOverBase (length_cokernel_gt_kernel_of_support_over_base)

end Stafford38.Characteristic.PrincipalKoszulSupportOverBase
