import AlgebraicAnalysis.Module.PrincipalKoszulFiniteTorsion
import Stafford38.Characteristic.PrincipalKoszulPositivity

/- Compatibility exports for the neutral AlgebraicAnalysis API. -/

namespace Stafford38.Characteristic.PrincipalKoszulFiniteTorsion

export AlgebraicAnalysis.PrincipalKoszulFiniteTorsion (isNoetherian_kernel_power isFiniteLength_kernel_power length_cokernel_gt_kernel_of_stable_power_and_nonzero)

end Stafford38.Characteristic.PrincipalKoszulFiniteTorsion
