import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Stafford38.Characteristic.PostScalarExtensionPoisson

/-!
# Involutivity descends from a radical to its minimal primes

Gabber's theorem is stated for the *radical* of the annihilator of an
associated graded module: `{√J, √J} ⊆ √J`.  The project interfaces, and the
coisotropic consumers downstream of them, ask instead for involutivity of each
individual minimal prime of `J`.  This file supplies the elementary
commutative-algebra step between the two, so that no Gabber-shaped statement
has to be strengthened by hand.

Two facts are proved.

* `exists_notMem_mul_mem_radical`: if `P` is minimal over `J` and `f ∈ P`,
  then some `s ∉ P` satisfies `s * f ∈ √J`.  This is the saturation statement
  that replaces localizing at `P`; it is proved directly from the maximally
  disjoint prime construction applied to the multiplicative set generated by
  `P`'s complement together with `f`, so no Noetherian hypothesis and no
  finiteness of the minimal-prime set is used.

* `minimalPrimes_isInvolutive_of_radical_isInvolutive`: if `√J` is involutive
  then every minimal prime of `J` is involutive.  With `u = s * t` produced by
  the previous lemma for `f` and `g`, the Leibniz rule gives

  ```text
  {u f, u g} = u^2 {f, g} + u g {f, u} + u f {u, g},
  ```

  whose left-hand side lies in `√J ⊆ P` and whose last two summands lie in `P`
  because `f, g ∈ P`.  Hence `u^2 {f, g} ∈ P`, and `u ∉ P` with `P` prime
  gives `{f, g} ∈ P`.

Nothing here proves involutivity of any concrete radical; this is the
descent step only.
-/

namespace Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity

open Stafford38.Characteristic
open Stafford38.Characteristic.PostScalarExtensionPoisson

noncomputable section

section Saturation

variable {R : Type*} [CommRing R]

/-- Saturation at a minimal prime.  If `P` is minimal over `J` and `f ∈ P`,
some element outside `P` carries `f` into the radical of `J`.  This is the
localization-free form of `√(J R_P) = P R_P`. -/
theorem exists_notMem_mul_mem_radical
    {J P : Ideal R} (hP : P ∈ J.minimalPrimes) {f : R} (hf : f ∈ P) :
    ∃ s, s ∉ P ∧ s * f ∈ J.radical := by
  classical
  have hprime : P.IsPrime := hP.1.1
  by_contra hcon
  have hcon' : ∀ s : R, s ∉ P → s * f ∉ J.radical := fun s hs hmem =>
    hcon ⟨s, hs, hmem⟩
  set S : Submonoid R := P.primeCompl ⊔ Submonoid.powers f with hS
  have hdisj : Disjoint (J : Set R) (S : Set R) := by
    rw [Set.disjoint_left]
    rintro x hxJ hxS
    rw [SetLike.mem_coe, hS, Submonoid.mem_sup] at hxS
    obtain ⟨s, hs, z, hz, rfl⟩ := hxS
    obtain ⟨m, rfl⟩ := Submonoid.mem_powers_iff z f |>.mp hz
    have hsP : s ∉ P := hs
    cases m with
    | zero =>
        rw [pow_zero, mul_one] at hxJ
        exact hsP (hP.1.2 hxJ)
    | succ m =>
        refine hcon' s hsP ⟨m + 1, ?_⟩
        have hrw : (s * f) ^ (m + 1) = s ^ m * (s * f ^ (m + 1)) := by ring
        rw [hrw]
        exact Ideal.mul_mem_left _ _ hxJ
  obtain ⟨Q, hQprime, hJQ, hQdisj⟩ := Ideal.exists_le_prime_disjoint J S hdisj
  have hQP : Q ≤ P := by
    intro x hx
    by_contra hxP
    exact Set.disjoint_left.mp hQdisj hx
      (SetLike.mem_coe.mpr (le_sup_left (a := P.primeCompl) (b := Submonoid.powers f) hxP))
  have hPQ : P ≤ Q := hP.2 ⟨hQprime, hJQ⟩ hQP
  exact Set.disjoint_left.mp hQdisj (hPQ hf)
    (SetLike.mem_coe.mpr
      (le_sup_right (a := P.primeCompl) (b := Submonoid.powers f) (Submonoid.mem_powers f)))

end Saturation

section Involutivity

variable {k : Type*} [Field k] {n : ℕ}

/-- The Leibniz expansion used by the descent, with `{u, u} = 0` already
cancelled. -/
theorem sq_mul_poissonBracket_eq
    (u f g : SymbolRing k n) :
    u * u * poissonBracket f g =
      poissonBracket (u * f) (u * g)
        - u * (g * poissonBracket f u) - f * (u * poissonBracket u g) := by
  rw [poissonBracket_mul_left, poissonBracket_mul_right,
    poissonBracket_mul_right u u g, poissonBracket_self]
  ring

/-- Gabber's radical statement implies the minimal-prime statement the
project's coisotropic consumers require. -/
theorem minimalPrimes_isInvolutive_of_radical_isInvolutive
    (J : Ideal (SymbolRing k n)) (h : IsInvolutive J.radical) :
    ∀ P ∈ J.minimalPrimes, IsInvolutive P := by
  intro P hP f hf g hg
  have hprime : P.IsPrime := hP.1.1
  have hrad : J.radical ≤ P := hprime.radical_le_iff.mpr hP.1.2
  obtain ⟨s, hs, hsf⟩ := exists_notMem_mul_mem_radical hP hf
  obtain ⟨t, ht, htg⟩ := exists_notMem_mul_mem_radical hP hg
  set u : SymbolRing k n := s * t with hu
  have huf : u * f ∈ J.radical := by
    have hrw : u * f = t * (s * f) := by rw [hu]; ring
    rw [hrw]
    exact Ideal.mul_mem_left _ _ hsf
  have hug : u * g ∈ J.radical := by
    have hrw : u * g = s * (t * g) := by rw [hu]; ring
    rw [hrw]
    exact Ideal.mul_mem_left _ _ htg
  have hbr : poissonBracket (u * f) (u * g) ∈ J.radical := h _ huf _ hug
  have hmem : u * u * poissonBracket f g ∈ P := by
    rw [sq_mul_poissonBracket_eq]
    exact sub_mem
      (sub_mem (hrad hbr) (Ideal.mul_mem_left _ _ (Ideal.mul_mem_right _ _ hg)))
      (Ideal.mul_mem_right _ _ hf)
  have huP : u ∉ P := fun hmemu => (hprime.mem_or_mem hmemu).elim hs ht
  rcases hprime.mem_or_mem hmem with hsq | hbracket
  · exact absurd ((hprime.mem_or_mem hsq).elim id id) huP
  · exact hbracket

end Involutivity

#print axioms exists_notMem_mul_mem_radical
#print axioms sq_mul_poissonBracket_eq
#print axioms minimalPrimes_isInvolutive_of_radical_isInvolutive

end

end Stafford38.Characteristic.RadicalMinimalPrimeInvolutivity
