import Stafford38.Characteristic.AssociatedGradedFinite
import Stafford38.Characteristic.ConcreteSquareZeroTraceData
import Stafford38.Characteristic.SquareZeroHighPowerReduction
import Stafford38.Characteristic.SquareZeroLocalizedRing

/-!
# The concrete right-Rees Artinian-local adapter

This file packages the inputs that the concrete order-Rees two-jet already
supplies at a minimal prime of the special-fibre annihilator.  The deformation
ring is kept in the actual orientation used by the right module: it is the Ore
localization of the opposite two-jet ring, acting on the left on the localized
module.

The package contains the localized ring specialization, parameter vanishing,
both exact square-zero sequences, a nonzero finite-length special fibre, and
one maximal-ideal power annihilating that fibre.  It does not assume an
Artinian triangular trace theorem.

One missing localized-action consequence is recorded as
`LocalizedHighPowerTwoBlockVanishing`: two localized deformation blocks whose
specializations lie in the chosen annihilating power must act successively by
zero.  The more primitive missing inputs are compatibility of specialization
with the full localized action and exactness of the localized ring map with
kernel generated by the parameter.  The latter is needed to identify the ring
modulo its parameter with the commutative local fibre.  High-power Artinian
quotient descent and survival of parameter exactness are then separate.  No
Artinian quotient action is asserted below.
-/

namespace Stafford38.Characteristic.RightReesArtinianAdapter

open Stafford38.Characteristic
open Stafford38.Characteristic.SquareZeroHighPowerReduction
open Stafford38.Characteristic.SquareZeroLocalizedExactness
open Stafford38.Characteristic.SquareZeroLocalizedRing
open Stafford38.Characteristic.SquareZeroTraceData
open Stafford38.CharacteristicConcreteSquareZeroTraceData
open Stafford38.CharacteristicFilteredQuotientTwoJet
open Stafford38.CharacteristicOrderReesTwoJet
open Stafford38.EulerSurjectivity
open Stafford38.WeylIteratedEquivalence

noncomputable section

set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 1000000

universe u_k u_R u_B u_N u_G

variable {k : Type u_k} {R : Type u_R} {B : Type u_B}
variable {N : Type u_N} {G : Type u_G}
variable [Field k] [CharZero k]
variable [CommRing R] [Algebra k R]
variable [Ring B] [Algebra k B]
variable [AddCommGroup N] [Module k N] [Module Bᵐᵒᵖ N]
variable [SMulCommClass k Bᵐᵒᵖ N]
variable [AddCommGroup G] [Module k G] [Module R G]

variable (D : RightSquareZeroTraceData k R B N G)
variable (S : Submonoid R)
variable [OreLocalization.OreSet (OppositeDenominators D S)]
variable [IsLocalRing (Localization S)]
variable [CharZero (Localization S)]
variable [IsNoetherianRing (Localization S)]

/-- A precise missing localized-action consequence.

The factors are elements of the actual opposite localized deformation ring,
so their displayed product acts in the same order on the localized right-Rees
module.  This statement is deliberately elementwise: it is exactly what is
needed to make the finite sums defining the high-power product ideal act by
zero, without silently postulating a noncommutative ideal quotient.
-/
def LocalizedHighPowerTwoBlockVanishing (q : ℕ) : Prop :=
  ∀ {iota : Type*} (s : Finset iota)
    (a b : iota →
      OreLocalization (OppositeDenominators D S) (Bᵐᵒᵖ))
    (_ha : ∀ i ∈ s,
      localizedOppositeSpecialization D S (a i) ∈
        IsLocalRing.maximalIdeal (Localization S) ^ q)
    (_hb : ∀ i ∈ s,
      localizedOppositeSpecialization D S (b i) ∈
        IsLocalRing.maximalIdeal (Localization S) ^ q)
    (z : LocalizedDeformationModule D S),
      (∑ i ∈ s, a i * b i) • z = 0

/-- All pre-Artinian inputs already produced by the localized square-zero
development, before the missing two-block action bridge and quotient.

The structure is a proposition and introduces no replacement ring or module.
Every field names an equation for the concrete maps in the imported APIs.
Surjectivity and parameter vanishing do not identify the kernel of ring
specialization with the principal parameter ideal.
-/
structure LocalizedPreArtinianCore : Prop where
  base_charZero : CharZero k
  localizedFibre_charZero : CharZero (Localization S)
  localizedFibre_noetherian : IsNoetherianRing (Localization S)
  ringSpecialization_surjective :
    Function.Surjective (localizedOppositeSpecialization D S)
  ringSpecialization_numerator :
    ∀ b : Bᵐᵒᵖ,
      localizedOppositeSpecialization D S
          (OreLocalization.numeratorHom b) =
        algebraMap R (Localization S) (D.pi b.unop)
  ringSpecialization_parameter :
    localizedOppositeSpecialization D S
        (OreLocalization.numeratorHom (MulOpposite.op D.c)) = 0
  parameter_sq :
    ∀ z : LocalizedDeformationModule D S,
      localizedCAct D S (localizedCAct D S z) = 0
  parameter_fraction :
    ∀ (z : N) (s : OppositeDenominators D S),
      localizedCAct D S (z /ₒ s) =
        (MulOpposite.op D.c • z) /ₒ s
  parameter_exact :
    AddMonoidHom.ker (localizedCAct D S) =
      AddMonoidHom.range (localizedCAct D S)
  moduleSpecialization_surjective :
    Function.Surjective (localizedSpecialization D S)
  moduleSpecialization_fraction :
    ∀ (z : N) (s : OppositeDenominators D S),
      localizedSpecialization D S (z /ₒ s) =
        LocalizedModule.mk (D.rho z) (denominatorMap D S s)
  moduleSpecialization_exact :
    AddMonoidHom.ker (localizedSpecialization D S) =
      AddMonoidHom.range (localizedCAct D S)
  fibre_nontrivial : Nontrivial (LocalizedModule S G)
  fibre_finiteLength : IsFiniteLength (Localization S) (LocalizedModule S G)
  annihilatingPower :
    ∃ q : ℕ,
      IsLocalRing.maximalIdeal (Localization S) ^ q ≤
        Module.annihilator (Localization S) (LocalizedModule S G)

/-- Generic assembly of the localized pre-Artinian core from the existing ring,
module, and finite-length APIs.  This theorem does not prove
`LocalizedHighPowerTwoBlockVanishing`.
-/
theorem localizedPreArtinianCore_of_exact_finiteLength
    (hnontrivial : Nontrivial (LocalizedModule S G))
    (hlength : IsFiniteLength (Localization S) (LocalizedModule S G)) :
    LocalizedPreArtinianCore D S := by
  letI : Nontrivial (LocalizedModule S G) := hnontrivial
  obtain ⟨q, hq⟩ :=
    exists_maximalIdeal_pow_le_annihilator_of_finiteLength hlength
  exact
    { base_charZero := inferInstance
      localizedFibre_charZero := inferInstance
      localizedFibre_noetherian := inferInstance
      ringSpecialization_surjective :=
        localizedOppositeSpecialization_surjective D S
      ringSpecialization_numerator :=
        localizedOppositeSpecialization_numerator D S
      ringSpecialization_parameter :=
        localizedOppositeSpecialization_parameter D S
      parameter_sq := localizedCAct_sq_eq_zero D S
      parameter_fraction := localizedCAct_oreDiv D S
      parameter_exact := localizedCAct_ker_eq_range D S
      moduleSpecialization_surjective :=
        localizedSpecialization_surjective D S
      moduleSpecialization_fraction := by
        intro z s
        rw [localizedSpecialization_apply,
          localizedSpecializationFun_oreDiv]
      moduleSpecialization_exact :=
        localizedSpecialization_ker_eq_range D S
      fibre_nontrivial := hnontrivial
      fibre_finiteLength := hlength
      annihilatingPower := ⟨q, hq⟩ }

section Concrete

universe u

variable (K : Type u) [Field K] [CharZero K]
variable {n : ℕ}

/-- At every minimal prime over the characteristic-module annihilator, the
concrete right order-Rees two-jet supplies the full localized pre-Artinian core.

The existentially returned Ore-set instance is the one constructed from the
square-zero commutator factorization.  The theorem stops before asserting full
localized-action semilinearity, principal-parameter ring-kernel exactness,
`LocalizedHighPowerTwoBlockVanishing`, or Artinian quotient descent.
-/
theorem exists_concrete_localizedPreArtinianCore
    (I : RightIdeal (PresentedWeyl K n))
    (P : Ideal (SymbolRing K n)) [P.IsPrime]
    (hP : P ∈
      (Module.annihilator (SymbolRing K n)
        (Stafford38.CharacteristicAssociatedGradedModule.OrderAssociatedGradedModule
          K I)).minimalPrimes) :
    ∃ h : OreLocalization.OreSet
        (OppositeDenominators (filteredQuotientTwoJetTraceData K I)
          P.primeCompl),
      letI := h
      LocalizedPreArtinianCore
        (filteredQuotientTwoJetTraceData K I) P.primeCompl := by
  obtain ⟨h, _hexact, hnontrivial, hlength⟩ :=
    Stafford38.Characteristic.AssociatedGradedFinite.exists_minimalPrimeLocalizedExactnessAndFiniteLength
      K I P hP
  refine ⟨h, ?_⟩
  letI := h
  letI : CharZero (Localization P.primeCompl) :=
    charZero_of_injective_algebraMap
      (FaithfulSMul.algebraMap_injective K
        (Localization P.primeCompl))
  letI : IsNoetherianRing (Localization P.primeCompl) :=
    IsLocalization.isNoetherianRing P.primeCompl
      (Localization P.primeCompl) inferInstance
  exact localizedPreArtinianCore_of_exact_finiteLength
    (filteredQuotientTwoJetTraceData K I) P.primeCompl
      hnontrivial hlength

#print axioms LocalizedHighPowerTwoBlockVanishing
#print axioms localizedPreArtinianCore_of_exact_finiteLength
#print axioms exists_concrete_localizedPreArtinianCore

end Concrete

end

end Stafford38.Characteristic.RightReesArtinianAdapter
