import Stafford38.Characteristic.SquareZeroLocalizedExactness
import Mathlib.RingTheory.Localization.Basic

/-!
# The localized deformation-ring specialization

The module localization used by the right Rees two-jet is over the opposite
deformation ring.  This file constructs the corresponding ring map from that
Ore localization to the ordinary commutative localization of the special
fibre.  It is the first ring-level input in the Artinian-local Gabber route.

No assertion is made that the kernel is generated by the square-zero
parameter, that the target is an Artinian quotient, or that a coefficient
field exists.
-/

namespace Stafford38.Characteristic.SquareZeroLocalizedRing

open Stafford38.Characteristic.SquareZeroTraceData
open Stafford38.Characteristic.SquareZeroOreLocalization
open Stafford38.Characteristic.SquareZeroLocalizedExactness

noncomputable section

universe u_k u_R u_B u_N u_G

variable {k : Type u_k} {R : Type u_R} {B : Type u_B}
variable {N : Type u_N} {G : Type u_G}
variable [Field k] [CommRing R] [Algebra k R]
variable [Ring B] [Algebra k B]
variable [AddCommGroup N] [Module k N] [Module Bᵐᵒᵖ N]
variable [SMulCommClass k Bᵐᵒᵖ N]
variable [AddCommGroup G] [Module k G] [Module R G]

variable (D : RightSquareZeroTraceData k R B N G)

/-- Specialization is a ring homomorphism on the opposite deformation ring
because its target is commutative. -/
def oppositeSpecializationRingHom : Bᵐᵒᵖ →+* R where
  toFun b := D.pi b.unop
  map_one' := by simp
  map_zero' := by simp
  map_add' a b := by simp
  map_mul' a b := by
    change D.pi (b.unop * a.unop) = D.pi a.unop * D.pi b.unop
    rw [map_mul, mul_comm]

@[simp] theorem oppositeSpecializationRingHom_apply (b : Bᵐᵒᵖ) :
    oppositeSpecializationRingHom D b = D.pi b.unop :=
  rfl

section Ore

variable (S : Submonoid R)
variable [OreLocalization.OreSet (OppositeDenominators D S)]

/-- The canonical numerator units in a commutative localization. -/
def localizationNumeratorUnits : S →* Units (Localization S) where
  toFun := OreLocalization.numeratorUnit
  map_one' := by
    apply Units.ext
    change (OreLocalization.numeratorHom : R →* Localization S) 1 = 1
    exact map_one _
  map_mul' a b := by
    apply Units.ext
    change (OreLocalization.numeratorHom : R →* Localization S)
        ((a : R) * (b : R)) =
      (OreLocalization.numeratorHom : R →* Localization S) a *
        (OreLocalization.numeratorHom : R →* Localization S) b
    exact map_mul _ _ _

/-- Every pulled-back Ore denominator maps to its canonical numerator unit in
the commutative localization. -/
def localizedDenominatorUnits :
    OppositeDenominators D S →* Units (Localization S) :=
  (localizationNumeratorUnits S).comp (denominatorMap D S)

@[simp] theorem localizedDenominatorUnits_val
    (s : OppositeDenominators D S) :
    (localizedDenominatorUnits D S s : Localization S) =
      algebraMap R (Localization S) (denominatorMap D S s) := by
  rfl

/-- The specialization of the opposite deformation ring extends through its
Ore localization to the ordinary localization of the commutative fibre. -/
def localizedOppositeSpecialization :
    OreLocalization (OppositeDenominators D S) (Bᵐᵒᵖ) →+* Localization S :=
  OreLocalization.universalHom
    ((algebraMap R (Localization S)).comp
      (oppositeSpecializationRingHom D))
    (localizedDenominatorUnits D S)
    (fun s => by
      rw [localizedDenominatorUnits_val]
      rfl)

@[simp] theorem localizedOppositeSpecialization_oreDiv
    (b : Bᵐᵒᵖ) (s : OppositeDenominators D S) :
    localizedOppositeSpecialization D S (b /ₒ s) =
      ((localizedDenominatorUnits D S s)⁻¹ : Units (Localization S)) *
        algebraMap R (Localization S) (D.pi b.unop) :=
  rfl

@[simp] theorem localizedOppositeSpecialization_numerator (b : Bᵐᵒᵖ) :
    localizedOppositeSpecialization D S
        (OreLocalization.numeratorHom b) =
      algebraMap R (Localization S) (D.pi b.unop) := by
  exact OreLocalization.universalHom_commutes _ _ _

@[simp] theorem localizedOppositeSpecialization_parameter :
    localizedOppositeSpecialization D S
        (OreLocalization.numeratorHom (MulOpposite.op D.c)) = 0 := by
  simp [D.pi_c]

/-- Surjectivity of the original specialization survives localization. This
is a ring-level statement; it does not identify the kernel. -/
theorem localizedOppositeSpecialization_surjective :
    Function.Surjective (localizedOppositeSpecialization D S) := by
  intro z
  refine Localization.induction_on z ?_
  rintro ⟨r, s⟩
  obtain ⟨a, ha⟩ := D.pi_surjective r
  obtain ⟨b, hb⟩ := D.pi_surjective (s : R)
  let sb : OppositeDenominators D S :=
    ⟨MulOpposite.op b, by
      change D.pi b ∈ S
      rw [hb]
      exact s.property⟩
  refine ⟨(MulOpposite.op a) /ₒ sb, ?_⟩
  rw [localizedOppositeSpecialization_oreDiv]
  change
    ((OreLocalization.numeratorUnit (denominatorMap D S sb))⁻¹ :
        Units (Localization S)) *
        algebraMap R (Localization S) (D.pi a) =
      Localization.mk r s
  rw [ha]
  change (1 /ₒ denominatorMap D S sb) * (r /ₒ 1) = r /ₒ s
  rw [OreLocalization.mul_div_one]
  have hs : denominatorMap D S sb = s := Subtype.ext hb
  rw [hs]
  simp

end Ore

#print axioms oppositeSpecializationRingHom
#print axioms localizationNumeratorUnits
#print axioms localizedDenominatorUnits
#print axioms localizedOppositeSpecialization
#print axioms localizedOppositeSpecialization_parameter
#print axioms localizedOppositeSpecialization_surjective

end


end Stafford38.Characteristic.SquareZeroLocalizedRing
