import Stafford38.Geometry.A0ChartFormalEtale
#print axioms Stafford38.Geometry.A0ChartFormalEtale.formallyEtale_originalAffineChartToCommonOpen
#check Stafford38.Geometry.A0ChartFormalEtale.originalAffineChartToCommonOpen
