import Stafford38.Geometry.ActualSmoothOpenChartNumerator

set_option autoImplicit false

open Stafford38.Geometry.ActualSmoothOpenChartNumerator
open Stafford38.Geometry.GeneralDivisorialVisibleFrame

#check exists_nonzero_homogenized_numerator
#print axioms exists_nonzero_homogenized_numerator
