module
public import Stafford38.Geometry.GeneralTangentLimitCriterion

@[expose] public section

namespace Stafford38.Geometry.GenericFibreMatrixColumnsConsumer

open Stafford38.Geometry.GeneralTangentLimitCriterion

/-- The integer lattice generated by 2 spans the rational line, although 1
is not an integer multiple of 2. This checks the scalar-extension direction
with a literal denominator. -/
def lattice : Submodule ℤ (Fin 1 → ℤ) :=
  Submodule.span ℤ {fun _ => (2 : ℤ)}

theorem rational_one_mem_generic_fibre :
    (fun _ : Fin 1 => (1 : ℚ)) ∈ genericFibre (K := ℚ) lattice := by
  have htwo : (fun _ : Fin 1 => (2 : ℤ)) ∈ lattice :=
    Submodule.subset_span (Set.mem_singleton _)
  have htwoQ : (fun _ : Fin 1 => (2 : ℚ)) ∈ genericFibre (K := ℚ) lattice := by
    apply Submodule.subset_span
    exact ⟨fun _ => (2 : ℤ), htwo, rfl⟩
  have h := Submodule.smul_mem (genericFibre (K := ℚ) lattice) (1 / 2 : ℚ) htwoQ
  convert h using 1
  ext i
  norm_num

theorem columns_identify_same_generic_fibre :
    genericFibre (K := ℚ) lattice =
      Submodule.span ℚ (Set.range fun _ : Fin 1 => fun _ : Fin 1 => (2 : ℚ)) := by
  apply genericFibre_eq_span_matrixColumns lattice
    (fun _ : Fin 1 => fun _ : Fin 1 => (2 : ℤ))
  congr 1
  ext v
  simp

#print axioms rational_one_mem_generic_fibre
#print axioms columns_identify_same_generic_fibre
#print axioms Stafford38.Geometry.GeneralTangentLimitCriterion.genericFibre_eq_span_matrixColumns

end Stafford38.Geometry.GenericFibreMatrixColumnsConsumer
