import Stafford38.Geometry.SmoothLocalTiltedArcAxisLift

#check Stafford38.Geometry.SmoothLocalTiltedArcAxisLift.tilted_local_axis_lift_of_selected_coordinate_rows_on_arc
#check Stafford38.Geometry.SmoothLocalTiltedArcAxisLift.exists_tilted_local_axis_lift_of_selected_coordinate_rows
#print axioms Stafford38.Geometry.SmoothLocalTiltedArcAxisLift.tilted_local_axis_lift_of_selected_coordinate_rows_on_arc
#print axioms Stafford38.Geometry.SmoothLocalTiltedArcAxisLift.exists_tilted_local_axis_lift_of_selected_coordinate_rows
