import Mathlib

/-!
# The evolutionary Stafford certificate

Let `D` be a ring containing a Weyl pair `p * x - x * p = 1`, let `B` be any set
of elements commuting with both `x` and `p`, and let

    d = p ^ r - ∑ⱼ aⱼ * x ^ j,     aⱼ ∈ B.

This file machine-checks that the right ideal generated by `d` and `x ^ r * d`
is the whole ring, with the Stafford cofactor fixed to `x ^ r` independently of
`B`, of the coefficients `aⱼ`, and of the size of the support.

The proof has three separated layers.

* `stafford_of_bezout` is a pure ring identity: it consumes a corner
  commutator, an elimination identity, and a Bézout identity, and produces the
  certificate.  No Weyl structure is used.
* The `Weyl` section proves the Euler shift calculus and the two factorial
  identities `p ^ r * x ^ r = rising E r`, `x ^ r * p ^ r = falling E r`, where
  `E = x * p`.
* `potential_elimination` performs the simultaneous shifted cancellation that
  removes every potential coefficient at once.

`evolution_stafford_certificate` assembles the three. The Bézout identity it
consumes is discharged in `Stafford38.EulerRootSeparation`, which proves the
needed polynomial coprimality under every positive integer shift.

Convention: all ideals here are **right** ideals, matching the repository
convention.  Statements are written as `d * R + x ^ r * d * S = 1`.
-/

namespace Stafford38.Evolution

open Polynomial

/-! ## Layer 1: the pure ring assembly -/

section Assembly

variable {D : Type*} [Ring D]

/-- The certificate assembly.  `c` is the corner commutator `d * F - F * d`,
`h` is the eliminated polynomial, `q` the elimination cofactor, and `a`, `b` a
Bézout pair for `c` and `h`.  Nothing about `D` beyond ring axioms is used. -/
theorem stafford_of_bezout (d F c h l q a b : D)
    (hcorner : d * F - F * d = c)
    (helim : d * F * l = h - c * q)
    (hbezout : c * a + h * b = 1) :
    d * (F * a + F * (l + q) * b) + F * d * (-a - q * b) = 1 := by
  have expand :
      d * (F * a + F * (l + q) * b) + F * d * (-a - q * b)
        = (d * F - F * d) * a + (d * F * l) * b + (d * F - F * d) * (q * b) := by
    noncomm_ring
  rw [expand, hcorner, helim]
  have : (h - c * q) * b + c * (q * b) = h * b := by noncomm_ring
  rw [show c * a + (h - c * q) * b + c * (q * b) = c * a + ((h - c * q) * b + c * (q * b)) by
        noncomm_ring, this, hbezout]

end Assembly

/-! ## Layer 2: the Euler shift calculus -/

section Weyl

variable {D : Type*} [Ring D] {x p : D}

/-- The Euler operator. -/
def euler (x p : D) : D := x * p

/-- `(E + 1)(E + 2) ⋯ (E + n)`. -/
def rising (E : D) : ℕ → D
  | 0 => 1
  | (n + 1) => rising E n * (E + ((n : D) + 1))

/-- `E (E - 1) ⋯ (E - (n-1))`. -/
def falling (E : D) : ℕ → D
  | 0 => 1
  | (n + 1) => falling E n * (E - (n : D))

@[simp] lemma rising_zero (E : D) : rising E 0 = 1 := rfl
@[simp] lemma falling_zero (E : D) : falling E 0 = 1 := rfl

lemma rising_succ (E : D) (n : ℕ) :
    rising E (n + 1) = rising E n * (E + ((n : D) + 1)) := rfl

lemma falling_succ (E : D) (n : ℕ) :
    falling E (n + 1) = falling E n * (E - (n : D)) := rfl

variable (hw : p * x = x * p + 1)

include hw

/-- `E * x = x * (E + 1)`. -/
lemma euler_mul_x : euler x p * x = x * (euler x p + 1) := by
  simp only [euler]
  rw [mul_assoc, hw]

/-- `E * p = p * (E - 1)`. -/
lemma euler_mul_p : euler x p * p = p * (euler x p - 1) := by
  simp only [euler]
  rw [mul_sub, ← mul_assoc, hw]
  noncomm_ring

/-- `E * x ^ n = x ^ n * (E + n)`. -/
lemma euler_mul_x_pow (n : ℕ) :
    euler x p * x ^ n = x ^ n * (euler x p + (n : D)) := by
  induction n with
  | zero => simp
  | succ n ih =>
      have hcast : ((n : D)) * x = x * (n : D) := (Nat.cast_commute n x).eq
      rw [pow_succ, ← mul_assoc, ih, mul_assoc, add_mul, euler_mul_x hw, hcast]
      push_cast
      noncomm_ring

/-- `E * p ^ n = p ^ n * (E - n)`. -/
lemma euler_mul_p_pow (n : ℕ) :
    euler x p * p ^ n = p ^ n * (euler x p - (n : D)) := by
  induction n with
  | zero => simp
  | succ n ih =>
      have hcast : ((n : D)) * p = p * (n : D) := (Nat.cast_commute n p).eq
      rw [pow_succ, ← mul_assoc, ih, mul_assoc, sub_mul, euler_mul_p hw, hcast]
      push_cast
      noncomm_ring

/-- `E ^ m * x ^ n = x ^ n * (E + n) ^ m`. -/
lemma euler_pow_mul_x_pow (m n : ℕ) :
    euler x p ^ m * x ^ n = x ^ n * (euler x p + (n : D)) ^ m := by
  induction m with
  | zero => simp
  | succ m ih =>
      rw [pow_succ, mul_assoc, euler_mul_x_pow hw, ← mul_assoc, ih, mul_assoc, ← pow_succ]

/-- The rising factorial identity `p ^ n * x ^ n = (E+1) ⋯ (E+n)`. -/
lemma pow_mul_pow_eq_rising (n : ℕ) : p ^ n * x ^ n = rising (euler x p) n := by
  induction n with
  | zero => simp
  | succ n ih =>
      have hstep : p ^ (n + 1) * x ^ (n + 1) = p ^ n * (euler x p + 1) * x ^ n := by
        rw [pow_succ, pow_succ' x n, mul_assoc, ← mul_assoc p x, hw]
        simp only [euler]
        noncomm_ring
      rw [hstep, mul_assoc, add_mul, one_mul, euler_mul_x_pow hw,
        show x ^ n * (euler x p + (n : D)) + x ^ n
            = x ^ n * (euler x p + ((n : D) + 1)) by noncomm_ring,
        ← mul_assoc, ih, rising_succ]

/-- The falling factorial identity `x ^ n * p ^ n = E (E-1) ⋯ (E-(n-1))`. -/
lemma pow_mul_pow_eq_falling (n : ℕ) : x ^ n * p ^ n = falling (euler x p) n := by
  induction n with
  | zero => simp
  | succ n ih =>
      have hstep : x ^ (n + 1) * p ^ (n + 1) = x ^ n * euler x p * p ^ n := by
        rw [pow_succ x n, pow_succ' p n, mul_assoc]
        simp only [euler]
        noncomm_ring
      rw [hstep, mul_assoc, euler_mul_p_pow hw, ← mul_assoc, ih, falling_succ]

end Weyl

section Elimination

variable {D : Type*} [Ring D] {x p : D}

/-! ### Polynomial shift calculus -/

variable {k : Type*} [CommRing k] [Algebra k D]

/-- `f(E) * x ^ n = x ^ n * f(E + n)` for every polynomial `f`. -/
lemma aeval_euler_mul_x_pow (hw : p * x = x * p + 1) (n : ℕ) (f : k[X]) :
    aeval (euler x p) f * x ^ n = x ^ n * aeval (euler x p + (n : D)) f := by
  induction f using Polynomial.induction_on' with
  | add f g hf hg => simp only [map_add, add_mul, mul_add, hf, hg]
  | monomial m a =>
      simp only [aeval_monomial]
      rw [mul_assoc, euler_pow_mul_x_pow hw, ← mul_assoc, ← mul_assoc,
        (Algebra.commutes a (x ^ n)).symm]

/-- An element commuting with `E` commutes with every polynomial in `E`. -/
lemma commute_aeval_euler {a E : D} (h : a * E = E * a) (f : k[X]) :
    a * aeval E f = aeval E f * a := by
  have hc : Commute a E := h
  induction f using Polynomial.induction_on' with
  | add f g hf hg => simp only [map_add, mul_add, add_mul, hf, hg]
  | monomial m b =>
      simp only [aeval_monomial]
      have c1 : Commute a (algebraMap k D b) := (Algebra.commutes b a).symm
      exact (c1.mul_right (hc.pow_right m)).eq

/-- The rising factorial as a polynomial. -/
noncomputable def risingPoly (k : Type*) [CommRing k] : ℕ → k[X]
  | 0 => 1
  | (n + 1) => risingPoly k n * (X + Polynomial.C ((n : k) + 1))

/-- The falling factorial as a polynomial. -/
noncomputable def fallingPoly (k : Type*) [CommRing k] : ℕ → k[X]
  | 0 => 1
  | (n + 1) => fallingPoly k n * (X - Polynomial.C (n : k))

/-- The Euler corner polynomial `C_r = R₊ - R₋`; its evaluation at `E` is the
commutator `p ^ r x ^ r - x ^ r p ^ r`. -/
noncomputable def cornerPoly (k : Type*) [CommRing k] (r : ℕ) : k[X] :=
  risingPoly k r - fallingPoly k r

@[simp] lemma risingPoly_zero : risingPoly k 0 = 1 := rfl

lemma risingPoly_succ (n : ℕ) :
    risingPoly k (n + 1) = risingPoly k n * (X + Polynomial.C ((n : k) + 1)) := rfl

@[simp] lemma fallingPoly_zero : fallingPoly k 0 = 1 := rfl

lemma fallingPoly_succ (n : ℕ) :
    fallingPoly k (n + 1) = fallingPoly k n * (X - Polynomial.C (n : k)) := rfl

lemma aeval_risingPoly (E : D) (n : ℕ) :
    aeval E (risingPoly k n) = rising E n := by
  induction n with
  | zero => simp [risingPoly_zero]
  | succ n ih => simp [risingPoly_succ, rising_succ, ih]

lemma aeval_fallingPoly (E : D) (n : ℕ) :
    aeval E (fallingPoly k n) = falling E n := by
  induction n with
  | zero => simp [fallingPoly_zero]
  | succ n ih => simp [fallingPoly_succ, falling_succ, ih]

lemma aeval_cornerPoly (E : D) (r : ℕ) :
    aeval E (cornerPoly k r) = rising E r - falling E r := by
  simp [cornerPoly, aeval_risingPoly, aeval_fallingPoly]

/-! ### Simultaneous elimination of every potential coefficient -/

/-- `∑ⱼ aⱼ * x ^ nⱼ`, the potential written in the given support. -/
def potentialSum (x : D) : List (D × ℕ) → D
  | [] => 0
  | (t :: ts) => t.1 * x ^ t.2 + potentialSum x ts

/-- `∏ⱼ C(X + nⱼ)`, one shift of the corner polynomial per potential term. -/
noncomputable def shiftedProd (C : k[X]) : List (D × ℕ) → k[X]
  | [] => 1
  | (t :: ts) => C.comp (X + Polynomial.C ((t.2 : ℕ) : k)) * shiftedProd C ts

omit [Ring D] [Algebra k D] in
@[simp] lemma shiftedProd_nil (C : k[X]) : shiftedProd C ([] : List (D × ℕ)) = 1 := rfl

omit [Ring D] [Algebra k D] in
lemma shiftedProd_cons (C : k[X]) (t : D × ℕ) (ts : List (D × ℕ)) :
    shiftedProd C (t :: ts)
      = C.comp (X + Polynomial.C ((t.2 : ℕ) : k)) * shiftedProd C ts := rfl

lemma aeval_comp_shift (E : D) (C : k[X]) (n : ℕ) :
    aeval E (C.comp (X + Polynomial.C ((n : ℕ) : k))) = aeval (E + (n : D)) C := by
  simp [aeval_comp]

/-- **Simultaneous shifted cancellation.**  Multiplying the potential on the
right by one shift of the corner polynomial per term turns the whole potential
into a left multiple of the corner polynomial.  Every coefficient is eliminated
at once, and the coefficients are never assumed to commute with one another. -/
theorem potential_elimination (hw : p * x = x * p + 1) (C : k[X])
    (terms : List (D × ℕ)) (hcomm : ∀ t ∈ terms, t.1 * euler x p = euler x p * t.1) :
    ∃ q : D, potentialSum x terms * aeval (euler x p) (shiftedProd C terms)
      = aeval (euler x p) C * q := by
  induction terms with
  | nil => exact ⟨0, by simp [potentialSum, shiftedProd]⟩
  | cons t ts ih =>
      obtain ⟨q, hq⟩ := ih fun s hs => hcomm s (List.mem_cons_of_mem _ hs)
      have ht : t.1 * euler x p = euler x p * t.1 := hcomm t List.mem_cons_self
      set E := euler x p with hE
      set Cs : k[X] := C.comp (X + Polynomial.C ((t.2 : ℕ) : k)) with hCs
      set L : k[X] := shiftedProd C ts with hL
      -- the key exchange: `x ^ n * C(E + n) = C(E) * x ^ n`
      have hswap : x ^ t.2 * aeval E Cs = aeval E C * x ^ t.2 := by
        rw [hCs, aeval_comp_shift, ← aeval_euler_mul_x_pow hw]
      refine ⟨t.1 * x ^ t.2 * aeval E L + q * aeval E Cs, ?_⟩
      have hprod : shiftedProd C (t :: ts) = Cs * L := rfl
      rw [potentialSum, hprod, map_mul, add_mul, mul_add]
      congr 1
      · calc t.1 * x ^ t.2 * (aeval E Cs * aeval E L)
            = t.1 * (x ^ t.2 * aeval E Cs) * aeval E L := by noncomm_ring
          _ = t.1 * (aeval E C * x ^ t.2) * aeval E L := by rw [hswap]
          _ = (t.1 * aeval E C) * (x ^ t.2 * aeval E L) := by noncomm_ring
          _ = aeval E C * (t.1 * x ^ t.2 * aeval E L) := by
              rw [commute_aeval_euler ht C]; noncomm_ring
      · calc potentialSum x ts * (aeval E Cs * aeval E L)
            = potentialSum x ts * (aeval E L * aeval E Cs) := by
              rw [← map_mul, ← map_mul, mul_comm]
          _ = (potentialSum x ts * aeval E L) * aeval E Cs := by noncomm_ring
          _ = aeval E C * q * aeval E Cs := by rw [hq]
          _ = aeval E C * (q * aeval E Cs) := by noncomm_ring

/-! ### The main theorem -/

/-- Shifting every exponent of the potential support by `r`. -/
def shiftSupport (terms : List (D × ℕ)) (r : ℕ) : List (D × ℕ) :=
  terms.map fun t => (t.1, t.2 + r)

lemma potentialSum_mul_pow (x : D) (terms : List (D × ℕ)) (r : ℕ) :
    potentialSum x terms * x ^ r = potentialSum x (shiftSupport terms r) := by
  induction terms with
  | nil => simp [potentialSum, shiftSupport]
  | cons t ts ih =>
      simp only [shiftSupport, List.map_cons, potentialSum, add_mul]
      rw [mul_assoc, ← pow_add]
      congr 1

lemma commute_potentialSum_x {terms : List (D × ℕ)}
    (h : ∀ t ∈ terms, t.1 * x = x * t.1) :
    potentialSum x terms * x = x * potentialSum x terms := by
  induction terms with
  | nil => simp [potentialSum]
  | cons t ts ih =>
      have ht := h t List.mem_cons_self
      rw [potentialSum, add_mul, mul_add, ih fun s hs => h s (List.mem_cons_of_mem _ hs)]
      congr 1
      calc t.1 * x ^ t.2 * x = t.1 * x * x ^ t.2 := by rw [mul_assoc, mul_assoc, ← pow_succ,
            ← pow_succ']
        _ = x * (t.1 * x ^ t.2) := by rw [ht, mul_assoc]

lemma commute_potentialSum_x_pow {terms : List (D × ℕ)}
    (h : ∀ t ∈ terms, t.1 * x = x * t.1) (r : ℕ) :
    potentialSum x terms * x ^ r = x ^ r * potentialSum x terms := by
  induction r with
  | zero => simp
  | succ r ih =>
      rw [pow_succ, ← mul_assoc, ih, mul_assoc, commute_potentialSum_x h, ← mul_assoc]

/-- **Aggregate-commutation evolutionary Stafford theorem.**

Let `D` be any ring carrying a Weyl pair `p * x - x * p = 1`, let the potential
`A = ∑ⱼ aⱼ * x ^ j` be a displayed finite potential.  Assume directly that
the shifted coefficients commute with the Euler operator and that the
aggregate potential commutes with `x ^ r`; no coefficientwise commutation with
`x` or `p` is required.  Put

    d = p ^ r - A.

Given a Bézout identity for the corner polynomial `C_r` against
`R₊ · ∏ⱼ C_r(X + r + j)` (supplied by `Stafford38.EulerRootSeparation`), the right ideal
generated by `d` and `x ^ r * d` is the whole ring, with the explicit
certificate below. -/
theorem evolution_stafford_certificate_of_aggregate_commutation
    (hw : p * x = x * p + 1) (r : ℕ) (terms : List (D × ℕ))
    (hcommE : ∀ t ∈ shiftSupport terms r,
      t.1 * euler x p = euler x p * t.1)
    (hAxr : potentialSum x terms * x ^ r =
      x ^ r * potentialSum x terms)
    (α β : k[X])
    (hbezout : cornerPoly k r * α
        + (risingPoly k r * shiftedProd (cornerPoly k r) (shiftSupport terms r)) * β = 1) :
    ∃ R S : D, (p ^ r - potentialSum x terms) * R
        + x ^ r * (p ^ r - potentialSum x terms) * S = 1 := by
  set E := euler x p with hE
  set A := potentialSum x terms with hA
  set d := p ^ r - A with hd
  set C : k[X] := cornerPoly k r with hC
  set L : k[X] := shiftedProd C (shiftSupport terms r) with hL
  have hcommE' : ∀ t ∈ shiftSupport terms r, t.1 * E = E * t.1 := by
    simpa [hE] using hcommE
  -- the corner commutator
  have hcorner : d * x ^ r - x ^ r * d = aeval E C := by
    rw [hd, sub_mul, mul_sub, hAxr, aeval_cornerPoly, pow_mul_pow_eq_rising hw,
      pow_mul_pow_eq_falling hw]
    abel
  -- simultaneous elimination
  obtain ⟨q, hq⟩ := potential_elimination hw C (shiftSupport terms r) hcommE'
  have helim : d * x ^ r * aeval E L
      = aeval E (risingPoly k r * L) - aeval E C * q := by
    have hAxr : A * x ^ r = potentialSum x (shiftSupport terms r) :=
      potentialSum_mul_pow x terms r
    rw [hd, sub_mul, hAxr, pow_mul_pow_eq_rising hw, sub_mul, hq, map_mul,
      aeval_risingPoly]
  -- Bézout, transported into `D`
  have hbez : aeval E C * aeval E α + aeval E (risingPoly k r * L) * aeval E β = 1 := by
    have := congrArg (aeval (R := k) E) hbezout
    simpa [map_add, map_mul] using this
  exact ⟨_, _, stafford_of_bezout d (x ^ r) (aeval E C) (aeval E (risingPoly k r * L))
    (aeval E L) q (aeval E α) (aeval E β) hcorner helim hbez⟩

/-! The original coefficientwise theorem is a corollary of the aggregate
interface.  Keeping it explicit preserves the existing API while exposing
the strictly weaker hypotheses as a reusable producer contract. -/
theorem evolution_stafford_certificate
    (hw : p * x = x * p + 1) (r : ℕ) (terms : List (D × ℕ))
    (hx : ∀ t ∈ terms, t.1 * x = x * t.1)
    (hp : ∀ t ∈ terms, t.1 * p = p * t.1)
    (α β : k[X])
    (hbezout : cornerPoly k r * α
        + (risingPoly k r * shiftedProd (cornerPoly k r) (shiftSupport terms r)) * β = 1) :
    ∃ R S : D, (p ^ r - potentialSum x terms) * R
        + x ^ r * (p ^ r - potentialSum x terms) * S = 1 := by
  have hcommE : ∀ t ∈ shiftSupport terms r,
      t.1 * euler x p = euler x p * t.1 := by
    rintro ⟨a, n⟩ hmem
    simp only [shiftSupport, List.mem_map] at hmem
    obtain ⟨⟨b, m⟩, hb, heq⟩ := hmem
    have hba : b = a := congrArg Prod.fst heq
    subst hba
    have h1 : b * x = x * b := hx _ hb
    have h2 : b * p = p * b := hp _ hb
    simp only [euler]
    rw [← mul_assoc, h1, mul_assoc, h2, mul_assoc]
  have hAxr : potentialSum x terms * x ^ r =
      x ^ r * potentialSum x terms := commute_potentialSum_x_pow hx r
  exact evolution_stafford_certificate_of_aggregate_commutation
    hw r terms hcommE hAxr α β hbezout

end Elimination

end Stafford38.Evolution
