import Stafford38.Characteristic.CanonicalNormalSymbolFiniteness

/-!
# The coordinate hyperplane is noncharacteristic for the canonical quotient

Manuscript Appendix B (Definition B.1, Proposition B.2). Let `H = {x₁ = 0}` in
affine `n+1`-space and let `J ⊆ k[x, ξ]` be a characteristic ideal. The
projection `V(J) ∩ T*X|_H → T*H` forgets the covariable `ξ₁`. On coordinate
rings it is the map from `k[T*H] = k[x₂, …, ξ₂, …]` (all phase variables except
`x₁` and `ξ₁`) to `k[x, ξ] ⧸ (J + (x₁))`. Following Schnell's Definition 15.6,
`H` is *noncharacteristic* for `J` when this map is finite.

For the canonical quotient `Q = A/(dA + x₁ᴺ dA)` with `d` monic of degree `N`
in `∂₁`, the characteristic ideal `J = Ann gr Q` (the order initial ideal, see
`annihilator_orderAssociatedGradedModule`) contains the order symbol `P`, which
is monic of degree `N` in `ξ₁` over the other variables. Hence
`k[x, ξ] ⧸ (J + (x₁))` is a quotient of an extension of the base generated by
`1, ξ₁, …, ξ₁ᴺ⁻¹`, and the projection is finite. Moreover every prime of
`Char Q` containing all tangential covariables `ξ₂, …` contains `ξ₁`: the
support meets the conormal bundle of `H` only in the zero section.
-/

namespace Stafford38.NoncharacteristicHyperplane

open Stafford38.Characteristic
open Stafford38.CharacteristicInitialIdeal
open Stafford38.CharacteristicAssociatedGradedModule
open Stafford38.Characteristic.NormalSymbolPolynomial
open Stafford38.Characteristic.CanonicalNormalSymbolFiniteness
open Stafford38.Characteristic.CanonicalNormalAxisSupport
open Stafford38.WeylIteratedEquivalence
open Stafford38.WeylPBWMonicBridge
open Stafford38.WeylEulerResidue

noncomputable section

variable {k : Type*} [Field k]

/-- The phase variables of `T*H`: all except the coordinate `x₁` and its
covariable `ξ₁`. -/
abbrev HyperplaneVar (n : ℕ) :=
  {v : PhaseVar (n + 1) //
    v ≠ Sum.inr (0 : Fin (n + 1)) ∧ v ≠ Sum.inl (0 : Fin (n + 1))}

/-- The coordinate ring `k[T*H]`. -/
abbrev HyperplaneCotangentRing (n : ℕ) := MvPolynomial (HyperplaneVar n) k

/-- The ideal cutting out `V(J) ∩ T*X|_H`. -/
def restrictedIdeal {n : ℕ} (J : Ideal (SymbolRing k (n + 1))) :
    Ideal (SymbolRing k (n + 1)) :=
  J ⊔ Ideal.span {MvPolynomial.X (Sum.inl (0 : Fin (n + 1)))}

/-- The map from the ring of all symbols except `ξ₁` to the restricted
characteristic ring. -/
def normalCoeffProjection (n : ℕ) (J : Ideal (SymbolRing k (n + 1))) :
    normalCoeffRing (k := k) n →ₐ[k] SymbolRing k (n + 1) ⧸ restrictedIdeal J :=
  (Ideal.Quotient.mkₐ k (restrictedIdeal J)).comp
    ((normalSymbolAlgEquiv (k := k) n).symm.toAlgHom.comp
      (IsScalarTower.toAlgHom k (normalCoeffRing (k := k) n)
        (Polynomial (normalCoeffRing (k := k) n))))

/-- The inclusion `k[T*H] → k[x₁, x₂, …, ξ₂, …]`. -/
def hyperplaneInclusion (n : ℕ) :
    HyperplaneCotangentRing (k := k) n →ₐ[k] normalCoeffRing (k := k) n :=
  MvPolynomial.rename fun v => ⟨v.1, v.2.1⟩

/-- Setting `x₁ = 0`: `k[x₁, x₂, …, ξ₂, …] → k[T*H]`. -/
def hyperplaneRestriction (n : ℕ) :
    normalCoeffRing (k := k) n →ₐ[k] HyperplaneCotangentRing (k := k) n :=
  MvPolynomial.aeval fun v =>
    if h : v.1 = Sum.inl (0 : Fin (n + 1)) then 0 else MvPolynomial.X ⟨v.1, v.2, h⟩

/-- The projection `V(J) ∩ T*X|_H → T*H` on coordinate rings. -/
def hyperplaneProjection (n : ℕ) (J : Ideal (SymbolRing k (n + 1))) :
    HyperplaneCotangentRing (k := k) n →ₐ[k] SymbolRing k (n + 1) ⧸ restrictedIdeal J :=
  (normalCoeffProjection n J).comp (hyperplaneInclusion n)

/-- Definition B.1 for `X = 𝔸ⁿ⁺¹`, `H = {x₁ = 0}` and a characteristic ideal
`J`: the projection `V(J) ∩ T*X|_H → T*H` is finite. -/
def IsNoncharacteristic {n : ℕ} (J : Ideal (SymbolRing k (n + 1))) : Prop :=
  (hyperplaneProjection (k := k) n J).toRingHom.Finite

theorem normalSymbolAlgEquiv_symm_C_X {n : ℕ} (v : PhaseVar (n + 1))
    (hv : v ≠ Sum.inr (0 : Fin (n + 1))) :
    (normalSymbolAlgEquiv (k := k) n).symm (Polynomial.C (MvPolynomial.X ⟨v, hv⟩)) =
      MvPolynomial.X v :=
  (normalSymbolAlgEquiv (k := k) n).symm_apply_eq.mpr
    (normalSymbolAlgEquiv_otherVariable (k := k) n v hv).symm

/-- `x₁` vanishes on the restricted ring, so the projection from the ring of all
symbols except `ξ₁` factors through setting `x₁ = 0`. -/
theorem normalCoeffProjection_eq_comp {n : ℕ} (J : Ideal (SymbolRing k (n + 1))) :
    normalCoeffProjection n J =
      (hyperplaneProjection n J).comp (hyperplaneRestriction (k := k) n) := by
  apply MvPolynomial.algHom_ext
  intro v
  by_cases h : v.1 = Sum.inl (0 : Fin (n + 1))
  · have hv : v = ⟨Sum.inl 0, h ▸ v.2⟩ := Subtype.ext h
    have hzero : normalCoeffProjection n J (MvPolynomial.X v) = 0 := by
      rw [hv]
      simp only [normalCoeffProjection, AlgHom.comp_apply, IsScalarTower.coe_toAlgHom',
        Polynomial.algebraMap_apply, Algebra.algebraMap_self, RingHom.id_apply,
        Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.mem_sup_right (Ideal.subset_span
        (Set.mem_singleton_iff.mpr (normalSymbolAlgEquiv_symm_C_X _ _)))
    rw [hzero, AlgHom.comp_apply, hyperplaneRestriction, MvPolynomial.aeval_X, dif_pos h,
      map_zero]
  · rw [AlgHom.comp_apply, hyperplaneRestriction, MvPolynomial.aeval_X, dif_neg h,
      hyperplaneProjection, AlgHom.comp_apply, hyperplaneInclusion, MvPolynomial.rename_X]

variable {n N : ℕ}

/-- The order symbol lies in the characteristic ideal, and its normal form is
monic in `ξ₁`; therefore the projection forgetting `ξ₁` is finite. -/
theorem normalCoeffProjection_finite (d : PresentedWeyl k (n + 1))
    (hd : IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d) :
    (normalCoeffProjection n
      (orderInitialIdeal k (canonicalRightIdeal (presentedCoordinate k n) d N))).toRingHom.Finite := by
  set J := orderInitialIdeal k (canonicalRightIdeal (presentedCoordinate k n) d N)
  set e := normalSymbolAlgEquiv (k := k) n
  set g := canonicalNormalPolynomial (k := k) (n := n) (N := N) d
  have hg : g.Monic := canonicalNormalPolynomial_monic hd
  let F : Polynomial (normalCoeffRing (k := k) n) →+* SymbolRing k (n + 1) ⧸ restrictedIdeal J :=
    (Ideal.Quotient.mk (restrictedIdeal J)).comp e.symm.toRingEquiv.toRingHom
  have hFg : F g = 0 := by
    change Ideal.Quotient.mk (restrictedIdeal J) (e.symm g) = 0
    rw [Ideal.Quotient.eq_zero_iff_mem]
    apply Ideal.mem_sup_left
    change e.symm (e _) ∈ J
    rw [AlgEquiv.symm_apply_apply]
    exact canonical_orderPrincipalComponent_mem_initialIdeal k n N hd
  have hF : ∀ a ∈ Ideal.span {g}, F a = 0 := by
    intro a ha
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp ha
    rw [map_mul, hFg, mul_zero]
  let ψ : AdjoinRoot g →+* SymbolRing k (n + 1) ⧸ restrictedIdeal J :=
    Ideal.Quotient.lift (Ideal.span {g}) F hF
  have hψ : Function.Surjective ψ :=
    Ideal.Quotient.lift_surjective_of_surjective _ hF
      ((Ideal.Quotient.mk_surjective).comp e.symm.surjective)
  have hof : (AdjoinRoot.of g).Finite := by
    rw [← AdjoinRoot.algebraMap_eq]
    exact RingHom.finite_algebraMap.mpr (AdjoinRoot.powerBasis' hg).finite
  have hcomp : (normalCoeffProjection n J).toRingHom = ψ.comp (AdjoinRoot.of g) := by
    ext r <;> rfl
  rw [hcomp]
  exact (RingHom.Finite.of_surjective ψ hψ).comp hof

/-- **Proposition B.2 (finiteness).** `H = {x₁ = 0}` is noncharacteristic for the
canonical quotient: the projection from `Char Q ∩ T*X|_H` to `T*H` is finite. -/
theorem canonical_isNoncharacteristic (d : PresentedWeyl k (n + 1))
    (hd : IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d) :
    IsNoncharacteristic (k := k)
      (orderInitialIdeal k (canonicalRightIdeal (presentedCoordinate k n) d N)) := by
  have h := normalCoeffProjection_finite d hd
  rw [normalCoeffProjection_eq_comp] at h
  exact RingHom.Finite.of_comp_finite h

/-- The same statement for the annihilator of the associated graded module,
which is the characteristic ideal of the manuscript. -/
theorem canonical_isNoncharacteristic_annihilator (d : PresentedWeyl k (n + 1))
    (hd : IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d) :
    IsNoncharacteristic (k := k)
      (Module.annihilator (SymbolRing k (n + 1))
        (OrderAssociatedGradedModule k (canonicalRightIdeal (presentedCoordinate k n) d N))) := by
  rw [annihilator_orderAssociatedGradedModule]
  exact canonical_isNoncharacteristic d hd

/-- **Proposition B.2 (zero section).** A point of `Char Q` whose tangential
covariables `ξ₂, …` vanish also has `ξ₁ = 0`; in particular `Char Q ∩ T*_H X`
lies in the zero section. -/
theorem canonicalSupport_conormal_subset_zeroSection (d : PresentedWeyl k (n + 1))
    (hd : IsPBWMonicAt k (.inr (0 : Fin (n + 1))) N d)
    {p : PrimeSpectrum (SymbolRing k (n + 1))}
    (hp : p ∈ orderCharacteristicSupport k
      (canonicalRightIdeal (presentedCoordinate k n) d N))
    (htan : ∀ i : Fin (n + 1), i ≠ 0 → MvPolynomial.X (.inr i) ∈ p.asIdeal) :
    ∀ i : Fin (n + 1), MvPolynomial.X (.inr i) ∈ p.asIdeal := by
  intro i
  by_cases hi : i = 0
  · subst hi
    exact normalMomentum_mem_of_mem_canonicalSupport d hd hp htan
  · exact htan i hi

#print axioms canonical_isNoncharacteristic
#print axioms canonical_isNoncharacteristic_annihilator
#print axioms canonicalSupport_conormal_subset_zeroSection

end
end Stafford38.NoncharacteristicHyperplane
